### ISSUE TITLE
Adding a border throws off calcs and native scroll bar appears

### ISSUE THREAD

**Issue by furroy** [Grsmto/simplebar#101]
I was trying to duplicate the scrollbars on Slack which appear to have  a thick border, but when I added CSS style border: 4px solid #070707;  to either the bar or the thumb, the native scrollbar shows up.

Otherwise, excellent little tool.

**Comment by Grsmto** [comment]
Yeah probably it breaks the calculation of the position.
You can try replicate the same style using `box-shadow` instead of `border`.
