### ISSUE TITLE
Bugs everywhere important issue which can imporve many things

### ISSUE THREAD

**Issue by qarth1** [Grsmto/simplebar#103]
I'm trying to resolve the issue where there is one panel in which there is one 
<div class="row">
<div class="col-md-6">
</div>
<div class="col-md-5">
</div>
<div class="col-md-1">
</div>
</div>
where  in the attach file in panel i have put scroll in col-md-6 where in internet explorer its not working with keyboard keys..
Now in second col-md- 5
I have inserted bootstrap select box where in internet explorer and Mozilla Firefox scroll is not changing.
Now in  col-md-1 where im calling modal dialog box where my header and footer are fixed where double scroll is coming and also not working with keyboard keys.
[chirag.zip](https://github.com/Grsmto/simplebar/files/1206415/chirag.zip)
I'm expecting a solution with resolving issues in the file.
Also guide with latest js and css which i only need to use with the file.
A demo will be wonderful for me if you can make it.

**Comment by Grsmto** [comment]
Hi,
Sorry for the late reply, if you provide me an example using jsfiddle.net instead of what you sent (I wasn't able to test it).
Closing this as it doesn't seem to be a bug but more a usage problem.
