### ISSUE TITLE
Not working at all on Safari 10.1.2

### ISSUE THREAD

**Issue by atomless** [Grsmto/simplebar#104]
Simple bar does not appear to work at all on Safari 10.1.2 in OS X El Capitan. Working fine in Chrome and Firefox. Not Safari. Anyone have any clue what the issue is?

**Comment by Grsmto** [comment]
I'm surprised as El Capitan has only access to Safari 9.1. As far as I know Safari 10.1 was available on Sierra only.

**Comment by atomless** [comment]
My mistake the machine in question actually still has Yosemite! Version 10.10.5

**Comment by Grsmto** [comment]
Hi, sorry to bother you but can you try with the latest version again?

**Comment by Grsmto** [comment]
Latest version tested and seems to be working as expected. Closing.
