### ISSUE TITLE
No scrolling happening when scrolling on the .simplebar-track container

### ISSUE THREAD

**Issue by Tinoooo** [Grsmto/simplebar#105]
Hello,

when scrolling on the scrollbars track (.simplebar-track), the contents of the container don't scroll. When setting the z-index to a negative number, scrolling works. Do you see any problems in changing the z-index this way?

Thank you

**Comment by Grsmto** [comment]
Yeah you won't be able to drag the scrollbar with the mouse.
I didn't find a solution for this yet.

**Comment by Tinoooo** [comment]
I see. I didn't notice at first. Thank you for your help.
