### ISSUE TITLE
I cannot get rid of the internal browser scrollbar in IE 11

### ISSUE THREAD

**Issue by adrian-moisa** [Grsmto/simplebar#108]
I have been forced to move away from `perfect-scrollbar` and `ngx-perfect-scrollbar` due to severe performance problems when used together with angular 2 in IE11. I'm working on a big project and there are lots of components initialised at once. I had to do several, not pleasant, tricks in order to maintain page performance in the smooth and responsive zone (D3 charts are particulary sensitive to this). 

Anyway, I selected `simplebar` due to it's usage of the native scroll which has a significant benefit in solving those performance problems. However I still have one major issue. When I init an instance of the scrollbar I get both the simplebar and the browser native scrollbar at once. I managed to work around this issue using this snippet of CSS code:

    ::-webkit-scrollbar { /* for Mac OS X support */
        width: 0;
    }

However this does not work with internet explorer 11. I still see the scrollbar. This is a deal breaker for me. IE 11 is a must, the client uses it in the whole organisation. Maybe I'm doing something wrong. CSS styles seem just fine at first glance. If I disable `simplebar` I see no scrollbar at all.

**Comment by Grsmto** [comment]
Hi Adrian,
If it was only IE11 not working I would say there is a bug but as you had to hack around even for Chrome, I think there is an issue in your setup.
Maybe some CSS properties clash with Simplebar ones. Are you sure the CSS is applied properly? It's hard to help you without seeing the code! :(

**Comment by adrian-moisa** [comment]
I will try disabling some of the surrounding styles just to get a feeling where is the style generating this issue. It's difficult to provide a meaningful sample because I'm working on code that I cannot publish.

**Comment by Grsmto** [comment]
Hi @adrian-moisa if you want to try the new version, I think I fixed a bug related to this.
In the meanwhile I close this as this is probably the same issue as #110 .
