### ISSUE TITLE
"Latest release" : 2.4.0 on GitHub and 2.4.3 on npm...

### ISSUE THREAD

**Issue by Great-Fred** [Grsmto/simplebar#109]
Hello,

I have a problem to find the latest version.

I found 2 different "latest releases" :  2.4.0 on GitHub and 2.4.3 on npm...
Which release is the good one ?

Some remarks :
- On GitHub, the 2.4.3 is visible, but not tagged "latest" and has no "release note".
- The files in directory "dist" have an old version (2.4.1...).

Maybe everything is normal... :smile:

(and thank you for your plugin 👍 )

**Comment by Grsmto** [comment]
Hey, Thanks for this, I just tagged the 2.4.3 as the latest release.

> The files in directory "dist" have an old version (2.4.1...).
Couldn't check this, seems like the version is 2.4.3 on the dist files is right! Anyway should be fine now!

**Comment by Great-Fred** [comment]
Thanks for the answer :smile:
