### ISSUE TITLE
Simple Bar does not work on IE11

### ISSUE THREAD

**Issue by nagin** [Grsmto/simplebar#110]
I am first time using SimpleBar. I have simple html to test and understand SimpleBar.  This test html work on Chrome, FF , Edge  but not on IE11. I am attaching here sample html file I used for testing
[test.zip](https://github.com/Grsmto/simplebar/files/1324293/test.zip)

**Comment by Grsmto** [comment]
Hey, I'm aware of this and I'll land a fix this afternoon. Thanks!

**Comment by Grsmto** [comment]
Hey,
I just released a new version that should hopefully solve the IE11 issue, can you try now? 2.4.4.

**Comment by Great-Fred** [comment]
For me, this version works no more in my IE (Edge or 11, I don't really know...).

But, with the previous version, I had another problem with IE 10 (in emulation mode...)

**Comment by Grsmto** [comment]
Just tested on Browserstack IE11 seems to work fine. Do you have a jsfiddle where you can show it breaking? Or any error in the console?

**Comment by anibalrd** [comment]
I'm having the same problem, 2.4.3 works in IE 11 but 2.4.4 is not longer working.
The error in the console says "Array.prototype.toString: 'this' is null or undefined", I'm using webpack and it seems the error is thrown in the require function call.

**Comment by Great-Fred** [comment]
Excuse me for the delay.

In my IE, I have this error in the console :

> SCRIPT5007: Unable to get property 'contains' of undefined or null reference
File: simplebar.js, Line: 11, Column: 3243

It seems to be in the function "initDOM"...

**Comment by Grsmto** [comment]
Hey guys, can you test this jsfiddle and confirm the error for you? https://jsfiddle.net/Grsmto/57obe5w2/1/
I'm testing on Browserstack IE11/windows 10 and it works just fine so I'm a bit confused :/

**Comment by anibalrd** [comment]
This jsfiddle is also working in my IE 11. Not the same problem as in my application.

**Comment by Grsmto** [comment]
@Great-Fred your error seems to come from `classList` that is not supported by your browser. I believe IE11 does support it so it's probably unrelated to this issue. 
Simplebar polyfill is setup to "2 latest versions" so I believe you're testing in IE9 or compatibility mode and so you don't have `classList`.
You'll have to polyfill `classList` yourself (it's written in the doc).
@anibalrd I'll need more context as your error doesn't say much. I'll try a setup in a Webpack environment and see if I can replicate the issue. Can you confirm it's only on IE11? Thanks.

**Comment by Great-Fred** [comment]
@Grsmto Your jsfiddle works in my IE.
So there is maybe another problem.
I'm not in IE9 compatibility, but my browser seems to be IE11 with functionalities of Edge (in the compatibility list, there is "Edge (default)", "IE10", "IE9"... and in the menu "about Internet Explorer", I find "IE11").
It may be an Enterprise IE.

For `classList `, I use "`Modernizr.classlist`" to verify if it's present or not, before using `simplebar`. This way, IE9 uses "normal bars" in my "scrolled element"...

And if it was just a "`classList` problem", why would I have a problem with this version but none with the previous version ?

Maybe it's a problem with my "scrolled element"... But why with this version but not with the previous ?

**Comment by Grsmto** [comment]
Because between this version and the previous one, the polyfilling logic changed. So it's possible that something related to polyfills broke in between.

**Comment by Great-Fred** [comment]
@Grsmto : Is it possible to have a version of each not minified in ECMAScript 5.1?
Because IE11 is not compatible with ECMAScript 6 ...

I would like to see which are the elements used at the incriminated line in both version.
I'm not sure they're the same.

In the last version, I know it's a SVG element, thanks to the breakpoint on the error.
But, I don't know for the previous version, because I don't know where to put my breakpoint in the minified code...

**Comment by Grsmto** [comment]
@Great-Fred you can remove the Uglify JS plugin in the Webpack config and run `npm run build` again: https://github.com/Grsmto/simplebar/blob/master/webpack.config.js#L56
You should get a non-minified version.
Thanks for your help!

**Comment by Great-Fred** [comment]
In fact, I'm not using npm and I don't know how use it :sweat_smile: .
But I will try...

**Comment by Grsmto** [comment]
Hey no worries, I did it for you: https://pastebin.com/20rG6HR2

**Comment by Great-Fred** [comment]
Thank you...

Can I abuse your help and ask you the same thing for the previous version :sweat_smile: ?

**Comment by Great-Fred** [comment]
@Grsmto : I tried to build `simplebar` V2.4.3 in IntelliJ with Node and npm installed.
The "`node modules`" are loaded but, I'm not good enough to correctly configure my environment.
`npm run build` doesn't want to know anything... 😭 :cry:

**Comment by Great-Fred** [comment]
Hello @Grsmto .

I tried to "build my own version 2.4.3" but it seems that I don't get the same thing as you if I keep the Uglify JS plugin...
Maybe my modules are not in the good version...

**Comment by Grsmto** [comment]
Hi, here is the 2.4.3 unminified https://pastebin.com/F2HAh6Wg

**Comment by Great-Fred** [comment]
Thank you.

But, it's very strange because this non-minified version 2.4.3 does not work for a different reason than for the non-minified version 2.4.4, while the minified version in the release 2.4.3 works.

**Comment by Great-Fred** [comment]
@Grsmto :
The problem was that in IE11, the SVG Element has no `classList` and the only child in my "scrolled div" is a SVG Element.
So, in your code, when you "`make sure this element doesn't have the elements yet`" (your comment 😉) with those elements, you check a `classList` that does not exist in the child element...

I resolved my problem by inserting  in my "scrolled div" a new "`div`", containing my SVG Element, just before using `Simplebar`...
And I use the version 2.4.4 (but I don't know why I have the other issue with the previous version non-minified)...

Thank you for the time you spend for me 😃 👍 .

**Comment by Grsmto** [comment]
Good catch! Thanks for helping to identify this bug I'll have a look how to fix that!

**Comment by Great-Fred** [comment]
No problem 👍.
Good luck for the future 😄.
