### ISSUE TITLE
When .simplebar-track has margin-right or -left, scrollbar stops partway

### ISSUE THREAD

**Issue by narnigrin** [Grsmto/simplebar#113]
Hey, thanks for a really neat and simple-to-use plugin!

I've got a requirement from a client that the horizontal scrollbar for a certain element cover only part of the element's full width, so I've given .simplebar-track a left and right margin of about 23% in my CSS. Now .simplebar-scrollbar won't go all the way to the right (although I can see all the contents of the scrolled element, so it's just the position of .simplebar-scrollbar that's affected). 

This is what it looks like dragged as far as possible to the right: 
![example](https://user-images.githubusercontent.com/9936836/30956035-0e786ab4-a436-11e7-9211-f4343cd2120e.png)

Removing both margins removes the issue. Setting just one of the left and right margins to a percent or pixel value triggers it.

I'm init:ing the scrollbar using the data attribute, if that makes a difference.

What gives? I'm happy to hack my copy if you don't think built-in support for this use case is merited, but I'm not quite comfortable enough with vanilla js to be sure I won't break something.

**Comment by narnigrin** [comment]
The same thing happens when setting `left` and `right` for .simplebar-track instead of margins, by the way.

**Comment by Grsmto** [comment]
I see the bug but I don't think I'll have time to fix it anytime soon so you should probably try to figure out a workaround :/
Maybe you can simulate the track width offset with a css property like box-shadow or something, instead of actually changing the element dimension.

**Comment by narnigrin** [comment]
All right, thanks anyway for the quick answer!

**Comment by Grsmto** [comment]
Let me know if you find a solution or if you think it's a bug and can be fixed! 
Can be useful for users that want to achieve the same thing ;)
