### ISSUE TITLE
SimpleBar doesn't play nicely with Flexbox

### ISSUE THREAD

**Issue by RBrNx** [Grsmto/simplebar#114]
Thanks for the nice plugin! I've been using it for a short time but I just recently tried to use it on a Flexbox container and it all went wrong!

Here is a JSFiddle of the problem: https://jsfiddle.net/y6fj691y/2/
I have a Flexbox layout very similar to this. If SimpleBar is initialised on the container element then all the squares are pushed into a Single Column and do not obey the Flexbox parameters. The SimpleBar scrollbars will appear but will not actually scroll when used.

If you comment out the `align-items: flex-start` then this seems to fix the scrolling problem, but the squares are all still in a Single Column. 

In the JSFiddle you can also still see the Browsers Scrollbar, this doesn't seem to happen in my own project so I am unsure what's going on there either.

**Comment by Grsmto** [comment]
Hi,
Simplebar can't really do anything about this as it's not aware of the CSS properties that you apply to your elements around.
I fixed this for you there: https://jsfiddle.net/Grsmto/y6fj691y/3/

What I did is that I use another wrapper div that Simplebar will attach to, so it doesn't break your design :)

I should probably write something in the doc about this, I often have issues related to that!

**Comment by nathanwaters** [comment]
I had a lot of issues trying to get a vertical+horizontal centered flexbox to work within Simplebar. Best workaround hack was to use a table-cell: https://jsfiddle.net/3poqmuzn/1/
