### ISSUE TITLE
How to disable fade-in animation when the pointer hovers between two columns with scrolls

### ISSUE THREAD

**Issue by adrian-moisa** [Grsmto/simplebar#116]
I'm building a basic [code editor](https://github.com/visual-space/visual-school/tree/master/%40code-editor) and I have been using simplebar to enable fancy scrolls in three regions of the app. One is the code output, the other is the source code powered with ace code editor and last one is the sidebar. 

Whenever I move the pointer between these three regions simplebar triggers fade in animations (adds .visible class). I find them really distracting from the main objective of the app (learning programming). I would like to disable the fade in animation whenever I hover the scrolling area. I would like to enable the fade in only for hovering the scroll track or by scrolling with the mouse wheel. Is there any init option to control this?

Another thing that is distracting is that simplebar draws a full height scroll even if the content doesn't overflow out of the scrolling region. I would rather have it not showing up at all in this case. Any solution for this?

Thanks!

**Comment by adrian-moisa** [comment]
Eventually, after reading the code I figured that something like this can be done:

        sb = new SimpleBar(targetEl)
        sb.el.removeEventListener('mouseenter', sb.el.onMouseEnter)

**Comment by Grsmto** [comment]
Hi Adrian, that seems like an interesting project!
To hide the scrollbar, I see only quite complex solutions...You can make it appear when hovering on the track fairly easily with CSS but to make it appear on scroll, you will have for example to subscribe to the scroll event and add an extra class to the element.
That could work!
I don't have time to give you an example now but maybe you can figure out.

About the other problem, that's not normal. Scrollbar shouldn't appear if they are not needed. So there should be a CSS property clashing somewhere :/

**Comment by adrian-moisa** [comment]
Eventually, after reading the code, I figured this would work:

        sb = new SimpleBar(target)
        target.removeEventListener('mouseenter', sb.onMouseEnter)

**Comment by Grsmto** [comment]
That solution seems much better than mine ;)
