### ISSUE TITLE
Move scrollbar outside div

### ISSUE THREAD

**Issue by jamesrpublications** [Grsmto/simplebar#117]
Hello, I'm just trying to figure out how to move the scroll bar outside the div that actually scrolls. It appears to be hidden when using positioning to try move it outside.

**Comment by Grsmto** [comment]
We could get rid of the `overflow: hidden` that hides the scrollbar but as this is not a behaviour that is supported by the native scrollbar, I'm not sure this is a good idea anyway.
What were you trying to achieve visually? I'm sure there should be another way that doesn't involve changes in the script.

**Comment by jamesrpublications** [comment]
I basically just wanted to position the scrollbar outside a div as not to obscure its content. Here is a simple MS Paint sketch illustrating what I'd like to accomplish: http://i66.tinypic.com/33kdw13.jpg

**Comment by aidanholm** [comment]
I managed to move the (vertical) scrollbar out of the div by patching the library: https://github.com/crawl/crawl/commit/45387a99ae0a2459499e6178fde2f4d967179fbe is applied on top of the pre-built unminified file from unpkg, version 3.0.0-beta5. The margin/padding offset used to hide the native scrollbar is shifted by a fixed value, with some corresponding rules in CSS. I used 20px here, but you could use whatever value you want. Hope this helps someone!

**Comment by Grsmto** [comment]
Hey @aidanholm as you worked on this, do you see any easy way to get this implemented in Simplebar? 
Also that would be great to have a screenshot or something to see what you guys are actually trying to achieve (in a real UI life situation).

Thanks!

**Comment by Grsmto** [comment]
I think it should be possible now with the latest version since nothing is wrapped in `overflow: hidden` anymore.

**Comment by aidanholm** [comment]
@Grsmto Apologies for never getting back to you :( I had completely forgotten about this issue.
