### ISSUE TITLE
recalculate after dynamically loaded content (ajax)

### ISSUE THREAD

**Issue by daizumi** [Grsmto/simplebar#119]
Hi there,

First off, compliments on the plugin! I love the concept.

I can't figure out how to recalculate a SimpleBar element on the callback of my ajax call.
According to [this](https://github.com/Grsmto/simplebar#notifying-the-plugin-of-content-changes), I should have to create a new SimpleBar element and then call `recalculate()` on it. But what if I have already created the SimpleBar element by using the data-simplebar attribute, am I supposed to create it again? Or stop using the data attribute approach? Also, I have several scrollable containers in my site, so how do I know what simplebar element to recalculate? Is there a way to access the SimpleBar object from my element?

Say I have:

    <div data-simplebar></div>

And I just have one in the entire page, for the sake of the example.

Can i do something like:

    $('[data-simplebar]').SimpleBar.recalculate();

?

**Comment by Grsmto** [comment]
Hi Daizumi,
As said in the doc you shouldn't have to call `recalculate` at all as in theory we have some observers in place that should take care of that automatically when your content change. If it doesn't, there might be a problem in the setup (or with the plugin).
I guess your ajax call is simply adding some content to the scrollable element? This scenario should be already handled in theory, as you can on the demos: http://grsmto.github.io/simplebar/demos/

If it doesn't work, you can call `recalculate` manually just like you found. The code you pasted should works fine!

**Comment by daizumi** [comment]
Hi @Grsmto, thanks for the prompt reply! Yes, indeed it does it automatically (which is great).

I found the problem: I was replacing the scrollbar elements that SimpleBar had added to my container at the time of injecting the ajax-loaded content. I fixed it by adding `.simplebar-content` at the end of the target element, that my ajax would load content directly into SimpleBar's own container.

Still there's a small problem: the scrollbar is invisible after ajax happens. The container does scroll, but the scrollbar is invisible. It appears after I click anywhere in the container. Odd.

**Comment by Grsmto** [comment]
@daizumi did you fix your problem?
If you can replicate the issue you're mentioning, maybe you can create a jsfiddle and open a new ticket!
Thanks!

**Comment by daizumi** [comment]
No, the problem persists.
I'll try to replicate the issue in a jsfiddle when I have time.
Thanks!

**Comment by Shashank-Bhatt1** [comment]
Hi Is there any solution if entire wrapper where simplebar is attached rerenders from somewhere?
