### ISSUE TITLE
Version without jQuery?

### ISSUE THREAD

**Issue by Aedaeum** [Grsmto/simplebar#12]
Is it possible to port this to vanilla JavaScript without the jQuery dependency?

Thanks in advance.

**Comment by Grsmto** [comment]
Simplebar v2 is now jQuery-free.
https://github.com/Grsmto/simplebar/tree/v2

**Comment by Aedaeum** [comment]
Excellent, thank you. This was (now is) the best scrollbar script in my opinion.
