### ISSUE TITLE
configurable scroll hide timeout

### ISSUE THREAD

**Issue by abdulkareemnalband** [Grsmto/simplebar#122]
Currently hide timeout is hard coded to one second
Can we have configurable timeout

**Comment by Grsmto** [comment]
That makes sense. Also this could be defined in CSS with some transition delays instead of in the JS. Would be easier to customise.

**Comment by abdulkareemnalband** [comment]
CSS looks nice 
But actually I just copied your code into my app converted into typescript (my project is in typescript) and added timeout using data attribute

**Comment by Grsmto** [comment]
Closed in simplebar@3.0.0-beta.0.

**Comment by chojnicki** [comment]
Any info how to use it? I cannot find this in docs, any delay in css or js. Where it is and how to change it?

**Comment by Grsmto** [comment]
Hi @chojnicki you're right it's missing in the doc I believe.
The option is simply `timeout` and it takes milliseconds.
ex:  `new SimpleBar(document.getElementById('myElement'), { timeout: 500 });`

**Comment by chojnicki** [comment]
@Grsmto Thanks for updating docs ;)
