### ISSUE TITLE
How to import and use simplebar in angular 4 project?

### ISSUE THREAD

**Issue by costea93** [Grsmto/simplebar#123]
i added the dependency of simplebar in my vendor file, also i added 
`declare const SimpleBar: any;` 
in my component and in constructor: 
`new SimpleBar(document.querySelector('.scroll-content'), { autoHide: true });`
and i got the error: SimpleBar is not defined.

**Comment by Grsmto** [comment]
You probably need to import SimpleBar in your module. Like `import 'SimpleBar';` should be enough.
