### ISSUE TITLE
Loving this scrollbar, just wish there was a scrollbarMaxSize option

### ISSUE THREAD

**Issue by noir1899** [Grsmto/simplebar#125]
Please mark this as an enhancement request and not a bug report. I was looking for custom scrollbar script that would be unobtrusive and lightweight, and this one is perfect. I have no complaints.

I do think having a "scrollbarMaxSize" option would be a worthwhile inclusion, to complement the "scrollbarMinSize" option that already exists.

It might be subjective, but having a tall thumb (the moveable part of the scrollbar) on a short page element can look kind of silly in some instances. In my case the scrollbar thumb is almost the full height of the element. I realize this is probably how most modern touch devices would display their scroll indicators as well, but it's one aspect of this script that I wanted to customize, and was unable to do so via CSS.

To clarify: I can set the max-height of the scrollbar element to achieve the desired result visually, but functionally, once I scroll this bar down by half a centimeter it reaches the bottom of its track, rather than scrolling to the bottom of the element as normal.

Just thought I'd make the suggestion. If you don't think it's worth including, I understand.

Thanks again for making this plugin.

PS: One last thing to add. I was also confused at first by the double-scrollbar issue others have experienced. I guess I thought because the documentation states that it hides the native scrollbar, I should have "overflow:auto;" in my CSS. It might be good to include a brief explanation somewhere in the doc that this is, in fact, the incorrect way to use simplebar. At least it would help future numbskulls like myself! :)

**Comment by Grsmto** [comment]
Hi @noir1899 sorry for the late reply and thanks very much for your suggestions.
I think this may fit in the script if this is simple to implement, I'll look into it.
