### ISSUE TITLE
IE : "Object doesn't support property or method 'assign'". OK with FF and Chrome

### ISSUE THREAD

**Issue by Great-Fred** [Grsmto/simplebar#126]
Hello,

Everything is in the title ^^' 😄.

I use version v2.5.0...

Is there a solution ?

Thanks by advance.

**Comment by Grsmto** [comment]
Hi @Great-Fred as you'll be happy to see in [this commit](https://github.com/Grsmto/simplebar/commit/322ef343059d39bfdacec598ea9b563d5ad54661) that this bug has been fixed in the latest version 2.5.1.

**Comment by Great-Fred** [comment]
OK, thanks 😄 .
And sorry for the inconvenience...
I did not see if there was a new commit ^^'.

I test and I'll let you know...

**Comment by Great-Fred** [comment]
My test is ok with the new version.

Thanks 😃
