### ISSUE TITLE
recalculate debounce leading vs trailing

### ISSUE THREAD

**Issue by mnzaki** [Grsmto/simplebar#128]
I'm using simplebar with AngularJS. I need to call `recalculate` after a certain angular scope event (after which I'm fairly certain the scroll content is ready and in the DOM). The issue is that `recalculate` is debounced with `{ leading: true, trailing: false }`, so when I call it the call is simply discarded (as various other things trigger `recalculate`).I even tried timing out for more than the debounce timeout (currently 100ms) and for some reason this is not working as intended.

I found myself having to manually invoke the original `recalculate` like so:
```
simplebarInstance.__proto__.recalculate.apply(simplebarInstance);
```
to force a recalculate at the exact point at which I know it should work.

I'm not sure about the rationale behind choosing that `recalculate` fire *only* on the leading edge. Can it be configured with `{ leading: true, trailing: true }` instead?

**Comment by Grsmto** [comment]
Hi @mnzaki , I guess it's hard to replicate this issue in an isolated scope as it's quite specific to your use case.
I don't think calling recalculate on trailing debounce could be an issue so I could probably get that in!
Thanks for this report, I'm glad you found a workaround for your problem. I'll see if I can implement this.

**Comment by neo** [comment]
I was able to reproduce and submitted a PR (#141)
just found this issue now :D

**Comment by neo** [comment]
is there a new version published after solving this?

**Comment by Grsmto** [comment]
Not yet! I'm still working on a few additions before releasing one.

**Comment by neo** [comment]
Good to know, thanks!

**Comment by neo** [comment]
it would be very much appreciated if you could publish a patch release soon. :D
