### ISSUE TITLE
[New option] Don't hide scrollbar if there is no content to scroll

### ISSUE THREAD

**Issue by soanvig** [Grsmto/simplebar#129]
Currently, if the content doesn't require scrolling, the **simplebar** is hidden.

It would be nice, if there is an option to disable this behaviour and have scrollbar always enabled.
For now it works if `.simplebar-scrollbar` has `visibility: visible !important`.

About scroll dragger element: it gets min-height height in that state by default, so nothing to do here.

**Comment by luncht1me** [comment]
I'm currently fighting with the OPPOSITE of this....
My scrollbar is showing when my content isn't overflowing, and it looks terrible. It's just this little tiny circle of a scroller in the top of the content.

**Comment by Grsmto** [comment]
I think that's something we could support. This is supported by the default browser scrollbars via `overflow: scroll` so that would make sense.
I'll look into it.

**Comment by Grsmto** [comment]
Closed in simplebar@3.0.0-beta.0.
