### ISSUE TITLE
marginBottom clipping

### ISSUE THREAD

**Issue by jrschifa** [Grsmto/simplebar#133]
Just curious if anyone has run into an issue where the content gets clipped at the bottom due to this line. https://github.com/Grsmto/simplebar/blob/master/src/simplebar.js#L151 If offsetSize is use, all seems well.

**Comment by Grsmto** [comment]
Hey! If this happen to you there is probably a style clash between yours and Simplebar styles. Make sure to apply any style to a separate div or remove any styles that could potentially break layout calculations.
