### ISSUE TITLE
2 px offset top

### ISSUE THREAD

**Issue by TylerOlthuizen** [Grsmto/simplebar#134]
How can I get the 2px offset top off?

**Comment by neo** [comment]
any solution or workaround?
I feel like it's this line: https://github.com/Grsmto/simplebar/blob/master/src/simplebar.js#L354

**Comment by Grsmto** [comment]
It's true that the plugin should be agnostic to the design of the scrollbar and that line actually arbitrary apply a specific style. Until I patch this, I think a workaround could be to use the pseudo elements :before and :after to achieve this.
Try something like: 
```
.simplebar-scrollbar:before, .simplebar-scrollbar:after {
  content: '';
  position: absolute;
  display: block;
  width: 100%;
  height: 2px;
  background: red; // whatever the style of your bar is
}

.simplebar-scrollbar:before {
  top: -2px;
}

.simplebar-scrollbar:before {
  bottom: -2px;
}
```

**Comment by neo** [comment]
🎉
