### ISSUE TITLE
Native bar and simplebar show together on Chrome for Linux

### ISSUE THREAD

**Issue by amouratoglou** [Grsmto/simplebar#136]
HI Guys, I have this issue where both bars are together.

I have added to my CSS ```

.simplebar-scroll-content { 
    box-sizing: content-box !important;

}
```

but problem still persists... any hints?

**Comment by Grsmto** [comment]
Hi,
Unfortunately I can't test on Linux because it's not supported by Browserstack and I'm on mac.
Is it happening on http://grsmto.github.io/simplebar/ as well?

**Comment by amouratoglou** [comment]
Nope. it is working fine there... strange... I will keep looking and update. must be something in my code.
