### ISSUE TITLE
bower  ENOTFOUND Package simplebar not found

### ISSUE THREAD

**Issue by aquitania99** [Grsmto/simplebar#137]
Doing a deploy today I encountered this error!
**bower simplebar#^2.5.1                       ENOTFOUND Package simplebar not found**

And now even if I run it locally it fails, can't find the package.
Is there something going on?

Thanks in advance for your help.

Best Regards,

Sergio.

**Comment by Grsmto** [comment]
Hey,
Hmm it seems like it's due to #135. I removed the package from Bower because I thought it wasn't even working from there as it's a very old version of Simplebar hosted there!
I will try to add it back to Bower asap!

**Comment by aquitania99** [comment]
Thanks a lot you're a legend! I'll look into switching to npm too.
