### ISSUE TITLE
archive project / search for maintainers

### ISSUE THREAD

**Issue by DanielRuf** [Grsmto/simplebar#138]
It seems there are open issues.

Currently there are way too many custom scrollbar solutions on GitHub and no real collaboration between projects and everyone reinvents the same. Would be great to see a few great solutions instead of many with not enough support by the community.

**Comment by Grsmto** [comment]
Thanks for your insight Daniel.
As you can see on top of the README of this project, I  recommend to use https://github.com/utatti/perfect-scrollbar which is the most popular library and has very few issues.  

However it seems like Simplebar is still helping some people. Also it exists since 2013 so if there are too many on Github it's probably not my fault (especially as you can see there isn't any pull requests on this repo as oppose to what you say).
I'm open to maintainers and to merging this project to another if authors of other libraries are up for it (that's something I tried without success a long time ago).

**Comment by DanielRuf** [comment]
> I'm open to maintainers and to merging this project to another if authors of other libraries are up for it

That would be good. So far the 

> Also it exists since 2013 so if there are too many on Github it's probably not my fault (especially as you can see there isn't any pull requests on this repo as oppose to what you say).

You are right. Sorry I've used a text which fit for all repos but 2 not.
Generally it makes sense to bundle the knowhow and take a look at the features (feature comparison tables), different implementations and solutions and try to bring other solutions like perfect-scrollbar forward together but perfect-scrollbar should generally move to an org account to increase the truck factor, improve team collaboration and manage this better using teams with different rights.

**Comment by Grsmto** [comment]
> feature comparison tables
This would be really useful and I'll try to take the time to do this. That would help me to check again the different solutions on the "market" as well and see how Simplebar positions itself in 2018 and potentially do a move.

**Comment by DanielRuf** [comment]
Let me know if you need any help and I will try to invest some time to help with this.

**Comment by broodjekipburger** [comment]
I recently chose simplebar above alternatives like perfect-scrollbar because most of them are using non-passive event listener (scroll-block) which has a negative performance impact.
I hope this helps when setting up a feature comparison table.

**Comment by DanielRuf** [comment]
> because most of them are using non-passive event listener (scroll-block) which has a negative performance impact.

This should be easy to fix. Probably with a new option to optin using passive event listeners or use them by default.

**Comment by broodjekipburger** [comment]
> This should be easy to fix. Probably with a new option to optin using passive event listeners or use them by default.

You would say so but for example perfect-scrollbar won't implement... https://github.com/utatti/perfect-scrollbar/issues/560

**Comment by DanielRuf** [comment]
> won't implement

It's just because it is not so easy but it would be still possible imo. So it should be possible in general.

**Comment by neo** [comment]
This is a very simple solution, and I agree that it has the potential.
Also I just opened a PR #141

**Comment by DanielRuf** [comment]
How is this related to the issue here and what does your PR solve @neo?

**Comment by neo** [comment]
I was commenting that this project is a very nice solution and I think it has potential to become a community project.

The PR is just a side note saying that I'd like to contribute

**Comment by DanielRuf** [comment]
Ah ok. That was not quite clear.

**Comment by neo** [comment]
glad you understood now :D

**Comment by DanielRuf** [comment]
open / closed issue / PR ratio makes more sense than just the number of open ones, and also mumber of contributors.
