### ISSUE TITLE
rtl text direction support

### ISSUE THREAD

**Issue by broodjekipburger** [Grsmto/simplebar#139]
Is it possible to enable text direction support?
The library works perfectly since it relies on the browsers native scrollbars so the only issue here is in the CSS, which means based on the text direction (which can be detected by doing for example `getComputedStyle( document.getElementsByClassName( "simplebar-content" )[0] ).direction;`) padding-right with padding-left (https://github.com/Grsmto/simplebar/blob/322ef343059d39bfdacec598ea9b563d5ad54661/src/simplebar.js#L150) and margin-right with margin-left (https://github.com/Grsmto/simplebar/blob/322ef343059d39bfdacec598ea9b563d5ad54661/src/simplebar.js#L155) on init.

**Comment by Grsmto** [comment]
Hi @broodjekipburger
I think it's tricky to detect this automatically as the direction css property could potentially be applied higher in the DOM and cascading so Simplebar could miss it right?
Maybe having an option in the plugin to define the direction would then be a better solution?

**Comment by broodjekipburger** [comment]
Thanks!!

**Comment by mrg0lden** [comment]
simplebar-track is still on the right side on RTL mode even though we get `padding-left`
