### ISSUE TITLE
Documentation of " data-simplebar-autohide='false' "

### ISSUE THREAD

**Issue by jusoakley** [Grsmto/simplebar#140]
I was looking to turn off the autohide feature in an app that uses Shopify, which is not great at importing JS files. After hours of working with the documented method of declaring options with JS but with no results, I noticed this bit of HTML in the demo:

`<div class="demo3" data-simplebar data-simplebar-autohide="false">`

I added the autohide portion of this and it solved my problems immediately and seems to be working reliably. However, this solution is not documented in the README under options. I think this should definitely be documented.

**Comment by Grsmto** [comment]
Hi,
I'm glad you found a solution for this. If the JS way wasn't working it means there is probably a bug!
You are right we should document this!
I'll be working on a few issues at the end of the month and will definitely include that in! Thanks!

**Comment by jusoakley** [comment]
Sure thing! Now that I discovered that fix I'll definitely be using Simplebar in the future.

**Comment by PandaWood** [comment]
NB I couldn't get this to work until I took the advice of this issue - https://github.com/Grsmto/simplebar/issues/163
Where using `data-simplebar-auto-hide` does work and `data-simplebar-autohide` does not

**Comment by Kai7771** [comment]
Any idea on how I could change the color of the sidebar

**Comment by ebraho** [comment]
@Kai7771 
```
:global(.simplebar-scrollbar:before) {
  background-color: #dcdbe1;
}
```
