### ISSUE TITLE
Native Scrollbar shows on both Chrome and Firefox

### ISSUE THREAD

**Issue by CKMacLeod** [Grsmto/simplebar#143]
On Firefox (newest version, installed fresh today), the native scrollbar, or a version of it, even appears in a July 2017 demonstration Fiddle used on a previous thread:

https://jsfiddle.net/Grsmto/pctt4d6k/3/

I'm using the latest simplebar, downloaded yesterday from this repository. 

On Chrome, I was able to move out of an affected div with extra padding, but method doesn't work on Firefox.

Here are the un-styled initial versions. Very ugly:

![unstyled firefox](https://user-images.githubusercontent.com/6822649/36275984-4f844dce-1241-11e8-86b7-0e6057e2028b.JPG)

![unstyled chrome](https://user-images.githubusercontent.com/6822649/36275968-4755995a-1241-11e8-92b9-90763b599443.JPG)

**Comment by marko-hologram** [comment]
What OS ? I've opened that fiddle in Firefox 58, 59, 60 (Stable, Developer Edition, Nightly) and I tried it in Chrome 64 ...All on Windows 10. I don't see the native scrollbar, just simplebar the way it should be.

**Comment by CKMacLeod** [comment]
Windows 10 installed a few days ago, Chrome Version 64.0.3282.167 (Official Build) (64-bit)

The fiddle looks like this on Chrome. 

![simplebar](https://user-images.githubusercontent.com/6822649/36316369-f99c8ada-12ee-11e8-8c2e-614bb26fc784.JPG)

Is the native scrollbar at far right is supposed to be there? - I thought it was absent on an earlier look. This morning they look the same on both Firefox and Chrome, but, fiddling aside, when I wrote the question I was more concerned about the display issues in the "real world" contexts depicted.

**Comment by marko-hologram** [comment]
As far as that far right scrollbar in the fiddle goes it's supposed to be there sometimes, depeding on resolution since that's the JSFiddle window right there, no simplebar used. For me it looks like this in the picture below, no native sidebar (unless I resize my browser) at far right, but simplebar is in this div containing text. For me everything renders properly when I use simplebar, maybe some other CSS is clashing in your "real world" example.

![image](https://user-images.githubusercontent.com/22904204/36345655-b519aedc-142f-11e8-84f3-937db5676ca1.png)

**Comment by CKMacLeod** [comment]
I guess it's always possible that there was some CSS or other conflict. Unfortunately, the question and the examples I gave were connected to a time-limited project that's now done. I didn't see any CSS that should have affected either sidebar (or could affect the native sidebar on Firefox). I had to install an alternative scrollbar modified that worked fine out of the box, and I'm not in a position to go back and open up the site to experiment again. I guess you might have to wait to see if others discover similar problems, presuming you're confident it's working well for people.

**Comment by Grsmto** [comment]
@CKMacLeod the native scrollbar you are referring to in your screenshot is related to the `max-height: 400px` that is applied in the CSS. This has nothing to do with Simplebar, this is just the scroll from JSFiddle.
I'm glad you found a solution with another plugin.
