### ISSUE TITLE
this.observations_.forEach is not a function

### ISSUE THREAD

**Issue by broodjekipburger** [Grsmto/simplebar#144]
I got this Javascript error: `this.observations_.forEach is not a function`

Browser: `Firefox 19 on Ubuntu (Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:19.0) Gecko/20100101 Firefox/19.0)`
File / line: `/ajax/libs/simplebar/2.5.1/simplebar.min.js 1 : 28897`

Trace:
```
O.prototype.gatherActive@/ajax/libs/simplebar/2.5.1/simplebar.min.js:1
v.prototype.updateObservers_/t<@/ajax/libs/simplebar/2.5.1/simplebar.min.js:1
v.prototype.updateObservers_@/ajax/libs/simplebar/2.5.1/simplebar.min.js:1
v.prototype.refresh@/ajax/libs/simplebar/2.5.1/simplebar.min.js:1
n@/ajax/libs/simplebar/2.5.1/simplebar.min.js:1
l</<@/ajax/libs/simplebar/2.5.1/simplebar.min.js:1
b@https://cdn.trackjs.com/releases/current/tracker.js:5
```

Can this be fixed?

**Comment by Grsmto** [comment]
I don't think so. We are now at Firefox 58 and Firefox 19 has been released in 2013. So unfortunately I won't change any code to support this, it will be your responsibility to handle any potential polyfill for that.
As a hint, this seems to be the `forEach` function that is probably not supported by Firefox 19, so if you add a polyfill for this function, it may work.

**Comment by broodjekipburger** [comment]
Thanks for checking!
(Note: it seems forEach, as part of ECMAScript 5, should be supported by older Firefox versions https://caniuse.com/#search=forEach)
