### ISSUE TITLE
Not working if parent element has set css property display

### ISSUE THREAD

**Issue by netoper** [Grsmto/simplebar#145]
When the parent element is set as display: block; (or any other exclude flex;) scrollbar not working. Scroll bar is show, but mousewheel is unresponsive. Why?
[https://jsfiddle.net/cgdLvb0p/8/](https://jsfiddle.net/cgdLvb0p/8/)

**Comment by Grsmto** [comment]
Hi,
This is the same issue as #142 #133 #114 and others.
You shouldn't override Simplebar styles otherwise it breaks the plugin.

I'll add a section about this in the doc! Thanks!
