### ISSUE TITLE
Is this possible to update or destroy, regenerate scrollbar

### ISSUE THREAD

**Issue by betagoo** [Grsmto/simplebar#148]
Is this possible to update or destroy, regenerate scrollbar?

**Comment by Grsmto** [comment]
You can trigger a [manual update as stated in the doc](https://github.com/Grsmto/simplebar#notifying-the-plugin-of-content-changes) but if you have to that's probably a sign for a bug.
There is an undocumented function `unMount` that you can use as well if necessary.

What's your use case?
