### ISSUE TITLE
Recalculate not working

### ISSUE THREAD

**Issue by DanielBielczyk** [Grsmto/simplebar#151]
Hi @Grsmto,
I think there's a bug related to debouncing recalculate().
I have accordion with jQuery slideUp/Down animation inside element with SimpleBar. When some long section that should cause SimpleBar to show is opened, SimpleBar stays hidden. Instead it appears, when the section is closed. I tried to add recalculate() to slide's onComplete callback, but it doesn't helped. I had to wrap recalculate() with setTimeout longer than 100 ms, than it worked as expected.

**Comment by Grsmto** [comment]
Hi thanks for your report. I think this issue has been fixed in #141 .
I should release a version with this fix very soon!

**Comment by Grsmto** [comment]
Hi,
If you can try with the latest version. https://github.com/Grsmto/simplebar/releases/tag/v2.6.0
I'm closing for now!

**Comment by DanielBielczyk** [comment]
Hi, sory for the late response...
It's working, but there's another bug - when the scrollbar should hide, only the track does, handle is still visible. It's due to visibility: visible set on it. Strange, but according to specs - https://jakearchibald.com/2014/visible-undoes-hidden/

**Comment by Grsmto** [comment]
Did you update the css as well when you updated the plugin?

**Comment by DanielBielczyk** [comment]
Well, I didn't, but it's not the problem, visibility is set dirrectly on the scrollbar elements.

![obrazek](https://user-images.githubusercontent.com/37437037/38495463-f8138d42-3bf9-11e8-8607-290969bb88a4.png)

**Comment by DanielBielczyk** [comment]
I have some custom styling, but I updated the styles and removed my adjustments and the bug is still there.

**Comment by Grsmto** [comment]
Ok thanks for the report I saw the bug with the with the `forceVisible` option enabled. Can you confirm you have this option on?

**Comment by DanielBielczyk** [comment]
Nope, only option I have set is autoHide: false.

**Comment by armhov** [comment]
Hi @Grsmto , i 'm using simplebar lib, and in consoe, i have get this cond of error, 
 Uncaught TypeError: Cannot read property 'recalculate' of undefined . 
Simplebar.js versions - trywith latest and with 2.6.0 versions, same error for two versions.
![screenshot from 2018-11-13 14-04-38](https://user-images.githubusercontent.com/33937449/48410288-3c9aa300-e74f-11e8-983f-8e56e75dd8ec.png)
![screenshot from 2018-11-13 14-14-06](https://user-images.githubusercontent.com/33937449/48410290-3d333980-e74f-11e8-87c6-093b9e598e57.png)
Can you help me ot give some recomendations ? 
Thanks !
