### ISSUE TITLE
Wrong version on cdnjs for v2.6.0

### ISSUE THREAD

**Issue by broodjekipburger** [Grsmto/simplebar#152]
For example see https://cdnjs.cloudflare.com/ajax/libs/simplebar/2.6.0/simplebar.js which is still v2.5.1, should be v2.6.0 and have the same contents as https://unpkg.com/simplebar@2.6.0/dist/simplebar.js

Can you fix this please? Thanks

**Comment by Grsmto** [comment]
I'm not using cdnjs and I had no idea SimpleBar was hosted there. The project is already using cdn.jsdelivr.net and unpkg as you noticed.
How am I suppose to fix this? Do you have any idea why this is happening?

**Comment by broodjekipburger** [comment]
CDNJS host files related on git tag and it seems it's still on v2.5.1 for tag v2.6.0, please see https://github.com/Grsmto/simplebar/tree/v2.6.0/dist i.e. https://github.com/Grsmto/simplebar/blob/v2.6.0/dist/simplebar.js

**Comment by Grsmto** [comment]
This is really surprising. Other services are relying on npm as far as I know and not on the actual repo.
I'll look into this, thanks.
