### ISSUE TITLE
Both horizontal and vertical scrollbar visible in rtl mode

### ISSUE THREAD

**Issue by broodjekipburger** [Grsmto/simplebar#153]
When in vertical mode, "simplebar-track horizontal" should be set to "visibility: hidden;".
It currently sets "left: 0px; width: 25px;" instead, thus making it visible in rtl.
I didn't have this problem in ltr mode.
Can you look into this issue please, thank you

**Comment by Grsmto** [comment]
Hi @broodjekipburger thanks for you report. I'm not sure I'm able to reproduce this issue. The RTL mode seems to work fine for me.
Could you give more details or better, provide a jsfiddle with the issue happening? You can use this one as a base: https://jsfiddle.net/Grsmto/57obe5w2/1/

**Comment by broodjekipburger** [comment]
Please see the issue, including my fix for it commented in the CSS, here: https://jsfiddle.net/57obe5w2/24/
Thank you

**Comment by Grsmto** [comment]
Awesome, thank you for the fix! I'll look into implementing this.
I will re-open the issue to not forget!
