### ISSUE TITLE
Using max-height does not work in IE11

### ISSUE THREAD

**Issue by jacksonv1lle** [Grsmto/simplebar#154]
This is a really great scrollbar. It satisfies all my needs except when I try to use max-height on IE11. I don't want to specify a height on my scrollable panels because I need them to collapse when there is no content. Is there any way for this to work?

**Comment by Grsmto** [comment]
Hi @jacksonv1lle , I think I experienced this issue as well. Could you let me know if applying this css solves the issue?
```
.simplebar-scroll-content {
    max-height: inherit!important;
}
```

Thanks for your report!

**Comment by jacksonv1lle** [comment]
@Grsmto Thank you sir. That has worked

**Comment by Grsmto** [comment]
I will implement this fix in the plugin for the next version! Thanks!
