### ISSUE TITLE
Scrollbar itself doesn't scroll on mobile devices (touch)

### ISSUE THREAD

**Issue by WHI-CH** [Grsmto/simplebar#156]
Is there a way to get the scrollbar itself to scroll on touch devices? We made it wider, but touch itself apparently doesn't do anything on the scrollbar. Tested on the latest Android Chrome and iOS Safari.

**Comment by WHI-CH** [comment]
Including this script after simplebar adds the touch events to the corresponding mouse events:
https://github.com/createlogic/map-touch-events-to-mouse-handlers

**Comment by Grsmto** [comment]
Hi,
This is intentional. The native behaviour on most mobile browsers is like this. It doesn't usually let the user drag the scrollbar, so SimpleBar is just following native behaviour.
I think the solution you provided is the right thing to do if you want to support this!
I'll close for now, feel free to comment your thoughts.

**Comment by WHI-CH** [comment]
True. You could add this as an option maybe? Like _scrollbarTouchEvents:true/false_ with default false?
We're using simplebar because we needed to add a wider scrollbar (18px) to a container for easier scrolling on the mobile version of a site.

**Comment by bryanbuchs** [comment]
CSS to hide the scroll track & thumb for touch devices:

```
  @media (hover: none) and (pointer: coarse) {
    .simplebar-track {
      display: none;
    }
  }
```

**Comment by shaunw** [comment]
Alo would like simplebar scrollbar to work on touchscreens.

How would you use [map-touch-events-to-mouse-handlers](https://github.com/createlogic/map-touch-events-to-mouse-handlers) with simplebar to get touch working on the scrollbar with touch devices?

**Comment by shaunw** [comment]
> Including this script after simplebar adds the touch events to the corresponding mouse events: https://github.com/createlogic/map-touch-events-to-mouse-handlers

Also would like simplebar scrollbar to work on touchscreens.

How would you use [map-touch-events-to-mouse-handlers](https://github.com/createlogic/map-touch-events-to-mouse-handlers) with simplebar to get touch working on the scrollbar with touch devices?
