### ISSUE TITLE
More scrolling events

### ISSUE THREAD

**Issue by apopelyshev** [Grsmto/simplebar#158]
Hey. I've already opened an issue recently, so - the plugin is great, thousand thanks to author - it goes without saying. However, during the development of my project I got needed to control the scrollbar reaching top/bottom of the track. Again, in **README** is mentioned another nice plugin - **Perfect scrollbar**, which provides users with many different events including, for example, **ps-x(or y)-reach-start(or end)**. It would be awesome, if **Simple Bar** had those too.

But for now I have to accomplish it like this:
`scroll.getScrollElement().addEventListener('scroll', function() {
if ($(this).scrollTop() == 0) <--here goes part for true-->
else <--and here for false-->});`
(and that's just for top, I haven't yet figured out a way for bottom)

**Comment by Grsmto** [comment]
I don't want to include that in the library code as this is not a native event. The goal of the library is to keep is as **Simple®** as possible so keep the codebase small.
However I would be happy to include some examples pages or a wiki page explaining how to do that.
I don't have time at the moment to work on this as I'm on some more important issues but feel free to send your findings here and I will see to include that in a wiki page/example!
