### ISSUE TITLE
Broken on Firefox + Linux

### ISSUE THREAD

**Issue by johanson** [Grsmto/simplebar#16]
width - widthMinusScrollbars returns always 0. For some reason `$('div', tempEl).innerWidth();` returns the width including the scrollbar(s).

Will try to investigate further, looks like it's working fine on Windows.

Xubuntu + Firefox 41.0.2

**Comment by johanson** [comment]
Well, for some reason the element has to be at least 56px high. Otherwise Firefox doesn't even add scrollbar to it, which makes the widthMinusScrollbars always 0 and simplebar think the browsers has floating scrollbars.

`tempEl  = $('<div class="scrollbar-width-tester" style="width:51px;height:56px;...` will fix the issue.

**Comment by Grsmto** [comment]
Hey!

Crazy! Thank you very much this! Sadly I can't test cause Browserstack doesn't support linux and I don't have a linux platform available.
But I guess your fix shouldn't impact on anything else so I can implement it!

**Comment by johanson** [comment]
You're welcome. 

It really is a strange bug. I'm surprised it only affects Firefox on Linux. Who knows, maybe only Ubuntu based distros. While Linux desktop is not the most popular web-browsing platform, I believe Firefox is the most popular browser on it.

I doubt it will break anything. You can try testingbot.com. They have Linux platform, you get 100 free minutes when you sign up, and overall it's cheaper than than Browserstack :)

**Comment by rolandhegedus** [comment]
The issue with the scrollbar still up on xubuntu with FF.
Its fix the issue:
`var testerDiv = $('<div style="width: 100px; height:100px; overflow: scroll; position: absolute; top: -9999px"/>');`
`$('body').append(scrollDiv);`
`testerDiv = testerDiv.get(0);`
`return testerDiv.offsetWidth + testerDiv.clientWidth;`

**Comment by rolandhegedus** [comment]
Its working better:
`var testerDiv = $('<div style="width: 100px; height:100px; overflow: scroll; position: absolute; top: -9999px"/>');`
`        $('body').append(testerDiv);`
`        testerDiv = testerDiv.get(0);`
`        return testerDiv.offsetWidth - testerDiv.clientWidth;`

**Comment by johanson** [comment]
@rolandhegedus Yes, I guess you can put some safer, bigger values as long as they are off the screen to make sure the scrollbars are actually rendered.
