### ISSUE TITLE
non-minified js version

### ISSUE THREAD

**Issue by staabm** [Grsmto/simplebar#161]
it would be great when the release downloads would contain a non-minified js version of the lib, so error reporting/bug reporting can be easier. this would also ease contribution and bug analysis.

the src/simplebar.js can not be loaded in a browser as is (tested on chrome 67.0.3387.0).
it requires a build step etc. which renders contribution harder..

when I instead use the minified js file to report problems, the issue is not that meaningful.

**Comment by Grsmto** [comment]
There is the sourcemap there https://github.com/Grsmto/simplebar/blob/master/dist/simplebar.js.map
I thought that would be enough for debugging. However It doesn't seem like you're using it.

I'm currently on a full rewrite of the plugin so I'll look into generating a non-minified version that should be simple enough.

**Comment by Grsmto** [comment]
Added in 15bbbb6b4b461d39d995bbc44decd3ea7ab1708d

**Comment by ppazos** [comment]
In newer releases I can't find the minified version, would be good to release both I guess.

**Comment by andersk** [comment]
@ppazos The minified version is still at [`dist/simplebar.min.js`](https://unpkg.com/browse/simplebar@5.0.7/dist/simplebar.min.js) where it’s always been.

**Comment by ppazos** [comment]
@andersk that is not on the project when you download from the releases section or clone it. And couldn't find that link on the documentation. Where is it?

**Comment by andersk** [comment]
@ppazos GitHub release downloads are generally just an archive of the source code used to build the release. The release itself lives on NPM like other JS packages. unpkg is one of many ways to see the contents of NPM. Documentation: https://github.com/Grsmto/simplebar/blob/master/packages/simplebar/README.md#installation
