### ISSUE TITLE
autohide: false doesn't work

### ISSUE THREAD

**Issue by hyperknot** [Grsmto/simplebar#163]
autohide: false doesn't have any effect. It is actually the same on the official examples as well.

**Comment by hyperknot** [comment]
Tested in macOS + Chrome, Win10 + Chrome, Win10 + IE11.

**Comment by Grsmto** [comment]
Can you show your setup? It seems to be working fine for example on this https://jsfiddle.net/57obe5w2/45/

Thanks

**Comment by hyperknot** [comment]
The ones on this page disappear:
http://grsmto.github.io/simplebar/demos/

**Comment by Macuyiko** [comment]
Using `data-simplebar-auto-hide` instead of `data-simplebar-autohide` worked for me.

**Comment by hyperknot** [comment]
OK, I'm actually using JS, similar to @Grsmto's snippet, I just thought that the bug might be the same in the official page as the one I'm experiencing.

**Comment by Grsmto** [comment]
The page you linked to is outdated. Where did you find the link out of curiosity? (I need to remove this).
There is a bug in the latest version with the `forceVisible` option enabled, so maybe that's where it comes from.

**Comment by hyperknot** [comment]
The big "Demos" button at the bottom of the official page :-)
http://grsmto.github.io/simplebar/

**Comment by Grsmto** [comment]
Closing. (see #164 for follow up)
