### ISSUE TITLE
autoHide:false hides the scrollbar till mousewheel event fires

### ISSUE THREAD

**Issue by Avessalom1** [Grsmto/simplebar#17]
I'm using the scrollbar on div element, i want the scrollbar to be always visible. So i set autoHide:false.  However the scrollbar is not visible till i scroll using the mousewheel.

**Comment by Grsmto** [comment]
Hey,
Can you tell me which device/browser you're testing? I can't reproduce this issue.
Thanks.

**Comment by Avessalom1** [comment]
windows, chrome

**Comment by Avessalom1** [comment]
Found the issue. I'm using the plugin inside angular application. The list i'm calling scrollbar for is loaded dynamically, so resizeScrollbar method is not triggered after that.

**Comment by Grsmto** [comment]
Did you fix the issue?
If so, is it related to Simplebar or Angular?
Thanks
