### ISSUE TITLE
Scroll by mouse doesn't work when add data-simplebar dynamic

### ISSUE THREAD

**Issue by ko22009** [Grsmto/simplebar#171]

**Comment by Grsmto** [comment]
Can you detail a bit? This doesn't mean much to me.

**Comment by ko22009** [comment]
If you have react or vue app, when dom virtual, your element loading dynamic, bcz event doesn't work. Try create dynamic attr to some elem dynamic.

**Comment by Grsmto** [comment]
There is now a [React wrapper for SimpleBar](https://github.com/Grsmto/simplebar/releases/tag/simplebar-react%400.0.1-beta.0). 
We don't have yet a Vue one but that should be easy enough to do yourself by taking example on the React one!
That should hopefully fix your issue.

**Comment by jpfernandezl** [comment]
This is a Vue.js wrapper:
https://gist.github.com/jpfernandezl/2dbf7cab593dec87eb080d6c1ae274ae
