### ISSUE TITLE
Scrollbar lingers when it should be hidden.

### ISSUE THREAD

**Issue by dmetal23** [Grsmto/simplebar#173]
There is a fundamental problem where if you are resizing a specific container and the scrollbar should be hidden, it actually just stays and is rather persistent. I would take a look at perfect-scrollbar and see how they hide the scrollbar once a resize occurs and it is no longer necessary.

**Comment by rayleigh3** [comment]
@dmetal23 I agree with you. I noticed that issue. This happens when you set the scrollbar to opacity: 1. the scrollbar track is hidden, but the scrollbar stays there.

**Comment by AndiZ23** [comment]
@dmetal23 @rayleigh3 
You can write your own javascript code to toggle the visibility if the scrollbar is not necessary there, something like:
```javascript
function resetScrollbar(scrollbar){
    var containerHeight = scrollbar.el.clientHeight,
          contentHeight = scrollbar.getContentElement().scrollHeight;
    if (containerHeight > contentHeight)
          scrollbar.trackY.style.display = "none"; // or scrollbar.hideScrollbar();
    else
          scrollbar.trackY.style.display = "block" // or scrollbar.showScrollbar();
}
```
