### ISSUE TITLE
Please, remove polifyls

### ISSUE THREAD

**Issue by ex3ndr** [Grsmto/simplebar#175]
It makes problematic to import and compile SSR-enabled apps with this library because of this.

Thanks!

**Comment by Grsmto** [comment]
Hi,
Thanks for you report, do you know exactly what polyfills are causing you issues? Or do you have more details about this?

**Comment by Grsmto** [comment]
I think this should be fixed with the new version. I tested with a Next.js setup and should be working fine with SSR!
