### ISSUE TITLE
Need height 100% in simplebar-scroll-content and simplebar-content

### ISSUE THREAD

**Issue by ThiPereira** [Grsmto/simplebar#177]
Hi!
All my container are using height 100%. So I did 2 modifications in the CSS:

.scroll-com-percent .simplebar-scroll-content {
height: 100%;
}

.scroll-com-percent .simplebar-content {
height: 100%;
}

The scroll stop working. It still is in screen but do not scrolls...

Any ideia?

**Comment by Grsmto** [comment]
I think this is the same issue as #185 so I'll close for now.
This situation is not currently supported by the plugin, sorry :(
