### ISSUE TITLE
Support for click on track

### ISSUE THREAD

**Issue by Grsmto** [Grsmto/simplebar#178]
I started an implementation of this but didn't finish because I'm not sure that's something people absolutely want for SimpleBar.
If you need this feature, please add a 👍 or comment below!
Remember that the goal of SimpleBar is to be as lightweight as possible. There is already plenty of plugins that support more features like this one.

Also it would probably be a good idea to copy the native implementation of [Webkit](https://github.com/WebKit/webkit/) instead of inventing something myself, but I wasn't able to find the code for it.

We need to keep in mind that it would be tricky to implement this especially on mobile because we usually don't want this on tap but in click (mouse...) only.

**Comment by strarsis** [comment]
@Grsmto: Yes! Also because users expect this.

**Comment by Grsmto** [comment]
Released! 🎉
