### ISSUE TITLE
SimpleBar demo renders differently on IE11 and Mac OS Firefox

### ISSUE THREAD

**Issue by petermikitsh** [Grsmto/simplebar#181]
The first screenshot is Windows 8, IE 11.0.9600.17416 (VM). Second is Mac OS 10.13.5 Firefox 61.0.1 (64-bit). The scrollbars look similar, except for their color. Is this intentional? I'm assessing using this library, but I'd want the same color scrollbar in all supported browsers.

Windows 8, IE 11:
<img width="1680" alt="screen shot 2018-07-19 at 12 28 25 pm" src="https://user-images.githubusercontent.com/1571918/42965558-3ec97f68-8b4f-11e8-8935-257faf866bfc.png">

Mac OS 10.13, Firefox 61:
<img width="1680" alt="screen shot 2018-07-19 at 12 24 33 pm" src="https://user-images.githubusercontent.com/1571918/42965607-568984a4-8b4f-11e8-9b41-b801860d21af.png">

**Comment by Grsmto** [comment]
I'm not seeing this at all on Mac OS 10.13, Firefox 61 :/
Not sure what's happening, are you testing on an actual mac or on a VM?

**Comment by petermikitsh** [comment]
Thank you for the quick response! The IE11 is a VM on the Mac.

I opened up Firefox on an actual Mac, not in a VM.

**Comment by petermikitsh** [comment]
Also, on Firefox 61 on Mac OS 10.13, if I hover over the scrollbar, it looks like this... you get a lighter background. I wasn't observing that effect in IE11.

<img width="1680" alt="screen shot 2018-07-19 at 12 42 58 pm" src="https://user-images.githubusercontent.com/1571918/42966254-6912258e-8b51-11e8-9670-fc2c6913ae60.png">

**Comment by Grsmto** [comment]
Hey,
Website was using an old version of the plugin. Should be fixed now thanks!
