### ISSUE TITLE
Reserved words in ES5 causes YUI-Compressor exceptions

### ISSUE THREAD

**Issue by Apke** [Grsmto/simplebar#182]
Hi,

i got a special problem with the YUI Compressor which i must provide for a project.

The compressor have problems with reserved words in method names like _delete_.

I solved that issues with a small plugin (babel-plugin-yui-compressor-fix-reserved-keywords)[https://www.npmjs.com/package/babel-plugin-yui-compressor-fix-reserved-keywords]

which only transform 

```javascript
// external
anonymous.prototype.delete = function() { ... }

// transformed to
anonymous.prototype["delete"] = function() { ... }
```

it should also be done by (@babel/plugin-transform-reserved-words)[https://www.npmjs.com/package/@babel/plugin-transform-reserved-words] which i tried to add it into _.babelrc_ at my fork, but i was not able to build it successfully.

i would appreciate if you could include a babel plugin for that case.

thanks and best regards

Apke

**Comment by Grsmto** [comment]
I'm not sure about adding a babel plugin globally for what seems to be a very edge case.
I believe you should be able to transpile yourself SimpleBar using this babel plugin and some custom configuration directly in your own project so I'll close this.
Thanks!
