### ISSUE TITLE
Elements inside simplebar can't have height: 100%

### ISSUE THREAD

**Issue by RennerBink** [Grsmto/simplebar#185]
Hi, currently it's not possible to set `height: 100%` on a element. It simply won't grow to the desired size.
If I compare it with a native-scroll-container its working though.

Here's a fiddle: http://jsfiddle.net/gvne6xk5/2/
The red container is the simplebar-scroll container and the blue one is the native-scroll container.
Notice the size difference of the `h2` elements.

**Comment by Grsmto** [comment]
Thanks for your report.
I think you are right, there is no way of doing this in pure css. That seems like a limitation of how the plugin works. I don't see any solution to that in pure css :/

I will improve the [caveats section](https://github.com/Grsmto/simplebar#5-caveats) with this.

**Comment by RennerBink** [comment]
That's very unfortunate...
I've tested other scrollbar plugins and the in the caveats section mentioned OverlayScrollbars plugin does support this behavior: http://jsfiddle.net/gvne6xk5/7/

Maybe you can ask the maintainer how he's doing it, because I think this is a quite important thing.

**Comment by Grsmto** [comment]
This is fixed in latest beta version.
