### ISSUE TITLE
Avoiding default scrollbar

### ISSUE THREAD

**Issue by RinatValiullov** [Grsmto/simplebar#186]
How can I avoid this default scrollbar on inner second *article*?

[simplebar library](https://codepen.io/4rontender/pen/jpwwyg?editors=0010)

![sb](https://user-images.githubusercontent.com/9755333/43181528-1db22846-8ff7-11e8-9126-6be33936754e.png)

**Comment by diogocostajumia** [comment]
It seems that the padding that's being set to "hide" the native scrollbar is too short from what i saw on the code. I don't know if it's a problem on the script or not but it could be that you have something "styling" the simplebar container? I'm not sure.

**Comment by RinatValiullov** [comment]
ok, will think about it

**Comment by CodeSpatial** [comment]
It's the padding on the article element in your Pen. Apparently if you have any padding on the element where you want to apply the simplebar, it offsets the hiding estimates for the native scrollbar. Remove the padding and you should be good.

**Comment by cara-tm** [comment]
Exactly! Name your `div` in order to apply your desire padding and avoid ugly effects within the additional markup injected by the script:

`article .inner {padding: 2em}`

**Comment by RinatValiullov** [comment]
Really strange. I thought that can apply bar on the outer element. 

https://codepen.io/4rontender/pen/jpwwyg?editors=0110

**Comment by cara-tm** [comment]
Solved if you remove this rule:

    article div {
    /*
	padding: 1em;
    */
    }

See it in action here: https://codepen.io/cara-tm/pen/yqZqeo

**Comment by RinatValiullov** [comment]
@cara-tm Thanks! Now all works as I wanted
