### ISSUE TITLE
scrollbar visibility

### ISSUE THREAD

**Issue by rayleigh3** [Grsmto/simplebar#190]
Good Day, 

Nice Script. 

I found issue regarding when i set the scrollbar opacity: 1.  (always visible).

So when the content is long, the scrollbar shows, but when the content is short the scrollbar track is hidden, but the scrollbar stays there.  

Thanks.

**Comment by WebKieth** [comment]
Confirm.
@rayleigh3 I wrote a script for my case:
```javascript
var scrollfix = function(){
  var interval, isScrollersCreate, obsConf, observer, that;

  observer = new MutationObserver(function(mts) {
    return mts.forEach(function(mt) {
      var scroller, visibility;
      if (mt.type === 'attributes' && mt.attributeName === 'style') {
        visibility = mt.target.style.visibility;
        scroller = mt.target.querySelector(".simplebar-scrollbar");
        return scroller.style.visibility = visibility;
      }
    });
  });

  obsConf = {
    attributes: true,
    childList: true
  };

  isScrollersCreate = false;

  that = this;

  interval = setInterval(function() {
    var targets;
    if (!isScrollersCreate) {
      targets = document.querySelectorAll(".simplebar-track");
      if (targets && targets.length) {
        targets.forEach(function(target) {
          return observer.observe(target, obsConf);
        });
        return isScrollersCreate = true;
      }
    } else {
      return clearInterval(interval);
    }
  }, 10);
}
```

**Comment by semiaddict** [comment]
I'm having a similar issue (tested in Chrome and FireFox): when the content is changed and no scrollbar is required anymore, it stays visible. However, the scrollbar's length is correctly resized if the scrollbar is needed.

From a first look, it seems that the simplebar-track gets a visibility of "hidden", but the simplebar-scrollbar still has visibility set to "visible", preventing it from inheriting the value of the simplebar-track.

@Grsmto, the autoHide option doesn't fix this issue, it just "automatically hides the scrollbar if the user is not scrolling".

So far I've managed to fix this with the following CSS:
```
.simplebar-scrollbar{
     visibility: inherit !important;
}
```
I'll try and take a closer look into the code soon and hopefully get back with a pull request.

**Comment by semiaddict** [comment]
This issue seems to be resolved in SimpleBar v3 (pre-release), so I'm just switching to that one.
