### ISSUE TITLE
Scroll table content Tbody without Thead ?

### ISSUE THREAD

**Issue by miranos** [Grsmto/simplebar#194]
Hi,

Is there a way to scroll only TBODY tag and let THEAD fixed always at the top ?

I tried but the result give nothing.

Any way to do it please ?

By the way thank you for this awesome work !

**Comment by Grsmto** [comment]
That should now work with the latest version I think. Try using `position: sticky` on your `<thead>`.

**Comment by akvaliya** [comment]
@miranos Can you share how did you apply this scroll to table? Documentation says table is not supported with this scroll. it'll be great if you can provide some little code.

**Comment by ybaldus** [comment]
@akvaliya https://jsfiddle.net/1z76Lhvo/12/
@Grsmto is it possible to add an example to the documentation?
