### ISSUE TITLE
Horizontal scroll bar doesn't work in Chrome or Edge

### ISSUE THREAD

**Issue by JDGHHou** [Grsmto/simplebar#195]
Cannot even drag bar to the right. Went into the CSS and increased the thickness of the horizontal scrollbar, but it is not able to detect that I am trying to click and drag on the element no matter where I click on it.

**Comment by Xapuu** [comment]
I think its related to #178

**Comment by Grsmto** [comment]
Hi guys I guess you talk about the new beta version. I fixed this issue already and will be releasing a new version really soon. 
Thanks

**Comment by Grsmto** [comment]
I'm closing in favour of #129
