### ISSUE TITLE
Scroll by pressing the arrow

### ISSUE THREAD

**Issue by ArtemPavliienko** [Grsmto/simplebar#198]
Hello. 

I have a list and I can select an item with the up and down arrows. But the scroll does not work. How do I make the scroll work?

there is a method el.recalculate(), but I did not understand how to work with him.

**Comment by Grsmto** [comment]
Hi @ArtemPavliienko 
SimpleBar shouldn't have any impact on this as far as I know. For example if you go on http://grsmto.github.io/simplebar/ give the focus on the scroll element and use the keyboard arrows, it should work properly.
So I think your issue comes from something else!

**Comment by ArtemPavliienko** [comment]
$(".simplebar-scroll-content").scrollTop( ..number.. ) and everything works :)

**Comment by Grsmto** [comment]
Hey, understood your issue now. For anyone falling into this, this is documented on the README [here](https://github.com/Grsmto/simplebar#trigger-programmatical-scrolling). Better use that instead of triggering the div manually.
