### ISSUE TITLE
osx captain

### ISSUE THREAD

**Issue by vAhyThe** [Grsmto/simplebar#20]
Simplebar wont show(even in dom) on all browsers in ios x(latest chrome/safari/firefox). No problem show in console. simplebar yust add `overflow:auto` and thats all. When i look on browserstack  (windows) works fine. Thaks for help.

**Comment by vahy** [comment]
in iosx lion it works

**Comment by Grsmto** [comment]
This seems to be the "normal" behavior. Read this section of the readme: https://github.com/Grsmto/simplebar#6-browsers-support

Can you confirm?

We could have an option to force the use of Simplebar in every cases.

**Comment by vahy** [comment]
I tested on desktop (MacBook‎ Pro). It will be awesome if simplebar work  on every desktop.  Maybe some problem with recognize what mobile or desktop ??

**Comment by Grsmto** [comment]
I'm closing the issue as this is not a bug but a decision made to disable Simplebar when a "floating" scrollbar is already present (mobile or mac OSX).
I will think of an option to force Simplebar to appear even when there is a floating scrollbar.

**Comment by caisah** [comment]
Hi, Is there anything done about OSX? If not, is there an easy way I could change the code to enable it? TBH I didn't bother to debug. I'm asking because I guess you know the code better :).

Thanks!

**Comment by Grsmto** [comment]
What exactly is the feature you mean by "enable it"?
Cause I work on OSX (El Capitan) and I built this project testing/working on it on OSX so if you can explain I can probably work on it :)
Is it what I described above? "force Simplebar to appear even when there is a floating scrollbar"?

Thanks!

**Comment by caisah** [comment]
Yep. On OSX the custom scrollbar won't show up at all. I would like to enable it.

**Comment by Grsmto** [comment]
Ok I got it! I will have some time soon to work on the project but it won't be before 2 weeks at least.
It's definitely a good option to implement.

**Comment by caisah** [comment]
Thanks a lot!

**Comment by kimko3000** [comment]
First, Thanks for your awesome code!

So, I have an issue probably related to this thread. I'm working on OS X El Capitan, and the simplebar works mostly fine..
**but** only when I have my settings in *System Preferences > General > Show scroll bars* on **'Always'** and
**not** when it's on **'Automatically based on mouse or trackpad'** which I thought is the default setting.

Is there a way to fix this or is it not a bug and it's designed to work like that? Or is it me not understanding the relations?

Thanks!

**Comment by Grsmto** [comment]
@kimko3000 yes, the plugin automatically disable itself when it detects a "floating" scrollbar.
This is explained in the doc there: https://github.com/Grsmto/simplebar#6-browsers-support

I understand the confusion and for the V2 I will implement an option to force Simplebar to be enabled. I will also update the description of the plugin cause it's pretty confusing.

**Comment by kimko3000** [comment]
@Grsmto thanks for your answer. i guess i didn't read that careful enough nor understood the concept of floating scrollbars.

so i'll try v2 then. 👍

**Comment by rohmanhm** [comment]
I got same problem, Is the feature has been already in v2 beta?

**Comment by Grsmto** [comment]
It's been added 2 days ago on this commit 4574c0b
but no release yet. I'll edit a release supporting this feature asap, just need to test it before!

**Comment by rohmanhm** [comment]
thanks, it's ready in v3 beta. I tested and work perfectly on both of Windows and Mac Chrome browser.
