### ISSUE TITLE
TypeError: e is undefined

### ISSUE THREAD

**Issue by JLE91** [Grsmto/simplebar#200]
Hi,

i am using your script and i'm really happy with it. Thanks for your good job.
Unfortunately i'm receiving a JavaScript Error because of it.
I'm using it along some other Scripts and compress all of them in one single large .js File, but that doens't seem to be the problem. 
At first i was using v 2.5.1 and after updating to v 2.6.1, the error is still there.
I'm not sure, why and how it appears, maybe you still know what causes the problem.
I unminified the js file to locate, where the error comes from:
**TypeError: e is undefined**
```
 E.prototype.onTransitionEnd_ = function(t) {
            var e = t.propertyName;
            y.some(function(t) {
                return !!~e.indexOf(t)
            }) && this.refresh()
        }
```
Thanks

**Comment by Grsmto** [comment]
I believe this piece of code doesn't come from SimpleBar!
Hope you found a solution since that!
