### ISSUE TITLE
Optimise performances for multiple instances in a page

### ISSUE THREAD

**Issue by Grsmto** [Grsmto/simplebar#205]
Multiple instances of the plugin could share some infos like the native scrollbar width so they don't need to calculate this individually.
Basically setting some data as static within the SimpleBar class.

**Comment by adjourn** [comment]
Good idea, accessing `offsetWidth` (which you have to do when measuring scrollbar width) triggers styles recalculation and it basically doubles the initialization time (if already have DOM ready, don't know what are the ratios if have to build DOM too). All other calculations and adding listeners are almost nothing next to it.

**Comment by Grsmto** [comment]
Done in #373
