### ISSUE TITLE
Problem with horizontal scrolling and dynamic scrolling content

### ISSUE THREAD

**Issue by exteon** [Grsmto/simplebar#207]
I have an "infinite" scroller (I add content to the content-container when scroll position gets below container-size threshold). I am trying to combine it with your scroller. Results:

- On vertical scroller, it works decently, although it shows a certain lag in redrawing following the content update; any way to improve on that?
- On horizontal scroller: here it behaves weirdly; as I scroll right, content is added, the cursor should skip left; but it does the opposite, it skips right like mad.

**Comment by adjourn** [comment]
@Grsmto How about having throttles in options? Then we don't have to worry about _most scenarios._

**Comment by Grsmto** [comment]
I'm closing this for now.
If by any chance you have some time to provide a jsfiddle with an infinite scroll implementation, that would be really helpful if you still get issues with the latest version.
