### ISSUE TITLE
Capture all mouse events while dragging?

### ISSUE THREAD

**Issue by exteon** [Grsmto/simplebar#208]
I found this to be quite common among the other scrollers I tested: while mouse-scrolling, all mouse events are not captured, so I get hover events for elements I move the mouse over, and even click events if there are active elements under the scrollbar and I scroll so that I mouse-down and mouse-up over the same element. To be consistent with browser scrollbar behavior, all default actions on all mouse events should be prevented while scrolling.

**Comment by Grsmto** [comment]
This is live in latest version.
