### ISSUE TITLE
Window resize event handler should be debounced then removed in removeListeners 

### ISSUE THREAD

**Issue by davemoore24** [Grsmto/simplebar#209]
It looks like this may be an oversight, but the resize hanlders are never removed. It might also be nice to debounce this. 

![image](https://user-images.githubusercontent.com/6215968/45842712-19b9b880-bce3-11e8-8d16-453ef31db077.png)

**Comment by davemoore24** [comment]
The image above is simplebar in a modal that I was just opening and closing.

**Comment by Grsmto** [comment]
You're right. Forgot to remove that listener! Thanks!
