### ISSUE TITLE
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass

### ISSUE THREAD

**Issue by lightframes** [Grsmto/simplebar#210]
Hi,
when i compile my scss files with webconfig on Laravel, I have this warning

Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.

I import simplebar in my app.scss file with 
@import '~simplebar/dist/simplebar';
And it get the css file because there are no scss file. Could you please transform the css files in scss files, or maybe I'm doing something wrong with import?

**Comment by Grsmto** [comment]
According to [that issue](https://github.com/sass/node-sass/issues/2362) it's a "bug" from libsass. I think you can ignore this warning.
