### ISSUE TITLE
Can't have sticky elements

### ISSUE THREAD

**Issue by adjourn** [Grsmto/simplebar#213]
I've stumbled upon another limitation of this implementation besides `height: 100%`.  Can't have `position: sticky` elements. Please take a look at this example: https://jsfiddle.net/9eb13n2L/

Should it be caveat or should it be supported? If anyone finds a way to _magically_ make it work, Im all ears.

**Comment by Grsmto** [comment]
Hey, 
Thanks for your report.
You'll be happy to know that this will be supported in the new version of the plugin. I'm expecting an alpha release very soon.

**Comment by adjourn** [comment]
Thanks @Grsmto, this would have been a deal breaker for me. Too early to estimate date?

Little trivia: Twitch uses this for all their desktop scrollbars (as far as I can tell), that's how I found this.

**Comment by Grsmto** [comment]
It will be a big change on top of the current beta release so expect some bugs. But I want something to be testable next week.

**Comment by adjourn** [comment]
Are you planning to resolve all the issues in [Roadmap](https://github.com/Grsmto/simplebar/projects/1) before releasing `next` as new beta version?

**Comment by Grsmto** [comment]
This is released in latest beta version.

**Comment by adjourn** [comment]
Very cool! Updated example if anyone is interested: [https://jsfiddle.net/9eb13n2L/3/](https://jsfiddle.net/9eb13n2L/3/)

**Comment by jrgd** [comment]
@Grsmto the above demo by @adjourn seems broken; is this expected? 
I just discovered your (awesome) work and trying to catch up with current state and how to do the thing I want: I have a sticky element (header) inside a div on which I apply simplebar and it keeps on scrolling along the rest of the content—let me know if I should open a new issue…

**Comment by Grsmto** [comment]
@jrgd there is a working example on the examples page, first one on the top left: http://grsmto.github.io/simplebar/examples
