### ISSUE TITLE
Add all classnames to options?

### ISSUE THREAD

**Issue by adjourn** [Grsmto/simplebar#214]
What do you think about adding `visible`, `horizontal` and `vertical` classnames to options too? It's not a huge deal but it adds minor inconveniences when dealing with CSS libraries that hash classnames.

**Comment by Grsmto** [comment]
Could be.
Can you describe your use case and why you need to be able to change the default class names?
I was actually thinking of removing this feature entirely as I didn't really see the point.

**Comment by f4w-pwharton** [comment]
I'd also like to be able to change the other class names, particularly the 'visible' one.

We use Bootstrap 4 which includes 'visible' also, defined as:
```
.visible {
    visibility: visible !important;
}
```
This means that even though a `.simplebar-track` has `style="visibility: hidden;"` the `.simplebar-scrollbar`  inside has the visible class and so can be seen when it shouldn't.

An alternative fix for my case would be to just prefix all the classes you use with simplebar- like you have done for some of them.

**Comment by Grsmto** [comment]
I keep this open because I want to change the default `.visible` class as it's too generic.

**Comment by Grsmto** [comment]
Closing this for now as we had a PR solving this.
