### ISSUE TITLE
Dynamic update

### ISSUE THREAD

**Issue by bigboytr** [Grsmto/simplebar#215]
I have a div with some child elements. Scrollbar perfectly working. But when change child count dynamically, scrollbar not working correctly. I think it's need to rerendering or something like that. Is there any advice ?

**Comment by Grsmto** [comment]
Hi Yasin,
It should rerender automatically in theory so there might be a bug.
It would be very useful if you could provide me a JSFiddle showing this issue? Here is one to get you started https://jsfiddle.net/Grsmto/57obe5w2/1/

Thanks!

**Comment by bigboytr** [comment]
Hi Adrien,
Thanks for the fiddle. I changed that. I added 10 more rows dynamically. But it's not working as I expected. If you debug this fiddle on inspector, you will understand what I want to say. On the inspector, added new rows out side of the content box. So it not scrolling.

**Comment by valeriy-efimov** [comment]
+1
![image](https://user-images.githubusercontent.com/5989188/46734368-a2e95d00-cc9b-11e8-9196-edb17ca99c71.png)
`el.getContentElement();` not working, it does not add new elements inside "simplebar-content"

my try on vue
```
<div id="city_select_bar">
       <template v-for="region in all_regions_filter">
           <li class="region_optgroup">{{region.name}}</li>
          <template v-for="city in region.cities">
             <li  class="region_optgroup_children">{{city.name}}
                            </li>
              </template>

             </template>
      </div>

        mounted() {
...
                vm.simple_bar = new SimpleBar(document.getElementById('city_select_bar'), {autoHide: false});
...
        },

```

**Comment by bigboytr** [comment]
@valeriy-efimov thanks for the screenshot. This is point I mentioned.

**Comment by Grsmto** [comment]
We now have a new Vue wrapper! Please check it out!
