### ISSUE TITLE
Not scrolling in Firefox

### ISSUE THREAD

**Issue by netdjw** [Grsmto/simplebar#216]
Hi there!

I use this code:

```
<div data-simplebar>
    ...
</div>
```

in SCSS:

`@import '../../node_modules/simplebar/dist/simplebar.css';`

in JavaScript:

`import 'simplebar';`

It's working fine in Chrome.

But not scrolling in Firefox and Edge. The scrollbars showign, but not working.

Firefox 62.0 (64 bit)
Microsoft Edge 42.17134.1.0

Any idea or trick?

**Comment by Grsmto** [comment]
Please try again with latest version and submit a jsfiddle if you're still having this issue. Thanks!

**Comment by EmilMoe** [comment]
It's working in Safari, version 3, here. But it doesn't work in Firefox 63 either.
