### ISSUE TITLE
Remove again / Toggle

### ISSUE THREAD

**Issue by EmilMoe** [Grsmto/simplebar#217]
How can I toggle if it's enabled or just remove it?

**Comment by Grsmto** [comment]
Sorry I'm not sure to understand your question.
Do you want to destroy the plugin after initialisation? To restore it to before it was applied?
If yes, it's not currently supported (see #157) as I think it's not a very common scenario. In most scenarios the plugin should unmount by itself (but the DOM won't come back to how it was before!).

**Comment by EmilMoe** [comment]
Hi @Grsmto 

Sorry for the late reply. The problem is that, I'm using it in an editor where an option is to toggle scrollbars. Therefor It would be nice to enable and disable them to show the user instantly how the result looks.
