### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by Grsmto** [Grsmto/simplebar#221]
We receive a lot of issues that are related to the same problems:
- Simplebar doesn't work because user has applied extra styles to the host element that breaks the plugin
- User is using Simplebar in a modern framework (React, Vue, etc.) and Simplebar breaks/doesn't update properly

It would be great to: 
- Have an issue template that points the reporter to a troubleshooting section in the README or with common answers directly in the template.
- Invite reporter to provide a JSFiddle that shows the issue (insist on that, issues have 99% more chances to be resolved with that!)

**Comment by Grsmto** [comment]
Closed in #225 🎉

**Comment by superfunkminister** [comment]
Added in https://github.com/Grsmto/simplebar/pull/225
