### ISSUE TITLE
Apply hover effect on scrollbar

### ISSUE THREAD

**Issue by omzy83** [Grsmto/simplebar#229]
I have tried to apply a hover effect to the scroll bar but this does not work:

```
.simplebar-scrollbar::before:hover {
    background-color: red;
}
```

**Comment by Grsmto** [comment]
You're right I think since we support scroll on track and we have `pointer-events: none;` on the container, you can't use the `:hover` rule.
SimpleBar should add a class when scrollbar is being hovered but it's not currently being supported.

**Comment by Grsmto** [comment]
Released 🎉
