### ISSUE TITLE
Hidden content of webpage

### ISSUE THREAD

**Issue by andreacivita** [Grsmto/simplebar#23]
I've tried your tutorial (include jquery,add link to css and js file,add data-simplebar-direction="vertical") but the content with scrollbar is hidden. 
I've tried to put on body, or in a div or section, but never works. Developer console in chrome doesn't show errors.

**Comment by Grsmto** [comment]
Hey! 
If you can have a check to the examples and see if it can help you to make it work. I close the issue for now.
If you figured out this as being a bug coming from Simplebar, please re-open and give some more details about the bug.
