### ISSUE TITLE
After simplebar is attached scroll to a element

### ISSUE THREAD

**Issue by supys12** [Grsmto/simplebar#235]
I am using simplebar in react and trying to scroll to a particular element after my list gets rendered and simplebar is attached to it. but when i try to do that i am not finding any scroll bar element in my DOM.
Do you guys have any callback event which will be called once a simple bar is attached, or can you suggest any alternative way to resolve this.

**Comment by Grsmto** [comment]
Hey,
Are you using the `simplebar-react` package?

**Comment by supys12** [comment]
No only simplebar

**Comment by Grsmto** [comment]
My answer was to suggest using `simplebar-react` if you are using React. Otherwise the plugin won't work as expected in the scenario your describe. This should fix your issue!
