### ISSUE TITLE
Simplebar 3.1.0-beta.4 missing lodash.memoize dependency

### ISSUE THREAD

**Issue by SkylerLipthay** [Grsmto/simplebar#236]
I'm getting some errors when trying to `import 'simplebar';` on the latest version (`simplebar 3.1.0-beta.4`).

```
Module not found: Error: Can't resolve 'lodash.memoize' in '.../node_modules/simplebar/dist'
```

Running `npm install --save lodash.memoize` fixes the problem for me. I believe ` simplebar/packages/simplebar/package.json` should have an explicit `lodash.memoize` dependency listed. I see there has been some commit activity regarding Yarn lately, so I apologize if this is a redundant issue report or if it turns out there is something wrong with my environment. Please let me know if you can't replicate.

Thanks!

Node version: 10.0.0
NPM version: 6.0.0
Webpack version: 4.6.0

**Comment by Grsmto** [comment]
Thanks very much for the report. I will update and do a release asap.
