### ISSUE TITLE
is it possible to make simplebar only scroll the vertical overflow ?

### ISSUE THREAD

**Issue by mazentouati** [Grsmto/simplebar#237]
i only need scroll bar to handle the vertical overflow only of the specified div (the div i applied simplebar to).
for my case, i need to make the horizontal overflow visible because i need it to be wrapped by the specified div's parent which mean the horizontal scroll will include the specified div siblings.

i checked this reply https://github.com/Grsmto/simplebar/issues/84#issuecomment-304129980 but that's not what i need as it will clip the overflowed content.

i couldn't find any clue in the documentation how to disable the horizontal bar.

**Comment by Grsmto** [comment]
Hi Mazen,
This is not currently supported. The overflowed content will always be clipped.
Could you provide a screenshot or a jsfiddle of what you're trying to achieve? It would be useful for me to understand your use case and see if I could add this feature.

**Comment by Grsmto** [comment]
Also on the latest version of SimpleBar you should be able to set `overflow-y: hidden` and it should scroll only vertically (but the horizontal content will still be clipped).
