### ISSUE TITLE
scroll-content too wide in IE 11

### ISSUE THREAD

**Issue by yellowsix** [Grsmto/simplebar#24]
When I use this in IE 11, it seems that the scroll-content is too large by a scrollbar width in Internet Explorer 11. For example, I have html like this:

```
<div style="width:600px;">
  <div class="simplebar">
    ... stuff ...
  </div>
</div>
```

When simplebar does its thing, the simplebar-scroll-content element is set to 617px wide, and then the child simplebar-content div also ends up 617px wide (when it should only be 600px). Thus 17px of content get hidden on the right edge.

I compared this in other browsers (where it is working fine): in Chrome and Edge the simplebar-scroll-content and simplebar-content is 600px (they both flag as "webkit" and thus the explicit sizing code is skipped in simplebar). In Firefox, simplebar-scroll-content is 617px wide, but simplebar-content is 600px wide (browser must be reserving space for the scrollbar, so everything lines up).

It seems that IE behaves like the "webkit" browsers -- if I check for IE 11 and skip the resizeScrollContent method, then everything works fine. Seems only Firefox needs it (of latest-version browsers).

**Comment by FabriceGaudin** [comment]
I have the same problem with the height of scroll-content, only in IE11 as well.

**Comment by Grsmto** [comment]
Hey,
is it with the V1 or V2?

**Comment by FabriceGaudin** [comment]
@Grsmto in my case it's the v1.1.3

**Comment by Grsmto** [comment]
@FabriceGaudin maybe you could try the v2? https://github.com/Grsmto/simplebar/tree/v2
Thanks

**Comment by FabriceGaudin** [comment]
@Grsmto Hi, actually I don't have the problem with v2. Will v1 be corrected as well ?

**Comment by FabriceGaudin** [comment]
@Grsmto I can't use V2 because I need to support IE9, do you know if V1 will be corrected ?

**Comment by Grsmto** [comment]
@FabriceGaudin I will continue to support v1 by accepting pull requests but I won't actively develop/fix issue on it myself.
You should be able to use V2 on IE9, it just need a polyfill for `classList` (it shouldn't be more than a couple of lines of code...). Let me know if you have other other problems with IE9!
