### ISSUE TITLE
Simplebar v3 not on cdnjs

### ISSUE THREAD

**Issue by olafcm** [Grsmto/simplebar#241]
Latest version does not show up on cdnjs (https://cdnjs.com/libraries/simplebar), can you please fix this?
Thank you :-)
Also thanks for offering and maintaining this great plugin  👍

**Comment by adjourn** [comment]
Why are you not using [unpkg.com](https://unpkg.com/)? It can serve every package and version from `npm` and also uses CloudFront under the covers, so if you're worried about speed, it should remain exactly the same.

**Comment by adjourn** [comment]
Why are you not using [unpkg.com](https://unpkg.com/)? It can serve every package and version from `npm` and also uses CloudFlare under the covers, so if you're worried about speed, it should remain exactly the same.

**Comment by broodjekipburger** [comment]
Sure, that's a great alternative!
But in my case it saves me a dns lookup and handshake because I load all my libs from cdnjs :-)

**Comment by Grsmto** [comment]
Closed in https://github.com/cdnjs/cdnjs/pull/13150
