### ISSUE TITLE
simplebar-placeholder is increasing width infinitely in Mobile

### ISSUE THREAD

**Issue by ZerglingGo** [Grsmto/simplebar#242]
## Current Behavior
When I loading pages in Mobile environment(Same affected in responsive mode at Developer tools), .simplebar-placeholder width is increasing infinitely.

![2018-11-29_16-05-29](https://user-images.githubusercontent.com/3365053/49204876-a1f9bf80-f3f0-11e8-8b32-6451ec87dad1.gif)

## Reproducible example
I couldn't reproduce this behavior. 
Current simplebar layouts:
![chrome_2018-11-29_16-18-07](https://user-images.githubusercontent.com/3365053/49205468-6bbd3f80-f3f2-11e8-940b-b7d60651a92b.png)

There has two simplebar elements Each is wrapped in a flex wrapper, and flex is set to 1 1 50%. and Inside has table.
Here is a simple summary:
div(display: flex) > section(flex: 1 1 50%)*2 > div(data-simplebar) > table(width: 100%)

## Additional context

![image](https://user-images.githubusercontent.com/3365053/49205864-a8d60180-f3f3-11e8-98da-35da2f829419.png)
![image](https://user-images.githubusercontent.com/3365053/49206053-2ac62a80-f3f4-11e8-88b3-caa3b58c7043.png)

This is recorded function calling. which is repeating a pattern similar to the above.

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 3.1.0
| Browser          | Google Chrome 70
| npm/Yarn         | None
| Operating System | Windows 10, Android

**Comment by Grsmto** [comment]
Hi,
thanks for this report.
It comes from the nature of the `flex-basis` property that works differently from `width/height`. In the meanwhile you can probably  work around this issue by applying `overflow: hidden` to the `data-simplebar` element or just use `width` instead of `flex-basis`

**Comment by Grsmto** [comment]
I had a deeper look at this and the solution is not an easy one.
It's definitely fixable but it involves quite some code so I will wait for now for more reports. If this is really blocking (as in, the workaround I proposed can't solve that), I will try to get a fix built-in.

**Comment by ZerglingGo** [comment]
Thank you.
I am currently using a temporary method to use `width` instead of `flex-basis`

**Comment by Grsmto** [comment]
Guys, I just released simplebar@4.0.0-alpha.0 that would be awesome if you could let me know if this is still happening with the new version.
Thanks for your contribution!

**Comment by ZerglingGo** [comment]
I have trying with simplebar@4.0.0-alpha.0, but problem is still continuing.

**Comment by Grsmto** [comment]
Ok thanks. It happens only when the scrollbar is floating. Got it.
I'll look into it.

**Comment by Grsmto** [comment]
I'm releasing `simplebar@4.0.0-alpha.1` in a few min. Let me know how it's going.

**Comment by ZerglingGo** [comment]
All right, now the problem is solved.
Thank you for your wonderful project and hard work.
