### ISSUE TITLE
Missing min-height: 0; for the simplebar-placeholder class, the content can't shrink when using flex box in Firefox

### ISSUE THREAD

**Issue by gustavshf** [Grsmto/simplebar#243]
## 🐛 Bugs

Please complete the following template:

## Current Behavior

When an element with data-simplebar is used as a part of flex container, it can grow, but it cannot shrink in Firefox, because min-height: 0; for the simplebar-placeholder class is missing.

## Expected behavior

The element with data-simplebar should be able to shrink in firefox as well when used as a part of a flex container.

## Reproducible example

Cannot make this library work in jsFiddle at the moment.

## Suggested solution(s)

Adding min-height:0 to the simplebar-placeholder class

## Your environment

| Software         | Version(s) | 
| ---------------- | ---------- |
| SimpleBar        | 3.1.0
| Browser          | Mozilla Firefox
| npm/Yarn         |
| Operating System | Windows

**Comment by yahyaerturan** [comment]
Having same issue with bootstrap 4 flex sidebar. I have a un-necessary `simplebar-placeholder` with 1000 px.  How can I solve this?

**Comment by Grsmto** [comment]
It's related to #253

**Comment by Grsmto** [comment]
Should be fixed in simplebar@4.0.0-alpha.0! 👊
