### ISSUE TITLE
Simplebar-vue doesn't replace horizontal scrollbar

### ISSUE THREAD

**Issue by mauleous** [Grsmto/simplebar#245]
## Current Behavior

Simplebar-vue only replace vertical scrollbar.

## Expected behavior

Simplebar-vue replaces both horizontal and vertical scrollbar.

## Reproducible example

```vue
<template>
  <simplebar data-simplebar-auto-hide="false" style="height: 100px; width: 100px;">
    <div style="width: 1000px; height: 1000px; background-color: #BDCCD4;">asdf</div>
  </simplebar>
</template>

<script>
import simplebar from 'simplebar-vue';
import 'simplebar/dist/simplebar.min.css';

export default {
  name: 'App',
  components: {
    simplebar
  },
}
</script>

```

## My environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | simplebar-vue v0.1.0 |
| UIKit    | 3.0.0-rc.24 |

**Comment by Grsmto** [comment]
Latest version should fix this.
Thanks for your report!
