### ISSUE TITLE
Can't Import simple bar into Angular7 Application

### ISSUE THREAD

**Issue by maitNoserYoung** [Grsmto/simplebar#246]
I use a UI Tempalte for my project, which uses Simplebar.
Sadly I can't get it to work, due to SimpleBar not being importable, is this a known issue?
Any idea on how I can fix this?
I already tried using a old version, but that doesn't work either.

**Comment by Grsmto** [comment]
We need more context to help you. This is not a known issue. 
Here is a Code Sandbox with Angular 7 loaded, can you provide an example of the issue from this? https://codesandbox.io/s/6y8rvvz3rz

I don't use Angular so I don't know how to set it up.

**Comment by serkon** [comment]
Hi,

1. First install `npm install simplebar --save`
2. Add polyfills.ts this:
`import 'simplebar'; // or "import SimpleBar from 'simplebar';" if you want to use it manually.`
3. then add main style.scss file this:
`@import '~simplebar/dist/simplebar.css';`
4. add `data-simplebar` attribute to which element you want to be scrolled with this theme. For example:
`<div  class='container' data-simplebar>`

**Comment by qiurenbo** [comment]
Hi, I make a wrapper for Angular. So you can use it in any component:


## Installation

```
npm i simplebar
npm i simplebar-angular
```

## Usage

### Import module

```js
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { SimplebarAngularModule } from 'simplebar-angular';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, SimplebarAngularModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

### Use component

```js
<div class="container">
  <ngx-simplebar [options]="options">
    <div *ngFor="let number of numbers">ngx-simplebar</div>
  </ngx-simplebar>
</div>

```

You can click [here](https://stackblitz.com/edit/simplebar-angular-demo) to see the demo.

**Comment by Grsmto** [comment]
Closing this since we now have an Angular plugin. Thanks.

**Comment by ranouf** [comment]
Hi,

@qiurenbo , I forked your sample use the attribute, but it does not work that way, any idea?
https://stackblitz.com/edit/simplebar-angular-demo-uehvzp?file=src/app/app.component.html

Thanks
