### ISSUE TITLE
Uncaught TypeError: Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by lmaowski** [Grsmto/simplebar#247]
## Current Behavior

Uncaught TypeError: Cannot read property 'left' of undefined

## Your environment
"simplebar": "3.1.0", npm, linux, chrome, ember.js 2.18

**Comment by lmaowski** [comment]
Ok managed to get a bit more info:

it's happening in the [`isWithinBounds`](https://github.com/Grsmto/simplebar/blob/simplebar%403.1.0/packages/simplebar/src/simplebar.js#L847) method. `bbox` is undefined. it's being called from the [`onPointerEvent` handler, here](https://github.com/Grsmto/simplebar/blob/simplebar%403.1.0/packages/simplebar/src/simplebar.js#L710).

i'm not sure how to reproduce this. i just click around randomly in my app (using ember.js)

**Comment by Grsmto** [comment]
Latest version should fix this.
Thanks for your report!
