### ISSUE TITLE
Track doesnt align with scrollbar thumb

### ISSUE THREAD

**Issue by boandriy** [Grsmto/simplebar#252]
Hello, I was trying to use simplebar to implement a scrollbar that would have a margin from right, top and bottom of the container div. Here is my css for it:

```
.simplebar-vertical{
  top: 5px !important;
  bottom: 5px !important;
  right: 5px !important;
}

.simplebar-scrollbar:before {
  background-color: red;
  opacity: 1 !important;
}

.simplebar-track.simplebar-vertical{
  background-color: green !important;
  border-radius: 5px;
  width: 7px !important;

}
.simplebar-track{
  border-radius: 5px !important;
  opacity: 1 !important;
}
```
As you can see I have changed the width of the track to be also equal to 7 px. But as a result the tracks background looks shifted to the right a bit and the scrollbar thumb doesn't align with the track. Is that a code problem or am I missing something? Thanks in advance.
Here is a picture.

![70](https://user-images.githubusercontent.com/22635911/50539764-64728880-0b8e-11e9-83c5-db5227d9efcc.png)

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | latest
| Browser          | chrome

**Comment by andersk** [comment]
SimpleBar by default expects the track to be 4px wider than the thumb, with 2px padding on either side. If you don’t want that, [try overriding this rule](https://github.com/Grsmto/simplebar/blob/simplebar%404.0.0-alpha.6/packages/simplebar/src/simplebar.css#L122).
