### ISSUE TITLE
Missing Dependencies with NPM

### ISSUE THREAD

**Issue by tophat1986** [Grsmto/simplebar#255]
ReadMe doesn't specify but for the noobs like me, it would help to state that this package requires additional package to install via webpack.  Throwing errors on build and I wasn't sure why.

`npm install --save core-js`

**Comment by Grsmto** [comment]
This is a bug.
Thanks for the report.

**Comment by vkrol** [comment]
@Grsmto why it was added to the dependencies if this package is not imported anywhere?

**Comment by Grsmto** [comment]
@vkrol it is imported by the transpiled code, once Babel has transformed the code to ES5.
Basically `core-js` is used to polyfill some ES6 features like `Array.from` and this kind of stuff. So it's a dependency of the compiled code but not the source code.

I think nobody noticed this before cause most users use Babel anyway and so they already had `core-js` implicitly in their `node_modules`.

**Comment by vkrol** [comment]
@Grsmto thank you!
