### ISSUE TITLE
Transition between native and simplebar (disable, destroy)

### ISSUE THREAD

**Issue by adjourn** [Grsmto/simplebar#257]
Sorry about wall of text, Im adding some extra info in case someone wants to implement it too (took me almost a whole day to discover edge cases and figure everything out) or if you want more background info for my reasoning. **DL;DR** issue and proposal are stated under **Problem**.

Im trying to make a case for proper disable/destroy method, I found several issues but all of them were asking for original DOM. Let me know what you think. If you don't like my idea, I could probably hack it.

---

Im exploring the best way to transition between native and `simplebar`. Im using React [in my demo](https://jsfiddle.net/8snmaxd1/) but same concepts should apply to most modern UI libraries. 

I think the best way would be to pass `disabled` prop to scroll component (similar to `simplebar-react`) and act based on that. That way I could toggle `simplebar` if business logic requires it or e.g parent component detects mobile device. `disabled` prop route also has several pros compared to destroying everything (some listed right here).

Here are few ways to render:      

#### 1. Render `simplebar` DOM elements in all cases
   - transition is a lot more efficient if DOM has same structure (no DOM mutations)
   - content `state` (any depth inside scrollbar) is preserved between transitions

#### 2. Render custom `div` (or other element) if `disabled`
   - faster for mobile (very questionable, saves only ~10 `div` elements)
   - all content `state` is lost on transitions (different DOM -> new component instances)
   - `simplebar` DOM elements are gone after transition to native but `simplebar` has just enough time to make last style changes before `unMount()` (applies styles to random content elements instead)

**Option 2.5** would be to render different component altogether and let JS remove any traces of `simplebar` but it has the same cons as second option (`state` is lost and it's even less efficient rendering wise).

---

#### Problem

I went with the first option, always render `simplebar` DOM elements and use `instance.unMount()`. 

But it doesn't remove all listeners, e.g `mousemove` fires `onMouseMove` which executes a lot of logic and scrollbar still appears if I hover track. I could force `opacity: 0;` with CSS but it's still a lot of pointless work.

I think `simplebar` should have a method (`unMount` or something else) that cleans up everything except DOM elements. It would make transitions so much easier and have smaller performance impact.

---

I also think that this is not accurate anymore ([source](https://grsmto.github.io/simplebar/)). Can't see any code that handles mobile.

> #### Supported everywhere
> SimpleBar support every modern browser and IE9+.
> It disables itself on mobile and device with "floating" scrollbars (macbook trackpad for example). But you can still force it if you want!

**Comment by Grsmto** [comment]
>simplebar DOM elements are gone after transition to native but simplebar has just enough time to make last style changes before unMount() (applies styles to random content elements instead)
>it doesn't remove all listeners, e.g mousemove fires onMouseMove which executes a lot of logic

These are definitely bugs and should be fixed. 
I think your second approach is the right one. Still I don't understand in what real app scenario you would ever want to do that? Could you describe your use case?

>I also think that this is not accurate anymore (source). Can't see any code that handles mobile.
You are right, this logic has been removed a long time ago because it was simple to implement in user land, website is not up to date.

If I suppose that you want to disable simplebar for mobile users (as your demo seems to show), I  believe you are going way overkill in trying to mount/unmount based on screensize/resize. The recommended way is to detect floating scrollbars at init and use or not simplebar based on that.

**Comment by Grsmto** [comment]
>do you agree that unMount should clean everything up (all listeners)?

Yes absolutely!
As I said in my previous comment:
>These are definitely bugs and should be fixed.

Thanks for your useful input as usual.

**Comment by Grsmto** [comment]
Hey @adjourn just published v3.1.3, hope it helps fixing your issue!

**Comment by adjourn** [comment]
It sure does, thank you! 

Im going to close this because the other mentioned bug isn't really `simplebar` fault I think. 

Should be obvious that if you change `simplebar` DOM structure while instance is still up, there be dragons and checking DOM validity all the time would be too much pointless work for `simplebar`. In order to avoid that bug, `simplebar` should be unmounted before updating DOM (not the case in my quick demo).
