### ISSUE TITLE
What you mean by: Simplebar doesn't use Javascript to handle scrolling?

### ISSUE THREAD

**Issue by scazzy** [Grsmto/simplebar#26]

**Comment by Grsmto** [comment]
I mean that the library doesn't simulate the scroll behaviour with custom JavaScript (aka "scroll hijacking"). Which means it's the same "browser native" scroll as when you do `overflow: scroll`.
(of course behind the scene it's still handled by the browser's JavaScript)
It's not very clear, I'll try to fix that.

**Comment by scazzy** [comment]
Okay. Sounds better.
But I read you use the scroll event, and you use jquery, it's confusing when you say it doesn't use javascript.

Also, does it handle the fixed/absolute containers with fixed dimensions having rough scrolling, like iphone safari?
