### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by adjourn** [Grsmto/simplebar#261]
#### Bug or feature..

I just came across this issue and I noticed that it has never been brought up here.
 
Currently `scroll-behavior: smooth;` can't be used. Dragging scrollbar with mouse is implemented by setting `scrollTop` which is affected by mentioned CSS rule. Browser smooths the scrolling and it feels sluggish and laggy. Same most likely (haven't tested it) applies to `x` axis and `scrollLeft`.

### [Demo](https://jsfiddle.net/de71fh28/)

Alternative is to animate with JavaScript and set `scrollTop` by using `requestAnimationFrame`.

---

Do you plan to support it? I have no idea what to replace `scrollTop` with.. In any case, feel free to close, could be a good issue for someone to find if having the same trouble.

**Comment by Grsmto** [comment]
A workaround could be to disable the property when the scrollbar is dragged.
Alternatively you could use [ScrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) instead of this, that would have the same effect.

**Comment by 2mkabir** [comment]
> A workaround could be to disable the property when the scrollbar is dragged.
> Alternatively you could use [ScrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) instead of this, that would have the same effect.

Hi
How use scrollIntoView Function?
I use this but not work!!
el.getScrollElement().getElementById('page').scrollIntoView()

**Comment by n0099** [comment]
Possible related: https://github.com/Norserium/react-indiana-drag-scroll/issues/53, https://github.com/mdn/content/issues/2719 and https://stackoverflow.com/questions/60795723/how-to-override-the-css-scroll-behavior-with-scrollto-in-javascript/66424833#66424833
