### ISSUE TITLE
Module polyfills

### ISSUE THREAD

**Issue by adjourn** [Grsmto/simplebar#264]
## Current Behavior

Screenshot is from `webpack-bundle-analyzer`. As you can see, `simplebar.esm.js` imports all necessary polyfills (thanks to `preset-env`). But it becomes an issue if we use `preset-env` for our code too, many polyfills get added twice. Gzip compresses it quite nicely when sent over the network (for those of us who use compression, ~3Kb difference) but it's still ~16Kb more JS to parse.

![polyfills](https://user-images.githubusercontent.com/17890701/52411754-7debe600-2ae5-11e9-934e-d540492e871d.png)

## Expected behavior

Im not 100% sure what's the correct way to handle this because Webpack is still largely a black box for me but it makes sense that if project uses `esm` bundle, it probably already polyfills other files and `simplebar` shouldn't import them. App's build process should run `babel-loader` on every `.js` file like big projects do (e.g. [`create-react-app`](https://github.com/facebook/create-react-app/pull/3776)), at least for production build.

`simplebar.js` and `simplebar.min.js` are already around 13Kb (after my own uglify and gzip), I presume both already include polyfills and that's okay because these are used in different environments.

## Suggested solution(s)

Don't import polyfills in `simplebar.esm.js`. Or should there be another bundle? Again, black box..

**Comment by Grsmto** [comment]
Hi @adjourn !
The esm package just declares its dependencies (using `import ...`) so in theory the bundler should not import these dependencies twice! If it does, it means the bundler doesn't load the esm file but the .js :/
>many polyfills get added twice.
I don't know why this is happening to be honest. I need to take a deeper look but in theory the esm version should still be pre-transpiled "ready to use" and the user shouldn't have to use Babel. Usual Webpack setup like `create-react-app` does *not*  transpile `node_modules` but only your source files. Every `node_modules` is supposed to be pre-transpiled.


The biggest deps for SimpleBar is the `resize observer polyfill`, I know it's bloating the size of the bundle and it's unavoidable. That's another issue but I was thinking that we could provide an option to load SimpleBar without it.

Could you confirm that some things are included twice in your final bundle? If so it's a bug. Otherwise it's just about performances optimisation.

**Comment by adjourn** [comment]
Yes, I can cofirm that 5.56 Kb (gzip) of polyfills is included into simplebar. `esm` is definately being used because if I comment imports out, none of the polyfills get added twice to final bundle.

#### node_modules/simplebar/dist/simplebar.esm.js

```js
/**
 * SimpleBar.js - v3.1.3
 * Scrollbars, simpler.
 * https://grsmto.github.io/simplebar/
 *
 * Made by Adrien Denat from a fork by Jonathan Nicol
 * Under MIT License
 */

// import 'core-js/modules/es6.regexp.replace';
// import 'core-js/modules/es6.function.name';
// import 'core-js/modules/es6.regexp.match';
// import 'core-js/modules/web.dom.iterable';
// import 'core-js/modules/es6.string.iterator';
// import 'core-js/modules/es6.array.from';
import scrollbarWidth from 'scrollbarwidth';
import throttle from 'lodash.throttle';
import debounce from 'lodash.debounce';
```

What's weird is that other dependencies get hoisted to bundle global scope (where they could be reused) but `core-js` dependencies stay inside `simplebar` scope (like shown in image above).


I don't mind `resize observer polyfill` that much, it's only 2.4Kb gzip. Especially compared to this issue.

**Comment by Grsmto** [comment]
I tried to find a solution for this but I'm kinda stuck.
I think it's related to that issue https://github.com/zloirock/core-js/issues/385

I need to see how other libraries/components are doing it and see if there is a solution.

**Comment by adjourn** [comment]
@Grsmto I have some great news. I had permission issues in my folder (hello Linux), so I deleted `yarn.lock` file, modules directory and ran `yarn` command, now I don't have this issue. :tada: 

I think it's safe to say that the problem was somewhere else and I have no idea where.

**Comment by Grsmto** [comment]
That's great news.
However if you check [here](https://bundlephobia.com/result?p=simplebar@3.1.3) you can see that core-js is taking a huuuuge part of the library size.
Which is weird because I don't use that many "new" functions. Feels like it's way too big, so I believe something wrong is definitely happening!

**Comment by adjourn** [comment]
I think it might make sense, when I copy-pasta `simplebar.js` and compile it myself:

Code is ~4.8kB, observer 2.4kB, lodash ~2.9kB total, core polyfills ~5kB + others ~0.45kB. These numbers are probably not very accurate (`webpack-bundle-analyzer`) but ratios should be kind of right.

```
["@babel/preset-env", {
  "useBuiltIns": "usage",
  "debug": true
}]

"last 2 version", "not dead", "> 0.2%", "ie 10" (what I usually use)

Added following polyfills:
  es6.array.from { "android":"4.2", "chrome":"49", "ie":"10", "ios":"8" }
  es6.string.iterator { "android":"4.2", "ie":"10", "ios":"8" }
  web.dom.iterable { "android":"4.2", "chrome":"49", "edge":"17", "firefox":"52", "ie":"10", "ios":"8", "opera":"56", "safari":"11.1" }
  es6.regexp.match { "android":"4.2", "chrome":"49", "edge":"17", "ie":"10", "ios":"8" }
  es6.function.name { "ie":"10" }
  es6.regexp.replace { "android":"4.2", "chrome":"49", "edge":"17", "ie":"10", "ios":"8" }
  es6.object.keys { "android":"4.2", "ie":"10", "ios":"8" }
  es6.array.iterator { "android":"4.2", "ie":"10" }


"> 0.25%", "not op_mini all" (browserlist used by simplebar)

Added following polyfills:
  es6.array.from { "android":"4.4.3", "chrome":"49", "ie":"11", "ios":"8" }
  es6.string.iterator { "android":"4.4.3", "ie":"11", "ios":"8" }
  web.dom.iterable { "android":"4.4.3", "chrome":"49", "edge":"17", "firefox":"64", "ie":"11", "ios":"8", "opera":"57", "safari":"11.1" }
  es6.regexp.match { "android":"4.4.3", "chrome":"49", "edge":"17", "ie":"11", "ios":"8" }
  es6.function.name { "ie":"11" }
  es6.regexp.replace { "android":"4.4.3", "chrome":"49", "edge":"17", "ie":"11", "ios":"8" }
  es6.object.keys { "android":"4.4.3", "ie":"11", "ios":"8" }
  es6.array.iterator { "android":"4.4.3", "ie":"11" }
```

**Comment by adjourn** [comment]
If it's something you want to address, I did some research:

If you replace `Array.from` (this has multiple listed dependencies) and find an alternative to current regexp (older version perhaps), you should only end up with `web.dom.iterable` (should be around 468B).

**Comment by Grsmto** [comment]
ref: https://medium.com/@WebReflection/avoiding-babels-production-bloat-d53eea2e1cbf
