### ISSUE TITLE
Rowspan Not Working on Table using simplebar

### ISSUE THREAD

**Issue by heckme** [Grsmto/simplebar#265]
**i try this with out simplebar**
![image](https://user-images.githubusercontent.com/8361133/52556281-25348a00-2e12-11e9-9b3c-5523ae6cbc45.png)

**i try this with simplebar**
not wokin rowspan this table

![image](https://user-images.githubusercontent.com/8361133/52556185-d71f8680-2e11-11e9-9253-eb83d8efcfb0.png)

**Comment by heckme** [comment]
<table class="table table-striped table-bordered table_com_all m-t-15">
                    <thead>
                      <tr>
                        <th>Draft Id</th>
                        <th>Cust Order Ref</th>
                        <th>Contact</th>
                        <th>Delivert Service</th>
                        <th>PostCode</th>
                        <th>Message</th>
                        <th>Fix</th>
                      </tr>
                    </thead>
                    <tbody id="simpleBar" data-simplebar data-simplebar-auto-hide="true">
                      <tr>
                        <td>213</td>
                        <td>10025</td>
                        <td>test</td>
                        <td>No Service</td>
                        <td>390022</td>
                        <td>Cus Order ref not valid</td>
                        <td Rowspan="6" align="center">
                          <a class="btn btn-edit btn-sm mr-2"><i class="fa fa-pencil"></i> Fix</a>
                          <a class="btn btn-warning btn-sm"><i class="fa fa-remove"></i> Delete</a>
                        </td>
                      </tr>
                      <tr>
                        <th Colspan="3" Rowspan="4">&nbsp;</th>
                        <th>Error</th>
                        <th>Field</th>
                        <th>Error Messge</th>

                      </tr>
                      <tr>
                        <td>no Service</td>
                        <td>396589</td>
                        <td>Product Code not Valid</td>
                      </tr>
                      <tr>
                        <td>no Service</td>
                        <td>396589</td>
                        <td>Product Code not Valid</td>
                      </tr>
                      <tr>
                        <td>no Service</td>
                        <td>396589</td>
                        <td>Product Code not Valid</td>
                      </tr>
                      <tr>
                        <td colspan="7" height="0"></td>
                      </tr>




                      <tr>
                        <td>213</td>
                        <td>10025</td>
                        <td>test</td>
                        <td>No Service</td>
                        <td>390022</td>
                        <td>Cus Order ref not valid</td>
                        <td Rowspan="6" align="center">
                          <a class="btn btn-edit btn-sm mr-2"><i class="fa fa-pencil"></i> Fix</a>
                          <a class="btn btn-warning btn-sm"><i class="fa fa-remove"></i> Delete</a>
                        </td>
                      </tr>
                      <tr>
                        <th Colspan="3" Rowspan="4">&nbsp;</th>
                        <th>Error</th>
                        <th>Field</th>
                        <th>Error Messge</th>

                      </tr>
                      <tr>
                        <td>no Service</td>
                        <td>396589</td>
                        <td>Product Code not Valid</td>
                      </tr>
                      <tr>
                        <td>no Service</td>
                        <td>396589</td>
                        <td>Product Code not Valid</td>
                      </tr>
                      <tr>
                        <td>no Service</td>
                        <td>396589</td>
                        <td>Product Code not Valid</td>
                      </tr>
                    </tbody>
                  </table>

**Comment by heckme** [comment]
![image](https://user-images.githubusercontent.com/8361133/52557215-c4f31780-2e14-11e9-9030-c74d44cdf7ac.png)

**Comment by Grsmto** [comment]
Tables are not supported using the HTML `<table>` element because Simplebar uses a `<div>` element.
I will add this info in the README.
