### ISSUE TITLE
Bug: Content jumps when calling recalculate method on iOS

### ISSUE THREAD

**Issue by Demivan** [Grsmto/simplebar#266]
## Current Behavior

When content is scrolled to the bottom calling `recalculate` method scrolls/jumps content up on iOS. It is only happening if content width is wider then container and is wrapping.

## Expected behavior

When calling `recalculate` scroll position should remain the same.

## Suggested solution(s)

This code resets padding set on content element to `0` causing it to have bigger width:
https://github.com/Grsmto/simplebar/blob/0016518f0922c22adb49a2dc0d61e6ce29e398b9/packages/simplebar/src/simplebar.js#L410-L412
Inside `hideNativeScrollbar` padding is set to correct value but not before content moved up because with more width it can wrap differently
https://github.com/Grsmto/simplebar/blob/0016518f0922c22adb49a2dc0d61e6ce29e398b9/packages/simplebar/src/simplebar.js#L552-L557

Setting padding in one assignment fixes this issue.

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 3.1.1
| Browser          | Safari
| npm/Yarn         | n/a
| Operating System | iOS

**Comment by Grsmto** [comment]
Hey @Demivan as you're working on SimpleBar at the moment, I'm curious if this is still an issue with latest version? Thanks!

**Comment by Demivan** [comment]
@Grsmto I have removed all calls to `recalculate` method when switching to version 4.0.0 as it now detects changes better. So I think this can now be closed.
