### ISSUE TITLE
Scrollbars remain visible when the CSS position of track is changed

### ISSUE THREAD

**Issue by vvasilev-** [Grsmto/simplebar#267]
Hi there,

Thanks for the great plugin! I noticed that if we change the position of vertical track for example then the scrollbar remains visible even if there is not enough content to overflow the container. 

Thanks in advance! 

## Current Behavior

The scrollbar remains visible.

## Expected behavior

The scrollbar should be hidden.

## Reproducible example

https://jsfiddle.net/v95qcmxy/

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 3.1.3
| Browser          | Chrome  72.0.3626.96
| Operating System | macOS Mojave

**Comment by Demivan** [comment]
Setting `top` and `bottom` for track resizes it and parent container.
If you want to change position of track set only one value. https://jsfiddle.net/h8o79ren/

**Comment by vvasilev-** [comment]
Hi @Demivan,

Thanks for the feedback. What I really need is to have a track which is smaller than the original container that's why I use both positions.

**Comment by Demivan** [comment]
@vvasilev- Then you need to wait for fix.
@Grsmto this happens because `isOverflowing` is set based on bounding rect of axis. Shouldn't `isOverflowing` compare content scroll height/width to `wrapperEl` bounding rect?

**Comment by Grsmto** [comment]
Yeah that makes sense. I think your proposed solution is right @Demivan I don't think there is any reason to calculate based on track size instead of wrapper.

**Comment by Grsmto** [comment]
Should be fixed in `simplebar@4.0.0-alpha.0`!
