### ISSUE TITLE
Missing Dependencies in React Example

### ISSUE THREAD

**Issue by mikhailsidorov** [Grsmto/simplebar#272]
There is `simplebar`  instead of `simplebar-react` in react example dependencies.  PR #271

**Comment by mikhailsidorov** [comment]
> Thanks for your contribution!

You are welcome.

**Comment by mikhailsidorov** [comment]
> Thanks for your contribution!

You are welcome.

**Comment by Grsmto** [comment]
Thanks for your contribution!
