### ISSUE TITLE
flickering scrollbar and content in Firefox

### ISSUE THREAD

**Issue by adsim** [Grsmto/simplebar#273]
I have an weird issue in Firefox where the scrollbar and the scrollable content are flickering as if simplebar can't decide whether a scrollbar is necessary or not. The scrollable container has a max-height of 350px and the issue happens far below this max-height.
It's only in Firefox (Windows, Mac and Linux ... tested at Browserstack) and only in an small area of possible heights.

https://www.dropbox.com/s/jsnmqiueyjkot6h/warenkorb2.mp4?dl=0

http://www.kryolan.einfach-beginnen.de/myaccount-singleorder.html

Any ideas how I could prevent this?

**Comment by jpfranchini1** [comment]
We are facing the same issue on Firefox when zooming. As mentioned, simplebar adds and removes the vertical scrollbar indefinitely while the container's height is < to max-height.
When the zoom is 100% the same container stops flickering.

**Comment by omitech** [comment]
Have the same issue. Only happens in firefox. Is there any way to resolve this?

**Comment by Grsmto** [comment]
Guys, I just released `simplebar@4.0.0-alpha.0` that would be awesome if you could let me know if this is still happening with the new version.
Thanks for your contribution!

**Comment by jozerozman** [comment]
@Grsmto  I also had this issue on mac Chrome and Safari. Updated to latest alpha version and now it's working!
