### ISSUE TITLE
Horizontal Scrolling Container

### ISSUE THREAD

**Issue by elalemanyo** [Grsmto/simplebar#277]
I am trying to use Simplebar with a Horizontal Scrolling Container, but is not working as expected.
[Here is a demo](https://codepen.io/elalemanyo/pen/vPZRZb) where you can check it.

Thanks

**Comment by justindmyers** [comment]
It's not working because you're container has no width so it's just growing the body width. You just need a container with a set width: https://codepen.io/justindmyers/pen/BbwydK

**Comment by elalemanyo** [comment]
Ok, but why is not showing scrollbars always? Is not `autoHide: false` suppose to do that?

**Comment by justindmyers** [comment]
@elalemanyo That part may be a bug. I noticed if I clicked on the scrollbar, it then stayed visible. 

It might be related to this: https://github.com/Grsmto/simplebar/issues/262

**Comment by elalemanyo** [comment]
@justindmyers sorry but I think that simplebar is not working, what I see is just the browser scrollbar. I think the problem is with the style from the inside elements, maybe.

**Comment by Grsmto** [comment]
https://codepen.io/Grsmto/pen/wOLWZo

**Comment by elalemanyo** [comment]
@Grsmto Scrollbar is not showing up on Safari

<img width="1433" alt="2019-03-27_1727" src="https://user-images.githubusercontent.com/3856862/55093949-adff4080-50b5-11e9-93b3-ab39090baf3d.png">

**Comment by elalemanyo** [comment]
It is also not possible to scroll to the end of the container. `simplebar-offset`container have inline right value making not possible to see the las part of the container. Is maybe because of using flex?
https://codepen.io/elalemanyo/full/vPZRZb
