### ISSUE TITLE
Simplebar has problem with collapse elements from Bootstrap

### ISSUE THREAD

**Issue by tottello** [Grsmto/simplebar#278]
Latest Bootstrap and Simplebar has problem with collapse element. Script is initialized but scrollbars doesnt show up and scrolling doesn't work.

## Current Behavior

Click 'Item 1' and 'Item 2'

https://jsfiddle.net/ops71v3f/

## Expected behavior

Click 'Item 1' and 'Item 2'

https://jsfiddle.net/r9en2d16/

**Comment by Grsmto** [comment]
Closed in favour of #282.

**Comment by oliviercperrier** [comment]
@Grsmto The same problem occurs when using Ant Design collapse.
