### ISSUE TITLE
Not detecting textarea resize

### ISSUE THREAD

**Issue by Cyrus-d** [Grsmto/simplebar#280]
## Current Behavior

I understand simplebar does not support the textarea, however, apparently, it's not detecting the textarea resizing either. is it by design?

## Expected behaviour

when textarea resized the simplebar should detect the resize change of textarea and recalculate scrollbar.

## Reproducible example

[https://codepen.io/Cyrus80/pen/QoryzR?editors=1111](https://codepen.io/Cyrus80/pen/QoryzR?editors=1111)

## Suggested solution(s)

Current I am using 'element-resize-event' to detect the change and update the scrollbar.

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | v3.1.3
| chrome            | 73.0.3683.75
|windows 10      | 64

**Comment by Grsmto** [comment]
Fixed in v3.1.5.
