### ISSUE TITLE
Bug: Infinite recalculating in 3.1.5

### ISSUE THREAD

**Issue by Odrin** [Grsmto/simplebar#286]
## Current Behavior

Infinite recalculating if scroll present (MutationObserver -> recalculate).

## Expected behavior

Simplebar don't recalculate infinitely.

## Reproducible example

https://jsfiddle.net/0u9rpfys/2/
Create breakpoint in `recalculate` method.

## Additional context

Problem appeared in 3.1.5 here:
https://github.com/Grsmto/simplebar/blob/7addb63af67a12d121218916ba0733355b6c9e09/packages/simplebar/src/simplebar.js#L389-L400
MutationObserver infinitely handles `this.contentEl` attribute `style` mutation.

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 3.1.5
| Browser          | Chrome 73, Firefox 67.0b7
| npm/Yarn         | npm 6.9.0
| Operating System | MacOS

**Comment by Grsmto** [comment]
Hey,

Just looking into this right now, could you give me some details on how to reproduce? I'm testing on Chrome 73 mac and I can't get the infinite loop to kick in.
cc @jmaryniowski

**Comment by Odrin** [comment]
@Grsmto just create breakpoint at line 3969 in simplebar.js [here](https://jsfiddle.net/0u9rpfys/2/).

**Comment by Grsmto** [comment]
Yeah I did and it's never being called whatever I do in your jsfiddle.

**Comment by Odrin** [comment]
It's strange because I can reproduce this in any browser on my Mac (10.14.4). [Example](https://www.dropbox.com/s/0i8e8odw53jnklg/Screen%20Recording%202019-04-08%20at%2010.10.33.mov?dl=0)
<img width="1563" alt="Screenshot 2019-04-08 at 11 19 46" src="https://user-images.githubusercontent.com/1961250/55709304-b7ab7100-59f0-11e9-8054-123dc338b11e.png">

**Comment by Grsmto** [comment]
That's so weird! I'll investigate this more.

Btw I just released `simplebar@4.0.0-alpha.0` if you could test and tell me if it's still happening. Actually we got rid entirely of this mutation observer so...
If you see any weirdness like this with the alpha, please re-open!

Thanks!

**Comment by melono6** [comment]
I have experienced the same issue on v3.1.5 in all browsers, causing performance issues and locking browser up completely in some cases. Reverting to earlier version fixed the issue
