### ISSUE TITLE
[Suggestion] Simpler wrapper for Vue

### ISSUE THREAD

**Issue by hfalucas** [Grsmto/simplebar#287]
Hi @Grsmto thank you for such a great plugin. Noticed the existence of a Vue and React wrapper and If you may I want to make some suggestions.

I've made a [simpler wrapper for Vue](https://github.com/hfalucas/simplebar-vue) and added some sugar to it. Inspired in the useful events that [perfect-scrollbar](https://github.com/utatti/perfect-scrollbar/#events) offers like when the scroll reaches the top or bottom, both good for infinite scroll hooks and chat pagination use cases.

My suggestions are:

- Do you think it could make sense to create an organization and have simplebar, simplebar-vue, and simplebar-react in separated repositories (easier to manage issues and pull requests) like [SortableJS](https://github.com/SortableJS) does?

- Is my wrapper good enough to be worthy of a pull request? (Still needs some refactoring, but the idea is there)

- Should the extra events in the wrapper 'scroll-y-reach-end', etc be in the main plugin?

Thank you in advance

**Comment by Grsmto** [comment]
Hi!

> Do you think it could make sense to create an organization and have simplebar, simplebar-vue, and simplebar-react in separated repositories (easier to manage issues and pull requests) like SortableJS does?

I think simplebar is not big enough of a thing to deserve an organisation for now. It's a fairly simple plugin so I don't it expand that much more. Also native scroll customisation is coming in all browsers pretty soon so I don't think this will even be needed for much more time anyway!

>Is my wrapper good enough to be worthy of a pull request? (Still needs some refactoring, but the idea is there)
>Should the extra events in the wrapper 'scroll-y-reach-end', etc be in the main plugin?

The goal of simplebar is to be as simple and small as possible. I try to keep the bundle size the smallest possible (it's far from being perfect but that's the initial goal...). I want to keep it to the strict minimum and ave only native behaviours supported.

Don't take me wrong, I think it's awesome that you built this extra plugin and I would be more than happy to reference it in the README of this repository (or/and in the README of the Vue plugin).
So people can still have the choice between a lighter/simpler version and something with extra sugar like you did!

What do you think?

**Comment by hfalucas** [comment]
Sounds perfect 👍
