### ISSUE TITLE
Publsih on NPM

### ISSUE THREAD

**Issue by doonetheprune** [Grsmto/simplebar#29]
Hi

Would you be able to publish this on on npm so it can be used in webpack or browserify.

Thanks

**Comment by darkwinternight** [comment]
That would be great!

**Comment by ravshansbox** [comment]
I've done this, but if author wants to publish himself i can remove my module.

**Comment by Grsmto** [comment]
Hey guys, thank you for this!
Sorry for not replying as I'm working on the v2 of library I wasn't yet taking care of that but that's definitely needed!
Thanks @ravshansbox once I'm done with v2 I'll ask you again and we can sort this out ;)
I'll drop a line about this on the readme file.

**Comment by Grsmto** [comment]
Hey @ravshansbox ! Could you give me the rights of the NPM simplebar package? I don't know how it works so I let you do...
My username is: `grsmto`
Thank you again!

**Comment by ravshansbox** [comment]
done.

**Comment by Grsmto** [comment]
@ravshansbox got it! Thanks dude 👍
