### ISSUE TITLE
Dummy Simplebars appear at intitialization of component even if no overflow

### ISSUE THREAD

**Issue by marchrenno** [Grsmto/simplebar#290]
I am using Simplebar   "version": "3.1.5" in an Angular project with Angular Material library.
I am currently struggling with the following behavior:

When a component is loaded, all the elements (divs) that have Simplebars show them (if I hover on them), even when there is no overflow. They are dummy scroll bars since I can't really scroll.

Once the content of those divs is modified, the behavior goes back to normal. the Simplebar disappears if there is no overflow.

**Comment by marchrenno** [comment]
I solved the issue by using new SimpleBar(document.getElementById('MyId')) in my  ngAfterViewInit(),  instead of  using the 'data-simplebar' in the HTML.

I guess the initialization of the bar is done too early in the Angular Lifecycle component if I put it in the HTML, and the Simplebar is not set properly then. Now it's all good.

**Comment by Grsmto** [comment]
Yes that's right, it would need an Angular wrapper to actually solve this issue. We have a Vue and React one but no Angular one yet.

**Comment by marchrenno** [comment]
Thanks for the answer.
And actually, regarding my previous solution, it didn't solve it completly. I had to add a "mouse-enter" listener on the div to recalculate the simplebar everytime I hover in the div. Now it works.

**Comment by Grsmto** [comment]
Yeah that's another issue. This has been fixed and will be released very soon!

**Comment by Grsmto** [comment]
Should be fixed in `simplebar@4.0.0-alpha.0`!
Will open another issue for an Angular wrapper.

**Comment by RenishDadhaniya06** [comment]
It is resolved? I am also facing this issue.
