### ISSUE TITLE
simplebar doesn't move in ie 9

### ISSUE THREAD

**Issue by mmehdinasiri** [Grsmto/simplebar#296]
i am use simplbar for ie9,  add [classlist-polyfill](https://github.com/eligrey/classList.js/blob/master/classList.js) and [requestAnimationFrame-polyfill](https://gist.github.com/paulirish/1579671) .
in ie simplarbar shows and scroll but slider doesn't move.
???

**Comment by Grsmto** [comment]
Yes this is because `translate3d` is not supported by IE9.
You can't actually use the latest version on IE9.
I will update the README.
If you absolutely want SimpleBar you can try the v1 as said in the README if it works for you!
