### ISSUE TITLE
Contents with bottom margin result in unnecessary scrollbar

### ISSUE THREAD

**Issue by andersk** [Grsmto/simplebar#299]
## Current Behavior

When putting a SimpleBar around contents with a bottom margin, margin collapse causes the bottom margin to be scrolled out of view.

## Expected behavior

The bottom margin should be visible (unless a height constraint forces it to be pushed out of view), like it would be with native `overflow: auto`.

## Reproducible example

https://jsfiddle.net/anderskaseorg/pcsgrhk0/

## Suggested solution(s)

Disable margin collapsing on `.simplebar-resize-wrapper`, e.g. with `overflow: hidden`.

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 4.0.0-alpha.1
| Browser          | Firefox 66
| npm/Yarn         | N/A
| Operating System | Ubuntu 19.04

**Comment by Grsmto** [comment]
FYI I replaced your solution by a different one since this was breaking horizontal scrolling.
See 8fa844cb19bd735871de4f9692588aa5fc701ac1
