### ISSUE TITLE
reset scrollbar or change position dynamically

### ISSUE THREAD

**Issue by mehulchauhan** [Grsmto/simplebar#3]
Hi,

How can I change scrollbar position dynamically, can you please help me,

In My scenario I am using bootstrap carousel and in each slide I have simplebar implemented, I want to reset scroll-x position to 0 when slide change is done. so that every time on slide change scroll will start from 0.
 
Thanks,
Mehul

**Comment by Grsmto** [comment]
Hi!

It's on the documention here https://github.com/Grsmto/simplebar#user-content-trigger-programmatical-scrolling

So basically what you can do is (in a jQuery context):
```
$('#element').simplebar('getScrollElement').scrollTop(0);
```

**Comment by torabian** [comment]
I have found the solution. You can access scroll element:

```
    const el = new SimpleBar(document.getElementById('layout'));
    el.scrollContentEl.scrollTop = 0;
```

**Comment by SpiritMod** [comment]
const el = new SimpleBar(document.getElementById('layout'));
el.getScrollElement().scrollTo(0,0);
