### ISSUE TITLE
in Firefox "simplebar-scroll-content" class having fixed width 

### ISSUE THREAD

**Issue by gablu** [Grsmto/simplebar#30]
I am using "simple bar" for my new project with "bootstrap" framework. Simple bar scroll is working fine except Firefox the problem is, in Firefox browser 'simple bar-scroll-content' class is having a fixed width which is creating a problem for responsive page, but the issue is not there in any other browsers.
Please help me to resolve it.
Here is the screenshot.
![height](https://cloud.githubusercontent.com/assets/11157455/14851136/8bef8a24-0c9b-11e6-8b3c-ed8b9bacc034.PNG)

**Comment by Grsmto** [comment]
Hi Gablu,
You should take a look at this method: https://github.com/Grsmto/simplebar#user-content-notifying-the-plugin-of-content-changes

If your content is resized, you must notify Simplebar that the content has changed.
You can do that in a window resize event: if you use jquery something along these lines:
```
$(window).on('resize', function(e) {
   $('#myElement').simplebar('recalculate');
});
```

Let me know if it solved your issue.
