### ISSUE TITLE
getScrollElement() no longer gets the element that scrolls

### ISSUE THREAD

**Issue by andersk** [Grsmto/simplebar#308]
## Current Behavior

In 4.0.0-alpha.4 and .5, `getScrollElement()` is no longer the element that scrolls, which breaks setting `scrollTop`, listening for `scroll` events, etc.

## Expected behavior

`getScrollElement()` should be the element that scrolls.

## Reproducible example

https://jsfiddle.net/anderskaseorg/nct1feq6/

## Suggested solution(s)

`getScrollElement()` should be `.simplebar-content-wrapper`, not `.simplebar-content`.

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 4.0.0-alpha.5
| Browser          | Firefox 66
| npm/Yarn         | N/A
| Operating System | Ubuntu 19.04

**Comment by Grsmto** [comment]
Oh damn, sorry about that. Typo when I refactored. Worst thing is that I refactored the unit test as well so it was passing...
