### ISSUE TITLE
Not working in Firefox or IE

### ISSUE THREAD

**Issue by raspberryconverse** [Grsmto/simplebar#31]
Perhaps I have no idea what I'm doing, but I can't seem to get this to work in Firefox or IE.

I do have an error, but it doesn't seem to be impeding it from working in Chrome.

> Uncaught TypeError: $(...).simplebar is not a function

Here is my code up until the actual content that changes from page to page:
```
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Coley Verbick: Web, Mobile, Radio Production, Voice Over and Photography</title>
<link href="../css/styles.css" rel="stylesheet" type="text/css">
<link href="http://overpass-30e2.kxcdn.com/overpass.css" rel="stylesheet" />
<link href="../css/simplebar.css"  rel="stylesheet"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script src='../scripts/perfect-scrollbar.jquery.js'></script>
<script src="../scripts/slidetoggle.js"></script>
<script>$('#site-wrap').simplebar();
 $('#maincontent').simplebar();</script>
</head>
<body class="simplebar-scroll-content">
<ul class="navigation">
    <li class="nav-item"><a href="index.html">Home</a></li>
    <li class="nav-item"><a href="portfolio.html">Portfolio</a></li>
    <li class="nav-item"><a href="about.html">About</a></li>
    <li class="nav-item"><a href="resume.pdf" target="_blank">Resume</a></li>
    <li class="nav-item"><a href="contact.html">Contact</a></li>
</ul>

<input type="checkbox" id="nav-trigger" class="nav-trigger" />
<label for="nav-trigger"></label>
<div id="site-wrap" class="simplebar-scroll-content">
<div id="maincontent" class="simplebar-scroll-content">
```

![image](https://cloud.githubusercontent.com/assets/8049631/15625261/bf3150c0-2465-11e6-8933-9a6ca33e7d51.png)

I know you're rewriting this plugin, but the other suggested plugins broke my jQuery.  If the whole not working in Firefox and IE thing is part of the rewrite, just let me know and I'll see if I can figure out another way.

**Comment by Grsmto** [comment]
Hi,
You seem to have loaded `perfect-scrollbar.jquery.js` instead of simplebar! :)

**Comment by raspberryconverse** [comment]
Even with changing that I'm still getting ugly scrollbars in Firefox and IE.  There are several warnings within the CSS.

> Timestamp: 6/1/2016 10:26:25 PM
Warning: Unknown pseudo-class or pseudo-element '-moz-scrollbar'.  Ruleset ignored due to bad selector.
Source File: file:///C:/Users/Coley%20Coley/Documents/My%20Webs/coley/css/simplebar.css
Line: 24, Column: 27
Source Code:
.simplebar-scroll-content::-moz-scrollbar {
