### ISSUE TITLE
Drag scroll on desktop

### ISSUE THREAD

**Issue by jozerozman** [Grsmto/simplebar#310]
Would it be possible to add an option to have drag scroll option?
Similar to this library: http://asvd.github.io/dragscroll/

**Comment by Grsmto** [comment]
SimpleBar is meant to replicate native scroll and be as lightweight as possible so I don't think this will ever be included.
But this is probably possible to have the library you linked working with SimpleBar but you'll need to experiment!

**Comment by robcostello1** [comment]
I can confirm this works with the following settings:
```
new SimpleBar(yourElement, {classNames: {contentWrapper: 'dragscroll'}});
dragscroll.reset();
```

**Comment by markhowellsmead** [comment]
@robcostello1's solutions works perfectly. 🎉
