### ISSUE TITLE
programmatic smooth scrolling

### ISSUE THREAD

**Issue by ndom91** [Grsmto/simplebar#315]
## 🔎 Usage Questions

Is it possible to programmatically smooth scroll? I'm trying to get a "scroll to top" button working without jumping right back to the top all jittery and ugly -like.

My current code:

```javascript
 $('.go-top').click(function(event) {
    event.preventDefault();
    let bodyscrollTop = simpleBar.getScrollElement()
    bodyscrollTop.scrollTop = 0
    // let bodyscrollTopTop = bodyscrollTop.scrollTop
    // $('html, body').animate({bodyscrollTopTop: 0}, 300);
})
```
That works, but jumps immediately back to the top, which isnt great UX..

The commented out portion is how I would expect to be able to do it smoothly, however that doesnt work at all. No Action. It does not generate any error messages either..

I've tried the `scrollIntoView()` method as well. That doesnt work either. 

Is this simply not possible with simplebar or am I missing something?

**Comment by Grsmto** [comment]
No idea about your jQuery plugin but should works just fine with `scrollIntoView()` but you need to target the element you want to scroll to. Not the element that scrolls itself.
Something like:
```
$('#topOfThePageElement')[0].scrollIntoView({ behavior: 'smooth' })
```

**Comment by ndom91** [comment]
@Grsmto when I tried it previously I had set the element as my header menu bar - that didnt work for whatever reason. I tried it now with the first H1 at the top of the page and that worked flawlessly!

**Comment by al1357** [comment]
Is there a way to programmatically smooth-scroll only the simplebar area without moving browser scrollbar, using Grsmto's method? If both are present they both get scolled.

`<body>
(...)
<div class="simplebar-wrapper">
(...)
<div class="smooth-scroll-to-me">Lorem ipsum...</div>
(...)
</div>
(...)
</body>`

**Comment by Grsmto** [comment]
@al1357 I don't think so.

However there are extra options, see: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

Otherwise you'll have to use another tool to animate the `scrollTop` property.

**Comment by Rod911** [comment]
You could also try 
```
[data-simplebar]:not(.simplebar-dragging) .simplebar-content-wrapper {
	scroll-behavior: smooth;
}
```

**Comment by luizfelipebraga** [comment]
> You could also try
> 
> ```
> [data-simplebar]:not(.simplebar-dragging) .simplebar-content-wrapper {
> 	scroll-behavior: smooth;
> }
> ```

this actually worked. ty

**Comment by darkmodeee** [comment]
> You could also try
> 
> ```
> [data-simplebar]:not(.simplebar-dragging) .simplebar-content-wrapper {
> 	scroll-behavior: smooth;
> }
> ```

Thank you for responding. This truly worked. However, when there is a nested simplebar. It no longer works. It only works on the parent simplebar.

**Comment by Rod911** [comment]
@darkmodeee should work all the same honestly, do you have a codepen or something to test it?

**Comment by darkmodeee** [comment]
> @darkmodeee should work all the same honestly, do you have a codepen or something to test it?

Hi @Rod911 I prepared a fiddle for you. Here's the link: https://jsfiddle.net/zorenkonte/vfb0gLun/42/. Thank you so much for your time.

**Comment by Rod911** [comment]
@darkmodeee [Codepen](https://codepen.io/rod911/pen/yLKKeBQ) See, works like a charm, I find the link tag works better for nested scrollbars as it scrolls both parent and child to get the element into view
