### ISSUE TITLE
Git changes still not making it into releases

### ISSUE THREAD

**Issue by andersk** [Grsmto/simplebar#316]
There was some previous discussion about this on the closed PR #306, but I figure it should have its own issue:

* [simplebar.js 4.0.0-alpha.3](https://unpkg.com/simplebar@4.0.0-alpha.3/dist/simplebar.js) → reads “SimpleBar.js - v4.0.0-alpha.3”
* [simplebar.js 4.0.0-alpha.4](https://unpkg.com/simplebar@4.0.0-alpha.4/dist/simplebar.js) → reads “SimpleBar.js - v4.0.0-alpha.3”
* [simplebar.js 4.0.0-alpha.5](https://unpkg.com/simplebar@4.0.0-alpha.5/dist/simplebar.js) → reads “SimpleBar.js - v4.0.0-alpha.4”
* [simplebar.js 4.0.0-alpha.6](https://unpkg.com/simplebar@4.0.0-alpha.6/dist/simplebar.js) → reads “SimpleBar.js - v4.0.0-alpha.5”
* [simplebar.js 4.0.0-alpha.7](https://unpkg.com/simplebar@4.0.0-alpha.7/dist/simplebar.js) → reads “SimpleBar.js - v4.0.0-alpha.5” (again!)

And the alpha.7 tarball is identical to the alpha.6 tarball with only the version number and (claimed) Git hash changed.

```console
$ mkdir simplebar-4.0.0-alpha.6 simplebar-4.0.0-alpha.7
$ curl 'https://registry.npmjs.org/simplebar/-/simplebar-4.0.0-alpha.6.tgz' | tar -C simplebar-4.0.0-alpha.6 -xz
$ curl 'https://registry.npmjs.org/simplebar/-/simplebar-4.0.0-alpha.7.tgz' | tar -C simplebar-4.0.0-alpha.7 -xz
$ diff -ur simplebar-4.0.0-alpha.6 simplebar-4.0.0-alpha.7
diff -ur simplebar-4.0.0-alpha.6/package/package.json simplebar-4.0.0-alpha.7/package/package.json
--- simplebar-4.0.0-alpha.6/package/package.json	1985-10-26 01:15:00.000000000 -0700
+++ simplebar-4.0.0-alpha.7/package/package.json	1985-10-26 01:15:00.000000000 -0700
@@ -1,5 +1,5 @@
 {
-  "version": "4.0.0-alpha.6",
+  "version": "4.0.0-alpha.7",
   "name": "simplebar",
   "title": "SimpleBar.js",
   "description": "Scrollbars, simpler.",
@@ -38,5 +38,5 @@
     "react-select": "^1.2.1",
     "style-loader": "^0.21.0"
   },
-  "gitHead": "a313e3be55e4659eac2bd17a9456942671c35dd4"
+  "gitHead": "3b283d3fe41868631ace8062ef371e8b7b7c7ce5"
 }

```

In particular, #312 is not present in the tarball even though it is an ancestor of that Git hash.

**Comment by Grsmto** [comment]
I think it should be fine now.
Really struggling with Lerna 😵
