### ISSUE TITLE
SimpleBar host element overflows from parent

### ISSUE THREAD

**Issue by Grsmto** [Grsmto/simplebar#318]
## 🐛 Bugs

Please complete the following template:

## Current Behavior

The div where SimpleBar is applied is overflowing from its parent if only the parent has a size specified. This cause the scroll to not work.

## Expected behavior

Host element should be restrained by parent's size.

## Reproducible example

https://jsfiddle.net/Grsmto/6pm0594L/3/

## Suggested solution(s)

Not sure, @andersk any idea what could solve this? This is the native behaviour so that's kind of "normal". I suppose we could just have a warning of "breaking change" for v4 stable and make sure users define constraint for the host element.
I'm just wondering if there would be a "magic" solution that would solve that.

## Additional context

This is a "regression" of #305

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 4.0.0-alpha.9
| Browser          | all

**Comment by KingSora** [comment]
Good day!

I think if this is the native behavior, I think you shouldn't see this behavior as a bug, but the behavior before, but thats just my oppinion. 

The best possible 'fix' which would give you the correct parent-size if the `outer` element has a size specified, but gives you the auto size if it hasn't is this:

```css
.inner {
    width: auto;
    height: 100%;
}
```
But this only applies if the outer element hasn't some special `position: absolute` - `top` `right` `bottom` `left` values.

But as I said, it sholdn't be treated as bug.

**Comment by Grsmto** [comment]
Hey @KingSora thanks very much for your feedback! I suppose you are right!
Also this "fix" would not solve if `outer` has it's size defined like `max-height: 100px` for ex.

I will leave this open to remember setting up a disclaimer for V4 stable release because I'm sure this might bug some users.

**Comment by andersk** [comment]
Agreed that matching the native behavior is as desired but the difference from v3 should be documented.

**Comment by Grsmto** [comment]
https://github.com/Grsmto/simplebar/releases/tag/simplebar%404.0.0
