### ISSUE TITLE
Add styled-components (and other css-in-js libs) support

### ISSUE THREAD

**Issue by gevgeny** [Grsmto/simplebar#319]
## ✨ Feature Request
A lot of React projects use css-in-js approach and import of .css files may be not available because webpack style and CSS loaders are not plugged.  This makes loading simplebar styles problematic. I think it can be easily fixed by adding copy of styles in js file:

####  simplebar-react/styles.js 
```js
export default `
 // styles here
`;
```

That way it can be easily loaded in project with styled-components:

#### Root.jsx
```js
import { createGlobalStyle } from 'styled-components';
import simplebarStyles from 'simplebar-react/styles';

const GlobalStyle = createGlobalStyle`
  ${simplebarStyles}
`;

const Root = () => (
  <>
    <GlobalStyle />
    <MyComponent />
  </>
)
```

**Comment by Grsmto** [comment]
I chose to provide the CSS as .css file as it's the most standard way.

However it's true that the core CSS could be included in the JS and only the theming could be provided as a separate file as I don't see a case where you would not want the core CSS included at all (cause the plugin would not work anyway).
But I don't think this is possible in an elegant way, maybe just using inline styles would work, not sure.

**Comment by Grsmto** [comment]
After thinking about it, I think I don't want to choose a CSS-in-JS technology as it will always make things complicated in some contexts.
If I add styles inline, it will make things harder to override if needed (user often hack around, as this plugin is a hack at its core anyway).

From my experience, most of the popular tools in the React space support raw CSS imports: Gatsby, CRA, Next.js, ...
So I think the more versatile is still raw CSS for this. So I will close for now. I'm happy to discuss tho if there is a better solution.
