### ISSUE TITLE
not work on dynamic content

### ISSUE THREAD

**Issue by orlandolabz** [Grsmto/simplebar#321]
i think this code will tell what the issue i mean, 
note : it works normal if default content is alr overflow

<script>
        const simpleBar = new SimpleBar(document.getElementById('myElement'));
        document.addEventListener('click', e => {
            simpleBar.recalculate();
            document.getElementById('myElement').insertAdjacentHTML('beforeend', `<p>Lorem ipsum dolor, sit amet
                consecteturadipisicing elit. Ullam, quo!</p>`)
        })
    </script>

**Comment by Grsmto** [comment]
You can't just add the content to the original element because it's now replaced with SimpleBar code.
You have to do like explained [in the doc](https://github.com/Grsmto/simplebar#add-content-dynamically):
```
const simpleBar = new SimpleBar(document.getElementById('myElement'));

document.addEventListener('click', e => { 
simpleBar.getContentElement().insertAdjacentHTML('beforeend', `
Lorem ipsum dolor, sit amet consecteturadipisicing elit. Ullam, quo!
`)
});
```
