### ISSUE TITLE
1px gaps due to imprecise scrollbar width calculation at non-default zoom levels

### ISSUE THREAD

**Issue by andersk** [Grsmto/simplebar#325]
## Current Behavior

To compute the width of a scrollbar, SimpleBar uses the `scrollbarwidth` library, which takes `offsetWidth - clientWidth` of a `div` with a scrollbar. Since `offsetWidth` and `clientWidth` are rounded to integers and the scrollbar width isn’t always an integer at some non-default browser zoom levels, this sometimes results in weird one-pixel layout gaps.

This test case consists of red SimpleBar `div`s of random widths on a blue background. When rendered at certain zoom levels, white gaps are visible on the right edges of some or all of the red `div`s. Chrome at 200% is an especially bad case:

![screenshot](https://user-images.githubusercontent.com/26471/57964938-c5a6b880-78f1-11e9-84a9-a4f227af4479.png)

## Expected behavior

There should be no white gaps.

## Reproducible example

https://jsfiddle.net/anderskaseorg/bhoqt7kc/

## Suggested solution(s)

I sent a fix upstream to felixexter/scrollbarWidth#2, but I’m not sure if the maintainer is active, so we may want to pull in the fixed `scrollbarWidth` function ourselves.

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 4.0.0-alpha.9
| Browser          | Chrome 75
| Operating System | Ubuntu 19.04

**Comment by andersk** [comment]
This may be the cause of #303.

**Comment by Grsmto** [comment]
Should be fixed in 4.1.0

**Comment by gavin-murphy** [comment]
We're experiencing this issue on horizontal scroll bar in Chrome and MS Edge using latest 4.1.0

Edge appears to show approx 2 pixels of the native scroll bar.
Chrome 1px.
