### ISSUE TITLE
Replace node mutation by WeakMap

### ISSUE THREAD

**Issue by Grsmto** [Grsmto/simplebar#326]
As discussed [there](https://github.com/Grsmto/simplebar/issues/313#issuecomment-489260361) it would be better to use a `WeakMap` to keep track of SimpleBar instances instead of mutating the nodes elements.

We also need to add a static helper to retrieve the SimpleBar instance (that will now sits at `SimpleBar.instances.get(el)`).

cc @andersk

**Comment by andersk** [comment]
Sounds good to me. Let's give the static helper a short name since `Simplebar.instances.get(el).getScrollElement()` is quite a mouthful. Maybe `SimpleBar.of`?

**Comment by Grsmto** [comment]
Yeah definitely.
I liked the `SimpleBar.ofElement` that you proposed before. Makes it clear what type of parameter it's expecting.

**Comment by andersk** [comment]
`ofElement` is more explicit, but I’m trying to imagine typical use cases like

```js
SimpleBar.ofElement(document.getElementById("pane")).getScrollElement().addEventListener("scroll", () => {
    …
})
```

and wondering whether the extra word is actually worth the extra horizontal space, when there’s not really anything else that you could take the SimpleBar of. Your call though.
