### ISSUE TITLE
How to deactivate and then reactivate (for responsive applications)?

### ISSUE THREAD

**Issue by stratboy** [Grsmto/simplebar#329]
Hi, this is not a bug, just asking how to do one thing.

I need the scrollbar for desktop breakpoints, but I son't need it for mobile breakpoints, since we will use a different method to scroll the content.

I see we can use `SimpleBar.removeObserver();` to deactivate it (am I right?). But then? What if I want to reactivate it later? :)

**Comment by Grsmto** [comment]
Hi @stratboy 
You can't do this with SimpleBar.
But you probably shouldn't/don't need to do this: your user can't go from mobile to desktop from the same page instance, without changing device. So what you should do instead is **only init SimpleBar from a certain breakpoint**.
To do this you can use the native [MatchMedia API](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) that lets you use CSS media queries in JS.
Hope this help. Don't hesitate to answer with some code solution if you figured out, to help the others.

**Comment by decimoseptimo** [comment]
In react, this will do for interactive detection. I think it's useful for desktops when window is minimized.

```js
const Layout = ({ children }) => {

  useEffect(() => {
    const mql = window.matchMedia("(min-width: 1025px)")
    const listener = () => {
      console.log(mql.matches)
    }
    mql.addEventListener("change", listener)

    return () => {
      mql.removeEventListener("change", listener)
    }
  }, [])

  return (<>...</>)
}
```
