### ISSUE TITLE
Different behavior between Firefox and Chrome

### ISSUE THREAD

**Issue by Kidel** [Grsmto/simplebar#330]
**Describe the bug**
Different behavior between firefox and chrome. Setting the height to a fixed value solves the issue with firefox but I can't really do it. Using Angular 7

![IMG_20190524_182436_149](https://user-images.githubusercontent.com/3390842/58342726-76143f80-7e51-11e9-9ad1-df26eeffbcd6.jpg)

![IMG_20190524_182433_889](https://user-images.githubusercontent.com/3390842/58342736-7c0a2080-7e51-11e9-9b9b-51a88ec8014f.jpg)

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 4.0.0
| Browser          | firefox
| npm/Yarn         | npm
| Operating System | any

**Comment by Grsmto** [comment]
You would need to provide an example because this can be happening cause of your CSS code.
Obviously we have tested the plugin in both Chrome and Firefox and [they behave the same on our examples page](http://grsmto.github.io/simplebar/examples).

**Comment by Grsmto** [comment]
Closing this as it's pretty old. Please re-open a new issue related to the latest version if needed! Thanks.
