### ISSUE TITLE
How to scroll an element to the left?

### ISSUE THREAD

**Issue by kickthemooon** [Grsmto/simplebar#334]
I have ul element that is scrolling horizontally.
On page load the ul starts at scrollLeft 0,
so it starts with the left most li items inside.

I would like it to scroll to the left,
so the li items start with right most elements.

I saw that there is a "direction rtl" example on the demo page. but i dont know how to set it up.

Any ideas on how to achieve this?

**Comment by Grsmto** [comment]
Hi,
```
var el = new SimpleBar(document.getElementById('myElement'))
var scrollEl = el.getScrollElement()
scrollEl.scrollLeft = scrollEl.scrollWidth()
```
