### ISSUE TITLE
simplebar-placeholder is still broken in latest alpha

### ISSUE THREAD

**Issue by mmase** [Grsmto/simplebar#339]
**Describe the bug**
In responsive flexbox grids, when the browser is resized, the simplebar-placeholder grows in width and the element responds as expected. However, whenever the browser is _reduced_ in width, the simplebar-placeholder element width remains unchanged, resulting in a non-responsive website.

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 4.0.0-alpha.0
| Browser          | Chrome
| npm/Yarn         | npm
| Operating System | os x

**Comment by Grsmto** [comment]
Should be fixed in 4.0.1

**Comment by jamilabreu** [comment]
@Grsmto I'm seeing this is broken again (when reducing window width). Tried a few things without success - any ideas? 🧐
