### ISSUE TITLE
Multiple core-js modules not found in gatsby 2

### ISSUE THREAD

**Issue by decimoseptimo** [Grsmto/simplebar#345]
In a [gatsby 2 default starter](https://github.com/gatsbyjs/gatsby-starter-default), either simplebar or react-simplebar throw
```
These dependencies were not found:
⠀
* core-js/modules/es.array.filter in ./node_modules/simplebar/dist/simplebar.esm.js
* core-js/modules/es.array.for-each in ./node_modules/simplebar/dist/simplebar.esm.js
* core-js/modules/es.array.reduce in ./node_modules/simplebar/dist/simplebar.esm.js
* core-js/modules/es.function.name in ./node_modules/simplebar/dist/simplebar.esm.js
* core-js/modules/es.object.assign in ./node_modules/simplebar/dist/simplebar.esm.js
* core-js/modules/es.parse-int in ./node_modules/simplebar/dist/simplebar.esm.js
* core-js/modules/es.regexp.exec in ./node_modules/simplebar/dist/simplebar.esm.js
* core-js/modules/es.string.match in ./node_modules/simplebar/dist/simplebar.esm.js
* core-js/modules/es.string.replace in ./node_modules/simplebar/dist/simplebar.esm.js
* core-js/modules/web.dom-collections.for-each in ./node_modules/simplebar/dist/simplebar.esm.js
```

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 4.1.0
| Browser          | chrome 75
| npm/Yarn         | npm 5.6.0
| Operating System | win 10

**Comment by Grsmto** [comment]
ref https://github.com/gatsbyjs/gatsby/issues/15601

**Comment by Grsmto** [comment]
As a temporary work around and until Gatsby upgrade to core-js v3, I released a version of the package built with core-js 2:

`simplebar@4.2.3-corejs2`
`simplebar-vue@1.2.3-corejs2`
`simplebar-react@1.2.3-corejs2`

**Comment by yurii-tk** [comment]
@Grsmto could you please also update simplebar-angular as well, as I`m constantly facing the issue with dependencies were not found
Thanks in advance!

**Comment by decimoseptimo** [comment]
@Grsmto given that gatsbyjs/gatsby#15601 is closed, do you think it would be safe to assume this is solved?

**Comment by barbalex** [comment]
I use this in up to date gatsby projects and it works well for me

**Comment by Grsmto** [comment]
This should be solved now since we don't ship with core-js anymore.
