### ISSUE TITLE
Vertical  Scroll on left on RTL direction.

### ISSUE THREAD

**Issue by iamebadi** [Grsmto/simplebar#356]
Hi Adrien Denat,
I want a feature for RTL languages.
in the RTL direction, the vertical scrollbar must be on left.
I don't see this feature on your code.

please help me.
Thanks.

**Comment by iamebadi** [comment]
> mode

eectiionn

**Comment by Deroswent** [comment]
Hello. Yes, it works, but it also changes the direction of the text to RTL in div. 

I haven't found in the documentation how to place the scroll bar on the left, while leaving the LTR text. Is this even possible?

Thanks in advance for your reply.
