### ISSUE TITLE
Content is selected when dragging track

### ISSUE THREAD

**Issue by Demivan** [Grsmto/simplebar#357]
**Describe the bug**
After listeners were made passive content is now selected when scrolling by dragging track.
And there is warning in the log:
```
Ignoring ‘preventDefault()’ call on event of type ‘click’ from a listener registered as ‘passive’.
```

**To Reproduce**
1. Go to https://grsmto.github.io/simplebar/
2. Scroll by dragging vertical track
3. Content is selected

**Expected behavior**
Content should not be selected when dragging track.

**Reproducible example**
https://grsmto.github.io/simplebar/

**Additional context**
There is `preventDefault` that fixes content being selected, but it is now ignored as listeners are passive.
I think most of the listeners can be made passive but not all of them.

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | v4.2.0
| Browser          | Firefox
| npm/Yarn         | n/a
| Operating System | Arch

**Comment by Grsmto** [comment]
I noticed the error but I can't reproduce the issue. I'm testing on Chrome latest/mac osx.

**Comment by Demivan** [comment]
My bad, it is working in Chrome right now. But content is selected in Firefox

**Comment by Grsmto** [comment]
Actually I see that content underlying is clickable (so you can highlight text on double click). But it doesn't select it on drag.

**Comment by Demivan** [comment]
Maybe it is possible to add `user-select: none;` to content when dragging and just remove `preventDefault`.

**Comment by Grsmto** [comment]
@Demivan no because you'll still be able to click for example a clickable element under the track.

**Comment by Demivan** [comment]
And what about `pointer-events: none` or is it a bit overkill? It will disable all pointer events on content so clicks will be prevented. But it will prevent hover on content too, not sure if it is an issue

**Comment by Grsmto** [comment]
Excellent idea. Actually I couldn't find another solution so I just did that. Seems to be working fine.
