### ISSUE TITLE
npm dist package

### ISSUE THREAD

**Issue by exteon** [Grsmto/simplebar#362]
We want to install simplebar via `npm` but we are only interested in the compiled (dist) files. Installing simplebar drags in `lodash`, `core-js` dependencies. Could you publish a `-dist` package for those who want to just use the plain-ole full js library?

**Comment by Grsmto** [comment]
Hi,

I'm not sure to understand exactly what you need. You want the source code only, without any dependency, and minified?
Because if you install on npm there is a `dist` folder with all the compiled versions (esm, commonjs, but with dependencies).

**Comment by exteon** [comment]
Hi, that's correct, we only use the contents of the dist folder. However, we use the npm package for easy dependency management. But the npm package lists and pulls all the other dependencies, which we will never use because we won't rebuild it, we just need to use it in a web context. I have noticed for other packages in the same situation that they have a `-dist` package which contains just the full compiled extension and no (or as few as possible for deployment) external deps, for web deployment.

**Comment by Grsmto** [comment]
So your problem is just the size of your `node_modules` folder? Because the dependencies are required for the ESM version of the plugin to be compiled by module bundlers.
I wonder this would be solved if the dependencies were defined as `devDependencies` instead of `dependencies`.

**Comment by exteon** [comment]
Yes; I did see the package is using ESM semantics and is webpack ready, so it would be a pity to not leave it `npm` and `webpack`-ready and confine actual `npm` and `webpack` users to using the dev pack. It's just our use case that we don't actually build the `npm` project, we just use `npm` for dep management. So I don't think it's a good idea, that's probably why I see `-dist` packages from others.

**Comment by Grsmto** [comment]
Hey,
I'm gonna close this as it's not up to SimpleBar to provide a solution for this. I would suggest to create a script to delete any npm package that is not a direct dependency: that should be fairly easy to parse your package.json file `dependency` key and just filter out any folder within `node-modules` that isn't there, before you deploy your website!
Good luck.
