### ISSUE TITLE
Start Scrow on Bottom

### ISSUE THREAD

**Issue by murilolivorato** [Grsmto/simplebar#364]
Hello , I wold like to know how can I start the scrow on bottom .
like this -
![screenscrow](https://user-images.githubusercontent.com/19832238/64548196-87039680-d304-11e9-93a9-29aa3c2932dd.gif)

**Comment by murilolivorato** [comment]
some one can help me please ? I need help .

**Comment by Grsmto** [comment]
Hi Murilo,

I don't think what you are trying to do is related to SimpleBar but I will try to help you (you would have the same problem without SimpleBar).
The way to do this is to scroll the container to the very bottom after initialisation.


Try this:
```js
const simpleBar = new SimpleBar(document.getElementById('myElement'));
const scrollEl = simpleBar.getScrollElement();
scrollEl.scrollTop = scrollEl.scrollHeight;
```

**Comment by murilolivorato** [comment]
It gave the folowing error - 
```
 SimpleBar is not defined
````

**Comment by Grsmto** [comment]
Well if you have this it's because you're not loading the plugin script properly I suppose.
I will close this issue because this is not related to a problem is SimpleBar itself.
Hope you found your solution.
