### ISSUE TITLE
Native scrollbar showing up in addition to simplebar

### ISSUE THREAD

**Issue by buesing** [Grsmto/simplebar#367]
**Describe the bug**
Using the latest simplebar, on Win + Mac FF/Chrome I'm still seeing the native scrollbar, in addition to simplebar. I tried various solutions from https://github.com/Grsmto/simplebar/issues/73, nothing worked. There is no padding or other CSS properties on the host element, only a height. See codepen link below.

**To Reproduce**
Open https://codepen.io/moriz/pen/eYOPddv
Mouse over the element and scroll, notice native scrollbar showing up

**Expected behavior**
Only the simplebar should show

**Reproducible example**
https://codepen.io/moriz/pen/eYOPddv

**Comment by Grsmto** [comment]
Hey,
Could you provide the "Your environment" part of the issue reporter template?
I tested your example on Mac FF/Chrome and I'm not seeing the issue.
Thanks.

**Comment by buesing** [comment]
Haha, sorry my bad, I styled the simplebar with a background and didn't realize it was using a ::before element, what I was seeing was actually the simplebar, not the native one. Thanks!

**Comment by Grsmto** [comment]
Ahah okay, great that you solved your issue!
