### ISSUE TITLE
SCRIPT438: Object doesn't support property or method 'matches' simplebar.esm.js (814,1)

### ISSUE THREAD

**Issue by manu1222** [Grsmto/simplebar#368]
**Describe the bug**
While implemeting react-select with simplebar-react as per code below, https://codesandbox.io/s/simplebar-reactselect-gwgpu

It is throwing IE console errors and scrollbar is not working as it is working in Chrome.

**Reproducible example**
https://codesandbox.io/s/simplebar-reactselect-gwgpu

**Console errors**
SCRIPT438: Object doesn't support property or method 'matches' simplebar.esm.js (814,1)
SCRIPT5009: 'Promise' is undefined index.js (1603,1)
SCRIPT5007: Unable to get property 'disconnect' of undefined or null reference simplebar.esm.js (773,1)

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 1.2.1
| Browser          | IE 11
| npm/Yarn         | npm
| Operating System | Windows

**Comment by manu1222** [comment]
I found the solution, add below code:

if (!Element.prototype.matches) {
    Element.prototype.matches =
      Element.prototype.msMatchesSelector ||
      Element.prototype.webkitMatchesSelector;
}

Reference URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/matches#Polyfill

**Comment by Grsmto** [comment]
Actually this is valid issue and this should be fixes. I will re-open.
Thanks.
