### ISSUE TITLE
[react] add support for forwardRef

### ISSUE THREAD

**Issue by SaraVieira** [Grsmto/simplebar#369]
## 🔎 Usage Questions

I am using the react warpper for simplebar and everything seems to work great but I am trying to get how much the user has scrolled and I tried the following:

```js

export const ScrollableContent = ({ children }) => {
  const simplebar = useRef(null);

  useEffect(() => {
    if (simplebar.current) {
      simplebar.current
        .getScrollElement()
        .addEventListener('scroll', e => console.log(e));
    }
  }, [simplebar]);

  return (
    <>
      <ScrollBarCSS />
      <ScrollWrapper>
        <Content>
          <SimpleBar
            ref={simplebar}
          >
            {children}
          </SimpleBar>
        </Content>
      </ScrollWrapper>
    </>
  );
};

```

But it doesn't seem to work and I don't ever get a current in my ref

Does anyone have any ideas?

**Comment by Grsmto** [comment]
Hey Sara,

Yeah actually we don't use `forwardRef` so it prob doesn't work as you would expect (actually you're absolutely right in your code and that should definitely return the SimpleBar instance!).
You can probably solve your issue using the `scrollableNodeProps` prop:

```js
<SimpleBar
    scrollableNodeProps={{ ref: scrollableElRef }}
>
...
```

What you would get here is a ref to the DOM element directly (what `getScrollElement()` returns), so you won't have to do `getScrollElement`. You can directly attach the listener to it in theory.

I realise that the React plugin (and actually Vue and Angular ones as well) don't have any documentation yet. I'll put the `forwardRef` and documentation as high priority.

Thanks for your report!

**Comment by SaraVieira** [comment]
Hey!

What you said works perfectly and its a closed one for me unless you wanna keep it open :)

I have been playing arround with adding the ref support and landed in this:

```
import React from 'react';
import 'simplebar';

const SimpleBar = React.forwardRef((props, ref) => {
  const { children, scrollableNodeProps, classNames = {}, ...options } = props;
  return (
    <div data-simplebar {...options}>
      <div className="simplebar-wrapper">
        <div className="simplebar-height-auto-observer-wrapper">
          <div className="simplebar-height-auto-observer" />
        </div>
        <div className="simplebar-mask">
          <div className="simplebar-offset">
            <div
              {...scrollableNodeProps}
              className={`simplebar-content-wrapper${
                scrollableNodeProps && scrollableNodeProps.className
                  ? ` ${scrollableNodeProps.className}`
                  : ''
              }`}
            >
              <div
                ref={ref}
                className={classNames.content || 'simplebar-content'}
              >
                {children}
              </div>
            </div>
          </div>
        </div>
        <div className="simplebar-placeholder" />
      </div>
      <div
        className={`${classNames.track ||
          'simplebar-track'} simplebar-horizontal`}
      >
        <div className={classNames.scrollbar || 'simplebar-scrollbar'} />
      </div>
      <div
        className={`${classNames.track ||
          'simplebar-track'} simplebar-vertical`}
      >
        <div className={classNames.scrollbar || 'simplebar-scrollbar'} />
      </div>
    </div>
  );
});

export default SimpleBar;
```

For it to work with the scroll the ref needs to be passed into the content

Does that make sense for you?

**Comment by Grsmto** [comment]
So to do what you wanted to do, you needed access to the scrollable node (`simplebar-content-wrapper`) or the content node (`simplebar-content`)?
I suppose your example is good and passing the `ref` prop should return `simplebar-content` that would makes sense.

**Comment by SaraVieira** [comment]
I think this works very well, i tried and I did get the ref back, want me to make a pr?

**Comment by Grsmto** [comment]
If you want to do a PR you can but please base it on the `next`. The source code might be slightly different from this one as we reworked the react plugin since that.

**Comment by Grsmto** [comment]
Hey @SaraVieira I ended up implementing this directly, thanks again for your help.

**Comment by aannaassalam** [comment]
Hey @Grsmto 

I am facing following problem with forwardRef and typescript.

![image](https://github.com/Grsmto/simplebar/assets/54815094/03be1955-f122-459a-8aab-f6526e4b3f1a)


and this is my code could you please help me with his?

`type ScrollbarProps = Omit<BoxProps, "color">;

const Scrollbar = forwardRef(
  ({ children, sx, ...other }: ScrollbarProps, ref) => {
    const userAgent =
      typeof navigator === "undefined" ? "SSR" : navigator.userAgent;

    const mobile =
      /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
        userAgent
      );

    if (mobile) {
      return (
        <Box ref={ref} sx={{ overflow: "auto", ...sx }} {...other}>
          {children}
        </Box>
      );
    }

    return (
      <StyledRootScrollbar>
        <SimpleBar
          scrollableNodeProps={{
            ref: ref
          }}
          clickOnTrack={false}
          {...other}
        >
          {children}
        </SimpleBar>
      </StyledRootScrollbar>
    )
  }
);
export default memo(Scrollbar);
`
