### ISSUE TITLE
Add documentation for framework plugins

### ISSUE THREAD

**Issue by Grsmto** [Grsmto/simplebar#370]
Currently the plugins README are just aliasing to the main vanilla-js README.
There should be specific documentation for each Vue, Angular and React plugins.

**Comment by matadorhernan** [comment]
> Currently the plugins README are just aliasing to the main vanilla-js README.
> There should be specific documentation for each Vue, Angular and React plugins.

Hey i can do that

**Comment by Grsmto** [comment]
Done.
