### ISSUE TITLE
Opportunity to save kb and improve performances

### ISSUE THREAD

**Issue by Grsmto** [Grsmto/simplebar#372]
1. The framework plugins don't need the HTML API, so we could provide a second bundle that gets rid of the global mutation observer and everything that comes with it.
From my tests we could save about 5kb of script with this, plus one less mutation observer that could improve performances especially in a JS app scenario.

SimpleBar with HTML API: 949 lines
SimpleBar without HTML API: 819 lines

2. `resizeObserver` is now supported on most modern browser so we should probably not include the polyfill by default anymore https://caniuse.com/#feat=resizeobserver 
Edit: actually iOS Safari still doesn't include it so we might keep it anyway.

3. We should group DOM read and write (like what fastDOM is doing) to reduce layout trashing

**Comment by Grsmto** [comment]
Following up on discussion in #391, should we remove `resize-observer-polyfill` from the bundle and let users install it themselves?

**Comment by unindented** [comment]
@Grsmto I'd be 100% in favor. My app already conditionally polyfills `ResizeObserver` (so Chrome and Firefox users don't have to download it for example), so by including `simplebar` I'm undoing that optimization.

**Comment by Grsmto** [comment]
It makes sense and I agree as well with that statement.
Will definitely work on that for the next release. It's a shame this came up right after the breaking 5.0 release! x)

**Comment by Grsmto** [comment]
So I really quickly tried to remove `resize-observer-polyfill`, the problem is that it's not anymore a polyfill but a ponyfill, so I'm not sure how that would work for the users as I suppose they would have to apply the ponyfill to window.resizeObserver before SimpleBar init:

```
import ResizeObserver from 'resize-observer-polyfill';
import 'simplebar';
import 'simplebar/dist/simplebar.css';

window.ResizeObserver = ResizeObserver;
```

This definitely makes usage more complex. I also had in mind to just have 2 bundles in the main package: one with (that would basically do what I just wrote above) and one without the polyfill. It would keep the default import with polyfill and also we would avoid the major release breaking change.

Something like:
```
import 'simplebar/dist/simplebar-no-polyfills.esm';
```

So for advanced users they can optionally get rid of the polyfills if necessary. Not sure it's something that would make sense...What do you think?

**Comment by unindented** [comment]
Having two bundles would solve the issue for me. The only thing is that it complicates your build and release process a bit...

**Comment by hc-codersatlas** [comment]
For saving kb why not optimize lodash too? See: https://github.com/fkhadra/react-on-screen/issues/55 for example

**Comment by nathggns** [comment]
Has there any progress on this?

**Comment by Grsmto** [comment]
There is!

I released a new beta version: `simplebar@6.0.0-beta.1 `. I didn't advertise it cause I need to write changelog and everything but I'll do a sum up here, as most suggestions in this issue were applied:

- Remove `resize-observer-polyfill` entirely from the dependencies. 
I didn't find an easy solution to "have it by default" and let advanced users remove it if needed, so let's just get rid of it. I totally agree that it should be lightweight by default.
- Move to `lodash-es` instead of importing the `lodash/function-name` version since we were very likely importing twice the same helper functions (thanks @hc-codersatlas)
- As suggested in my initial comment, the HTML API is now separated. That saves us a few kb.

**Comment by hakimio** [comment]
@Grsmto Any idea when `simplebar@6.0.0-beta.2` and `simplebar-angular@3.0.0-beta.2` will be published to npm?

**Comment by gitcatrat** [comment]
@Grsmto Is this a false size raport? https://bundlephobia.com/result?p=simplebar@6.0.0-beta.7

**Comment by Grsmto** [comment]
@gitcatrat yes I think so.

It seems like the Lodash functions are taking a lot of kb. Especially `memoize` I need to do some test, maybe we don't need it.

**Comment by gitcatrat** [comment]
Do you even need memoize? It seems to be only used for caching RTL helper result. I suggest to cache it manually.

**Comment by Grsmto** [comment]
This is finally done. The bundle size has been divided by 3 for `simplebar-react` for example: https://bundlephobia.com/package/simplebar-react@3.2.0

There is obviously more room for improvements but we'll see that in another issue! Thanks all.
