### ISSUE TITLE
Add CSS class when scrollbar is visible

### ISSUE THREAD

**Issue by aeslinger0** [Grsmto/simplebar#376]
Would it be possible to get a CSS class added whenever the content is large enough to require a scrollbar? This would allow me to style the content conditionally based on whether there is a scrollbar or not.

Some background on why I want to do this: I'm using the Angular Material Drag and Drop CDK to allow users to drag cards to different columns (like Trello). However, the simplebar appears _over_ the cards instead of squishing the cards to the left to make room for the scrollbar. Maybe this is a bug or maybe that's how simplebar is supposed to work, I don't know. But if there was a CSS class that was only applied when the scroll bar was present, then I could add a conditional margin on the cards to compensate.

**Comment by Grsmto** [comment]
Hey,
See #349 someone else already asked for this, I provided a potential workaround.
I understand why you need this, at the moment SimpleBar was mainly built for "floating" usage but I see some people are using it only to customise the scrollbar and keep it with the same behaviour.
I will keep this open and see if we can keep this into consideration for future versions.

**Comment by rayleigh3** [comment]
+1

**Comment by scarcoco** [comment]
+1

**Comment by Grsmto** [comment]
That's on my todo for a very very long time.
Marking #260 as it's a similar request. FYI this should be really easy to implement and is a #goodfirstissue for sure.

**Comment by Grsmto** [comment]
Done in latest version!
