### ISSUE TITLE
Two scrolls are visible, native and simplebar.

### ISSUE THREAD

**Issue by muziol** [Grsmto/simplebar#378]
**Bug**
Two scrolls are visible. You can check it in this example: [stackblitz](https://stackblitz.com/edit/simplebar-angular-demo-oem9po)

**Versions**
`
"simplebar": "^4.3.0-alpha.1",
"simplebar-angular": "^0.1.0",
`

**Comment by muziol** [comment]
It's solved my problem when I changed version to 4.2.3, but everyone who try install this package will get alpha version.

**Comment by Grsmto** [comment]
Thanks for the head up, you are right it shouldn't install the alpha version by default, I wasn't aware it was the case!

**Comment by Grsmto** [comment]
Rolled back to 4.2.3 by default. Closing. Thanks.

**Comment by qiurenbo** [comment]
@Grsmto I have set up an npm org and invite you to be the owner of simplebar-angular. Now you have the write access to simplebar-angular too~
