### ISSUE TITLE
[doc] Deprecation of data- attributes

### ISSUE THREAD

**Issue by strarsis** [Grsmto/simplebar#379]
In release notes, it is stated that `data-` attributes have been deprecated in favour of "React"-style attributes. However, this doesn't apply to the `data-simplebar` attribute that is required to apply simplebar on a specific element, just `simplebar` doesn't work.

**Comment by Grsmto** [comment]
Hi,
It's only for the `simplebar-react` package. It does not apply to the main SimpleBar library. It's only if you use React.

**Comment by strarsis** [comment]
@Grsmto: OK, would it make sense to make this more clear in the docs of the other packages?
