### ISSUE TITLE
Scroll to anchor doesn't work

### ISSUE THREAD

**Issue by ivanceban** [Grsmto/simplebar#38]
Hi Adrien,
Is there any way to scroll to anchor when the page is loaded? I tried this:
function scrollToAnchor(anchor){
        var aTag = $(anchor);
        $('html,body').animate({scrollTop: aTag.offset().top},'slow');
    }
$('button').on('click', function () {
        scrollToAnchor("#my_anchor");
 });

and it works only with default scrollbar. When Simplebar is active, this method doesn't work. 

I tried this: 
$('html,body, .simplebar').animate({scrollTop: aTag.offset().top - 200},'slow');
and this:
$('.simplebar').animate({scrollTop: aTag.offset().top - 200},'slow');
still nothing...

**Comment by Grsmto** [comment]
Hey @ivanceban you should probably take a look at the "stress test" demo where I'm doing something really similar: https://github.com/Grsmto/simplebar/blob/master/demo/stress-test.html
I hope this will help!
If you encounter a bug, please re-open ;)

**Comment by ivanceban** [comment]
Yes it helped. Thanks a lot!
