### ISSUE TITLE
Simplebar doesn't create instance again after clearing html inside host element.

### ISSUE THREAD

**Issue by Yauheni-Butski** [Grsmto/simplebar#381]
**Describe the bug**
Simplebar doesn't create instance again after clearing html inside a host element. It's look like he have some mechanism like-hash and check that element already should have scrollbar and doesn't create needed html for the second time.

**To Reproduce**
1. Add Simplebar to some element. 
var scroll = new SimpleBar($(".my-div")[0]);
(after that you can see that host element ".my-div" have attribute "data-simplebar=init" and needed html inside)

2. Clear all that inside this element.
$(".details-content").empty();

3. Try to add simpleBar to this element again
var scroll = new SimpleBar($(".my-div")[0]);

4. See that ".my-div" element have no entire html.

**Expected behavior**
Element should have entire html that needed for SimpleBar again.

**Additional info**
I use Simplebar with select2.js for replacing custom scrollbar in dropdown result. And some select2.js mechanism clearing host element after updating content. So, I don't want to change this logic and if you can point me how to re-create SimpleBar for the same element it would be great!

**Comment by Grsmto** [comment]
@Yauheni-Butski Hi, thanks for your report.
So I'm not sure this is a bug, since to "clear" SimpleBar in theory you should call the `unMount` function and not just remove the content. I'm not surprised this breaks the plugin.

Maybe what you could do here is try to call `unMount()` before initialization. You could try something like:

```js
if (scroll) {
  scroll.unMount();
}

scroll = new SimpleBar($(".my-div")[0]);
```

**Comment by Yauheni-Butski** [comment]
@Grsmto , yes, I think that this is what I need. Sorry, didnt find this moment in documentation.
