### ISSUE TITLE
Horizontal scrollbar won't move

### ISSUE THREAD

**Issue by peterwesterlund** [Grsmto/simplebar#382]
**Describe the bug**
Horizontal scrollbar won't move. Vertical is.

**Reproducible example**
https://jsfiddle.net/PeterWesterlund/bgyphzf3/16/

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        |  v4.3.0-alpha.1
| Browser          | Chromium Version 75.0.3753.0
| npm/Yarn         |
| Operating System | macOS Catalina 10.15

**Comment by Mushr0000m** [comment]
I have the exact same issue, how did your fixed it ?

**Comment by Grsmto** [comment]
The previous jsfiddle was broken due to the CSS that was used. Here is an updated one working https://jsfiddle.net/Grsmto/zxc7barm/1/

hope that helps

**Comment by AllanOricil** [comment]
It does not work. Try moving the scrollbar with the mouse wheel. It simplify does not work. The user has to drag the scrolbar to see its content moving horizontally.

**Comment by ronaldohoch** [comment]
Didn't work to me too.

**Comment by lunule** [comment]
Just checked this in 2024, and @Grsmto 's demo works fine, both with _drag_ and with _click_.
