### ISSUE TITLE
Cannot find module 'simplebar-angular'

### ISSUE THREAD

**Issue by blueblazerchrist** [Grsmto/simplebar#385]
**Describe the bug**
Cannot find module 'simplebar-angular'

**Comment by CedBadarou** [comment]
I have the same issue, I followed the instruction with npm (simplebar and simplebar-angular), but the module is not found.

**Comment by blueblazerchrist** [comment]
install versions manually
"simplebar": "^ 4.2.3",
"simplebar-angular": "^ 0.1.0", and it works without problem

**Comment by Grsmto** [comment]
Thanks for the report, I'm on it.

**Comment by Grsmto** [comment]
Ok I struggled a lot but you should now be able to use the latest version 1.0.8!
Thanks for your reports!
