### ISSUE TITLE
incorrect file name for typescript definition file for simplebar-react

### ISSUE THREAD

**Issue by MichaelFroeschen** [Grsmto/simplebar#389]
**Describe the bug**
The typescript definition file for simplebar-react is currently incorrectly copied via a cp command renaming the file to simplebar-react.d.t instead of simplebar-react.d.ts

**To Reproduce**
See the dist folder of the package.

**Expected behavior**
Should be named simplebar-react.d.ts

**Comment by Grsmto** [comment]
It's released in `simplebar-react@2.0.4`. Thanks.
