### ISSUE TITLE
Is v2 available on NPM?

### ISSUE THREAD

**Issue by nkoterba** [Grsmto/simplebar#39]
I'd like to use simplebar in a project but it's very confusing as to where or how I can get version 2?

I'd rather download it from github *OR* NPM, but I believe NPM still has version one.  When I try:

`"simplebar": "github:Grsmto/simplebar.git#v2"` 

in my `package.json` this is all I get downloaded into my `node_modules` folder:
![image](https://cloud.githubusercontent.com/assets/2508944/19314392/f39a391c-9067-11e6-9c53-bb2290069ec7.png)

**Comment by Grsmto** [comment]
Hey, sorry should have document that properly.
You can by doing this: `npm install simplebar@2.0.0-beta.1 --save`

**Comment by Grsmto** [comment]
Actually you're right I think there is a problem with the way I published it on NPM.
I'll take a look at it tonight. Sorry about that!

**Comment by Grsmto** [comment]
So I had a check yesterday and it's gonna be a longer to fix than expected :o 
Hopefully I'll have it sorted tonight!
Sorry about that.

**Comment by nkoterba** [comment]
@Grsmto Thanks for the help!  It's not an immediate need.  We can just bring in the source files we want but I figured I would point it out.

**Comment by Grsmto** [comment]
@nkoterba hey! I just release the beta 2 that should fix this issue!
If you want to give it a try `npm install simplebar@2.0.0-beta.2`
