### ISSUE TITLE
window is not defined on SSR

### ISSUE THREAD

**Issue by muziol** [Grsmto/simplebar#390]
window is not defined - on SSR

simplebar version: 5.0.2
simplebar-angular version: 1.0.8

when i change to versions: 4.2.3 and 0.1.0 then are not installed

**Comment by Grsmto** [comment]
Awaiting change before merging PR to fix this in #388

**Comment by Grsmto** [comment]
It's released on `simplebar-angular@1.0.9`. Thanks.
