### ISSUE TITLE
Simplebar uses global `window`/`document` variables

### ISSUE THREAD

**Issue by jack-arms** [Grsmto/simplebar#394]
**Is your feature request related to a problem? Please describe.**
Because the library uses the global `window`/`document` variables (e.g. https://github.com/Grsmto/simplebar/blob/4a9b3828352b0111e30f2cc5dd8d5b5ea5057eeb/packages/simplebar/src/simplebar.js#L137), it's not really possible to use the library in another window/document. For example, if the HTML element needing the scrollbar is inside an `iframe` or inside a second window that has content rendered inside of it using React running in a first window (https://medium.com/hackernoon/using-a-react-16-portal-to-do-something-cool-2a2d627b0202). 

**Describe the solution you'd like**
Instead of using `window`/`document`, use `el.ownerDocument` and `el.ownerDocument.defaultView || el.ownerDocument.parentWindow`

**Comment by Grsmto** [comment]
Great stuff, I had no idea of this issue.

**Comment by jack-arms** [comment]
I made a fix for this on a branch on [my fork](https://github.com/jack-arms/simplebar/tree/fix-window-document-globals), main changes are in [this commit](https://github.com/jack-arms/simplebar/commit/553407f4278ebce75bafa822d839df7662375e43).

Basically this replaces instances of `window` and `document` with `el.ownerDocument.defaultView` and `el.ownerDocument`, respectively, whenever an element is available, and defaults to the global `window`, `document` objects otherwise. Thoughts and/or would you like me to submit a PR?

**Comment by Grsmto** [comment]
Hey Jack,

Yeah I would totally accept a PR for that. This looks like a totally reasonable solution.

**Comment by jack-arms** [comment]
That'd be awesome! I'll sanity check it a bit more and then make a PR.

**Comment by jack-arms** [comment]
Closed with #411

**Comment by gitcatrat** [comment]
Not a huge issue at all but window and document values could be cached (quickly counted ~10 unnecessary function calls) because they should always stay the same. You can't move DOM elements (i.e scrollbar DOM) between the documents and if you put some of your scrollbar elements outside the iframe and some inside, you're begging for trouble big time.
