### ISSUE TITLE
FF 52/53 bugs

### ISSUE THREAD

**Issue by Poloten** [Grsmto/simplebar#395]
![image](https://user-images.githubusercontent.com/29718766/67487578-dca6bf00-f676-11e9-8f08-a584dbae69d0.png)

It's a latest version Firefox on Windows XP...

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.0.3-corejs2
| Browser          | Firefox 53.0.3 (64-bit)

**Comment by dogzy123** [comment]
Same

**Comment by dogzy123** [comment]
@Poloten as a temporary solution you can downgrade simplebar to version "2.0.0-alpha.0"

**Comment by Grsmto** [comment]
Released a fix in latest version. Hope it helps.
