### ISSUE TITLE
Memory leak in simplebar-vue

### ISSUE THREAD

**Issue by JON418** [Grsmto/simplebar#397]
I'm not sure what is the root cause of it, but while checking for possible memory leaks in my Vue app I noticed the simplebar components never get destroyed, they just keep adding in the app when a page using the simplebar component gets visited twice or more.

I think there should be some cleanup of the instanciated simplebar in the `beforeDestroy()` hook in `simplebar-vue/index.vue`, however I'm not sure how it could be implemented.

**To Reproduce**
1. Setup a simplebar component in a Vue app and navigate to its page in a browser
2. In Chrome, open the console and look for the Memory tab. Take a snapshot and look for the simplebar module. There should be 1
3. Navigate away from this page (the simplebar component should have been destroyed at this moment)
4. Navigate back to the page with a simplebar component and take a new snapshot. There should be 2 now

I use simplebar-vue 1.3.1

**Comment by JON418** [comment]
willing to give a shot at a PR if necessary

**Comment by Grsmto** [comment]
Actually Vue plugin is using the basic SimpleBar that sets a MutationObserver that should look for SimpleBar instances and unmount them automatically so the `beforeDestroy` shouldn't even be needed...so that's weird.
There might be a bug in the core library then.

**Comment by Grsmto** [comment]
Thanks for your report, I think I fixed it and added a test for it. I will release a new version soon.

**Comment by Grsmto** [comment]
Release in `simplebar-vue@1.3.4`

**Comment by JON418** [comment]
wow that was quick! Just updated to 1.3.4 and the leak is gone. Much thanks, really nice library btw :)
