### ISSUE TITLE
Throttle recalculations (v2)

### ISSUE THREAD

**Issue by ineentho** [Grsmto/simplebar#40]
What are your thoughts on throttling recalculations triggered by the mutation observer? I have a element which triggers the recaluclation ~ 1000 times before it's done and it's of course killing the performance.

**Comment by Grsmto** [comment]
Definitely something needed. 
Also I think about letting the user disable the mutation observer if needed for scenarios where perfs matters more.

Can I ask what is your use case so I can understand better the kind of scenario where this could be needed?
Thanks for this

**Comment by ineentho** [comment]
Our use case is quite simple: We have a long scrollable list of items where items are added one by one through appendChild. Most are added at load time, but more are removed and added dynamically afterwards too.

Temporarily disabling the mutation observer while loading the initial batch of items would probably work great too.

**Comment by Grsmto** [comment]
Ok thanks very much for that. I'll try to setup a similar scenario so I can test it, seems like a quite common use case (infinite scroll...etc).
The calculation is reading height, scroll position and other stuff so I guess it can be quite performance heavy as well. Probably need some improvements. But I'm sure the debouncing should solve 99% of the issues!

**Comment by ineentho** [comment]
Thanks for the quick update! It works great now :)
