### ISSUE TITLE
"display" property missing in latest CSS(5.0.5)

### ISSUE THREAD

**Issue by Hlsgs** [Grsmto/simplebar#403]
Upon having issue with both Simplebar and normal scrollbar showing, I found that adding `display: flex;` to the target element fixed the issue.

I then dug though simplebar's CSS and found that the `[data-simplebar]` block, although having flex properties, is missing a `display: flex;` decalaration.

Is this a bug or am I missing something here?

**Comment by Grsmto** [comment]
It's not a bug. The properties are there in case your element is flex.
If you can replicate that bug with our [Codesandbox](https://codesandbox.io/s/simplebar-react-gwgyw) or [Jsfiddle](https://jsfiddle.net/Grsmto/57obe5w2/1/) that would be useful!
