### ISSUE TITLE
getScrollbarWidth crash in Firefox on Windows

### ISSUE THREAD

**Issue by luky1984** [Grsmto/simplebar#404]
In firefox (47.0.2 - latest) on windows it crashes when calling function getScrollbarWidth.

I manually checked in firefox console that this code:
getComputedStyle(document.body, '::-webkit-scrollbar').display throws the exception  "Component is not available".

getComputedStyle(document.body, '::-webkit-scrollbar') itself doesn't crash though.

Anyways the solution seem to wrap the content of function getScrollbarWidth with try catch and return 0 in the catch.

Btw Firefox on Mac OS works good.
Btw Firefox on windows seems to be only browser where is the problem.
Btw Update of Firefox to latest version 56.0 didn't help.

**Comment by luky1984** [comment]
I wanted modify the original code and use it, but i was unable to do it. (I use react + ts) so i fixed it with this hack

if (window.getComputedStyle) {
  var old = window.getComputedStyle;
  window.getComputedStyle = function(element: any, pseudoElt?: any) {
    var ret = old(element, pseudoElt) || {};
    if (pseudoElt == '::-webkit-scrollbar') {
      try {
        ret.display == 'none';
      }  catch (e) {
        return {display: 'block'};
      }
    }
    return ret;
  } as any
}

**Comment by Grsmto** [comment]
Seems like the same issue as #395.
Are you on Windows XP as well? Because latest version of FF is 70 not 56.

**Comment by Grsmto** [comment]
So it seems like the throw/catch is the best solution :/ I'll release a fix soon! Thanks for your report.

**Comment by Grsmto** [comment]
Released a fix in latest version. Hope it helps.

**Comment by luky1984** [comment]
i am not sure now but i guess windows 10
