### ISSUE TITLE
Overflow on <ngx-simplebar>

### ISSUE THREAD

**Issue by Alessandroinfo** [Grsmto/simplebar#405]
## 💬 Questions and Help

I need to put the property: `overflow: auto;` if I don't do that I can't see the custom scrollbar?

Why that?
I use the latest Angular version, tested on the latest Chrome version.

**Comment by Grsmto** [comment]
Hi,

I'm not sure why you need that, in theory it shouldn't be needed. could you have a look at the Angular Codesandbox and see if you can replicate the issue there? https://codesandbox.io/s/simplebar-angular-umx1k

Thanks
