### ISSUE TITLE
SimpleBar not functional inside initially hidden element (regression from 4.2.3)

### ISSUE THREAD

**Issue by andersk** [Grsmto/simplebar#406]
**Describe the bug**
In SimpleBar 4.3.0-alpha.1 and later, if you initialize a SimpleBar on something inside a `<div hidden>` container, and then later show the container, the SimpleBar is not functional (the scrollbar doesn’t show and you can’t scroll with the scroll wheel) until you force a recalculation by resizing it. This is a regression from SimpleBar 4.2.3, where it worked correctly.

**To Reproduce**
1. Go to https://jsfiddle.net/anderskaseorg/9f2zmhtq/
2. Click on the Show button.
3. Attempt to scroll the SimpleBar.

**Expected behavior**
SimpleBar should work.

**Reproducible example**
https://jsfiddle.net/anderskaseorg/9f2zmhtq/

**Additional context**

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.0.6
| Browser          | Firefox 70.0.1
| npm/Yarn         | N/A
| Operating System | Ubuntu 20.04

**Comment by NechiK** [comment]
Yes, I faced this issue as well. I updated simplebar to fix issue with initial loading and got another issue with hidden elements :(

**Comment by arrancardnell** [comment]
I am facing a similar issue with a SimpleBar inside some Bootstrap 3 tabs, except that the entire contents of the tab (not just the scrollbar) remains hidden. It can be fixed by either resizing the page or switching back and forth between the tabs.

**Comment by Grsmto** [comment]
Fixed in `simplebar@5.0.7`. Let me know if any issue.
