### ISSUE TITLE
Issue when container have display:flex 

### ISSUE THREAD

**Issue by Alessandroinfo** [Grsmto/simplebar#408]
**Describe the bug**
When I use simplebar inside a container flex the root of the component don't take the width of its parent I must set width: 100% to take all width.

**Reproducible example**
https://codesandbox.io/s/simplebar-angular-xq1yu

**Comment by Grsmto** [comment]
Yes the Angular plugin has a container that should not be there. I fixed it but that's changing the DOM structure so will probably require at least a minor version update.
Will release soon.

**Comment by Grsmto** [comment]
Can you test with the latest `simplebar-angular@2.0.0`?

**Comment by Alessandroinfo** [comment]
Yes i have updated the angular library at the version 2.0.0 and i retrieve this error:
`ERROR this.SimpleBar.destroy is not a function`

**Comment by Grsmto** [comment]
@Alessandroinfo thanks for the report, it was a typo. I fixed it and added a test case for this.
It's released on `simplebar-angular@2.0.1`.
