### ISSUE TITLE
v2 release date

### ISSUE THREAD

**Issue by scooterlord** [Grsmto/simplebar#41]
Hello there! 

I've been searching forever for a good scrollbar that works as it should in all kinds of devices! Thanks for this!

Do you have any plans on the release of v2? I can't make the beta version to work :/

**Comment by Grsmto** [comment]
Hi!
I'm just waiting for some feedbacks and people around me to test it and have it working successfully before actually releasing it (and maybe write some proper tests as well). So there is no specific date yet.

But what's your issue with the v2 beta?

**Comment by scooterlord** [comment]
..the source code is not defined as a usable plugin. Or am I doing something wrong?

**Comment by Grsmto** [comment]
Sorry I was away from my laptop for the last 2 weeks. 
How do you use the script? Do you import it as a `<script>` tag or do you import it with a module loader (like in Webpack or Require js environment?).
@scooterlord no on V1 it's not possible.

**Comment by scooterlord** [comment]
Hello, thanks for getting back to me.
I tried using it in a <script> tag, but what is currently up as v2 doesn't look like js... What is he procedure to...uhm...'compile' it (?) in javascript?

**Comment by Grsmto** [comment]
hey @scooterlord check the README there: https://github.com/Grsmto/simplebar/tree/v2.0.0-beta.3#installation

there is documentation on how to use the V2 with script tag. Sorry this is not very clear from the homepage I'll try to clarify.

**Comment by scooterlord** [comment]
Well, I just saw the link to the source code and never saw v2 github page. So In other words, you just use the script found online right? (https://unpkg.com/simplebar@2.0.0-beta.2/umd/simplebar.js) 

Is there any roadmap about finalizing this? We are about to release our project and have to either stick to v1 or advance to v2. Is is easy to clarify what is v2 missing at this point?

**Comment by Grsmto** [comment]
If it's working fine for you, you can you the V2. The only reason it's on "release candidate" state and not release yet is to warn people that they might find bugs and things not working as expected.
As the plugin is used and works for most of the usages, I will release it as stable (but it won't be any major change anyway, so it's fine to use the RC now!).

**Comment by scooterlord** [comment]
Cool, thanks for sharing!
