### ISSUE TITLE
It's possible to publish simplebar without core-js ?

### ISSUE THREAD

**Issue by Poloten** [Grsmto/simplebar#413]
1) Some project used core-js2 versions, simplebar default use core-js3.
2) Some project used babel options `{"useBuiltIns": "usage"} `with `"targets": {"browsers": []}` its implement only needed polyfills.

Thats cases is increased bundle size.

**Comment by Grsmto** [comment]
Hi,

It's already available `simplebar@5.0.5-corejs2`.

**Comment by Poloten** [comment]
> Hi,
> 
> It's already available `simplebar@5.0.5-corejs2`.

Yep, but 5.0.5 version has a bug in old Forefox.

**Comment by Grsmto** [comment]
Done in latest version.
