### ISSUE TITLE
Centering the content horizontally

### ISSUE THREAD

**Issue by sumanita** [Grsmto/simplebar#419]
Hi there, 
Great plugin and it works like a charm. I am trying to horizontally center the content whenever there is scrollbar but bit struggle to do so. Is there any example with that don't find in demo page. by the way i am using "data-simplebar". anything help will be highly appropriated. 

many thanks
Sumanita

**Comment by Grsmto** [comment]
Hi,

I don't really understand what you're trying to do. Could you explain a bit more?

**Comment by sumanita** [comment]
thanks for the quick response. I set the fixed width in this class  "horizontal-scrolling__wrapper" and whenever there is scrollbar my content align to left. I want to align content inside that div to center of it so whenever i land in scrollbar div content inside is always middle of it. hope it make sense :) thanks once again.

**Comment by NechiK** [comment]
@sumanita Probably you need to change styles for `simplebar__contant` inside your  `horizontal-scrolling__wrapper`
