### ISSUE TITLE
v2: Calling recalculate on a hidden scrollbar

### ISSUE THREAD

**Issue by ineentho** [Grsmto/simplebar#42]
Calling `simpleBar.recalculate()` on a mac with floating scrollbars causes a crash since simplebar isn't active. I feel like that's reasonable, but there's no good way of detecting that.

In a few places in our code we have

```
this.simpleBar.recalculate();
this.simpleBar.flashScrollbar();
```

that runs when we add more content. It probably shouldn't be needed in v2 with mutation observers, but that's another issue.

The best way I found to make that code not crash on a mac is wrapping it with if `(this.simpleBar.el.style.overflow !== 'auto')`. I think two changes would be good:

1. Public facing functions such as recalculate should be noops when the scrollbar is disabled
2. There should be a way to detect if simplebar is active or not, simpleBar.enabled?

One of the above solutions is enough, but maybe it would be convenient to include both?

**Comment by Grsmto** [comment]
Hey! Thanks for this.
I agree with both the solutions you provide. I will take a look.
