### ISSUE TITLE
Track bug or terrible UX

### ISSUE THREAD

**Issue by sobekcinasobek** [Grsmto/simplebar#420]
Frustrating experience if you misclick the thumb
1. Go to https://grsmto.github.io/simplebar/

2. Click a few pixels next to Thumb Bounds and you will click right on Track Bound

![ScrollTrackErrorGlitch](https://user-images.githubusercontent.com/58614940/70367293-ea1eae00-189e-11ea-83c0-a04c0dc0065e.gif)

track is wider than thumb
![TrackVsThumb](https://user-images.githubusercontent.com/58614940/70367310-0de1f400-189f-11ea-9586-652553f3e25d.png)

**Comment by Grsmto** [comment]
Thanks for the report.
Just FYI this is not the case by default with the plugin, this is just the implementation of the website that has this issue.

**Comment by sobekcinasobek** [comment]
Are you sure? In my localhost app have the same issue and didn't change any of the options for the plugin

By the way I am using the "**simplebar-vue**"



Indeed track is smaller than the SimpleBar website but still, that ~1px on the scroll track is annoying
![thumb vs track](https://user-images.githubusercontent.com/58614940/70457834-26295d00-1ab1-11ea-8344-fdb82202efc6.png)


![Screen-Recording-_12-9-2019-6-13-14-PM_](https://user-images.githubusercontent.com/58614940/70457801-1d388b80-1ab1-11ea-8da2-44fa974c8305.gif)

**Comment by Grsmto** [comment]
Published as minor release. Thanks.

**Comment by andersk** [comment]
@Grsmto Did you mean to apply this change to the vertical scrollbar only, or should the horizontal scrollbar be changed as well?

**Comment by Grsmto** [comment]
@andersk it seems to affect only the vertical one. Horizontal bar still has this issue.
Did this change break something on your app?
