### ISSUE TITLE
How to prevent scrolling when clicked on scrollbar-track?

### ISSUE THREAD

**Issue by The-1818** [Grsmto/simplebar#421]
Usually, when clicked somewhere on `scrollbar-track`, `scrollbar-thumb` will move to the clicked area.
But I noticed that on [Twitch](https://twitch.tv) this is **not** the case. Since they also use SimpleBar, does anybody know how to do this?
![image](https://user-images.githubusercontent.com/58142354/70389566-c6b94780-19f3-11ea-9b6b-20cf484d16f5.png) <br>
_gif from: https://github.com/Grsmto/simplebar/issues/420_
![image](https://user-images.githubusercontent.com/58614940/70367293-ea1eae00-189e-11ea-83c0-a04c0dc0065e.gif)

**Comment by Grsmto** [comment]
There is now a new `clickOnTrack` option.
Published as minor release. Thanks.
