### ISSUE TITLE
Scrollbar in a modal

### ISSUE THREAD

**Issue by carpben** [Grsmto/simplebar#422]
I tried using simplebar in a modal/popup. It didn't work, probably because the parent modal uses fixed position. Is there a way to adjust Simplebar to handle such a situation? Are you aware of a different solution?

**Comment by scammi** [comment]
Inside the modal script
`new SimpleBar($(' .modal-body')[0]);`

**Comment by carpben** [comment]
@scammi I'm using "simplebar-react"

**Comment by gitcatrat** [comment]
@carpben https://github.com/Grsmto/simplebar/issues/529

**Comment by carpben** [comment]
@gitcatrat thanks, also React.portal might help. 

It's been nearly a year since I opened it and I am not sure if it's still relevant. Closing.
