### ISSUE TITLE
What do I style?

### ISSUE THREAD

**Issue by AbrahamBrookes** [Grsmto/simplebar#424]
Can you include in the README what css selector users need to style? After seeing what html was generated on my site I found that I should be styling the .simplebar-scrollbar class, but there's nowhere in the docs that outlines that. A little more explanation in the README about exactly what HTML structure the code generates and what to style would be good, so we know we're doing it right. Cheers!

**Comment by Grsmto** [comment]
I added a section in the README about styling.
Hope that gives hints on how to style the scrollbar.
https://github.com/Grsmto/simplebar/tree/master/packages/simplebar#styling
