### ISSUE TITLE
ScrollTop allways 0

### ISSUE THREAD

**Issue by scammi** [Grsmto/simplebar#426]
I have this modal where Simple bar is initiated and a form is  displayed. 
`el = new SimpleBar($('.fullModal .modal-body')[0]);`

When the modal is closed and opened again, the scroll bar remains where it was last placed.

` console.log(el.getScrollElement().scrollTop);`
Reveals that no matter where the scroll bar is placed it is set to 0, and when I try to set it equal to some value, it ignores it completely. 

I need to be able to set scrollTop = 0 and have it actually got to the top.

Thank you for your work.
Santiago.

**Comment by Grsmto** [comment]
The way you're trying to do seems correct. 
There might be an issue somewhere in your code that makes it not working.
I can't really help more than that without seeing the code, sorry!

**Comment by Cyrus-d** [comment]
Same problem here:

[https://codesandbox.io/s/tender-boyd-xcmdq](https://codesandbox.io/s/tender-boyd-xcmdq)

**Comment by scammi** [comment]
@Grsmto @Cyrus-d thank you for your answers.
I've been trying but haven't found a fix yet.  I've annexed some of my code, in the hope you might help me.

I have a bootstrap 4 modal
```
    <div id="fsModal" class="modal fade fullModal"  tabindex="-1" role="dialog">

      <div class="modal-dialog modal-dialog-centered" role="document"></div>

    </div>
```
I dynamically add a form throught ajax as
```
 $('#fsModal > .modal-dialog').html( form );
```

The form has a `div` that where I instantiate the simple bar from a script that came in the same ajax call
```
 var el = new SimpleBar($('.fullModal .modal-body')[0])
```

When the modal is closed I empty the .modal-dialog `vid`
```
 $('#fsModal').on('hidden.bs.modal', function () {
     $('#fsModal > .modal-dialog').empty();
 })
```
The scroll works, but when I re open a modal, it "remembers" where it was set.

![](https://media.giphy.com/media/S3JxVRTB7jZX47ytVy/giphy.gif)

Thanks!

**Comment by Grsmto** [comment]
@Cyrus-d you are doing `getContentElement` instead of `getScrollElement`.

**Comment by Cyrus-d** [comment]
@Grsmto correct, works fine with `getScrollElement`, thank you.

**Comment by Cyrus-d** [comment]
@scammi maybe using `simpleBar.recalculate();` when emptying the modal solve your problem!

**Comment by scammi** [comment]
Thank you, but it seems the problem does not relay relies on simple bar, since I removed it and the issue persists with the browser scroll

**Comment by ppazos** [comment]
@Grsmto getScrollElement is returning undefined in simplebar 4.1

**Comment by ppazos** [comment]
Now just tested with SimpleBar 5.1.0 I get the same: el.getScrollElement() is undefined,

"el" is:

```
{
  "el": {},
  "minScrollbarWidth": 20,
  "options": {
    "autoHide": true,
    "forceVisible": false,
    "clickOnTrack": true,
    "classNames": {
      "contentEl": "simplebar-content",
      "contentWrapper": "simplebar-content-wrapper",
      "offset": "simplebar-offset",
      "mask": "simplebar-mask",
      "wrapper": "simplebar-wrapper",
      "placeholder": "simplebar-placeholder",
      "scrollbar": "simplebar-scrollbar",
      "track": "simplebar-track",
      "heightAutoObserverWrapperEl": "simplebar-height-auto-observer-wrapper",
      "heightAutoObserverEl": "simplebar-height-auto-observer",
      "visible": "simplebar-visible",
      "horizontal": "simplebar-horizontal",
      "vertical": "simplebar-vertical",
      "hover": "simplebar-hover",
      "dragging": "simplebar-dragging"
    },
    "scrollbarMinSize": 25,
    "scrollbarMaxSize": 0,
    "timeout": 1000
  },
  "classNames": {
    "contentEl": "simplebar-content",
    "contentWrapper": "simplebar-content-wrapper",
    "offset": "simplebar-offset",
    "mask": "simplebar-mask",
    "wrapper": "simplebar-wrapper",
    "placeholder": "simplebar-placeholder",
    "scrollbar": "simplebar-scrollbar",
    "track": "simplebar-track",
    "heightAutoObserverWrapperEl": "simplebar-height-auto-observer-wrapper",
    "heightAutoObserverEl": "simplebar-height-auto-observer",
    "visible": "simplebar-visible",
    "horizontal": "simplebar-horizontal",
    "vertical": "simplebar-vertical",
    "hover": "simplebar-hover",
    "dragging": "simplebar-dragging"
  },
  "axis": {
    "x": {
      "scrollOffsetAttr": "scrollLeft",
      "sizeAttr": "width",
      "scrollSizeAttr": "scrollWidth",
      "offsetSizeAttr": "offsetWidth",
      "offsetAttr": "left",
      "overflowAttr": "overflowX",
      "dragOffset": 0,
      "isOverflowing": true,
      "isVisible": false,
      "forceVisible": false,
      "track": {},
      "scrollbar": {}
    },
    "y": {
      "scrollOffsetAttr": "scrollTop",
      "sizeAttr": "height",
      "scrollSizeAttr": "scrollHeight",
      "offsetSizeAttr": "offsetHeight",
      "offsetAttr": "top",
      "overflowAttr": "overflowY",
      "dragOffset": 0,
      "isOverflowing": true,
      "isVisible": false,
      "forceVisible": false,
      "track": {},
      "scrollbar": {}
    }
  },
  "removePreventClickId": null
}
```

**Comment by ppazos** [comment]
found the issue:

1. when the scrollbar is created, it returns the right object with the getScrollElement() defined
2. the issue is when I need to scroll up, and try to get the SimpleBar on the element that already has the SimpleBar applied, I think the lib tries to apply the plugin again and returns a different object, with getScrollElement() undefined

The only solution I found is to create a global variable, which I hate, and store the SimpleBar object returned when first applied the plugin, then when I need to scroll up, I access that global bar.

Would be nice if the plugin detects that it is already applied and returns the same object instead of a different inconsistent one.

**Comment by abishekrsrikaanth** [comment]
@ppazos, I have the same issue and I cannot use the `getScrollElement` for the same reason. @Grsmto, can you please look into this and solve this issue?
