### ISSUE TITLE
Simplebar produces SCRIPT5022: SyntaxError in IE 11

### ISSUE THREAD

**Issue by Sachien** [Grsmto/simplebar#429]
Hi there,

Simplebar produces `SCRIPT5022: SyntaxError` in IE(only) when used with ng-quill (https://github.com/KillerCodeMonkey/ngQuill/releases).

Though Simplebar works fine but whole ng-quill functionalities are broken.

**Reproducible example**
http://jsfiddle.net/czh5ewj7/2/

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.1.0
| Browser          | IE 11

Any quick solution would be appreciated.
Thanks!

**Comment by rjpedrosa** [comment]
Hi,

It seems IE does like the `:not` on 

```
Array.prototype.forEach.call(addedNode.querySelectorAll('[data-simplebar]:not([data-simplebar="init"])'), function (el) {
    !SimpleBar.instances.has(el) && new SimpleBar(el, getOptions(el.attributes));
});
```
I suggest excluding the "init" data-simplebar items inside the function,  @like:

```
Array.prototype.forEach.call(addedNode.querySelectorAll('[data-simplebar]'), function (el) {
    if(el.getAttribute("data-simplebar") != "init")
        !SimpleBar.instances.has(el) && new SimpleBar(el, getOptions(el.attributes));
});
```

**Comment by jocdu** [comment]
Same here without ng-quill :-(
Would be great to fix this with the solution from rjpedrosa above

**Comment by layvd** [comment]
@Grsmto it is still there, please release new version for this bug
