### ISSUE TITLE
SimpleBar container width collapsed when used in absolutely positioned container

### ISSUE THREAD

**Issue by resetko** [Grsmto/simplebar#430]
**Describe the bug**
SimpleBar container width is collapsing when used in floating (`position: absolute`) container.

**To Reproduce**
Use SimpleBar component within floating `div`

**Expected behavior**
Please correct me if I'm wrong, but from my understanding it should behave same as regular `div` with native `overflow: hidden scroll` property (adjust width to width of child elements, based on hardcoded css value or based on content).

**Reproducible example**
https://stackblitz.com/edit/react-ts-stdesm
Please check 2 boxes, `red` box is using native scroll, `pink` box is using SimpleBar component.

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.1.0
| Browser          | Chrome 79.0.3945.79
| npm/Yarn         |
| Operating System | Linux

**Comment by ErikParso** [comment]
I have a same problem, i want to use simplebar to scroll through options in my dialog

**Comment by VladyslavKramar** [comment]
Same issue.

**Comment by ErikParso** [comment]
Any progress on this issue ?

**Comment by Techwolfy** [comment]
I ran into this issue when attempting to apply SimpleBar to a Bootstrap dropdown menu. I was able to work around it by manually calculating and setting the width on the containing element, but I'd strongly prefer a CSS-based solution within the library.

**Comment by Grsmto** [comment]
Fixed in latest version.

**Comment by jojkos** [comment]
I have changed the version of SimplerBar used in the example and i don't think that the behavior is now completely correct https://stackblitz.com/edit/react-ts-q9u8l4.

The container isn't completely collapsed as it was before, but the width doesn't stretch properly to fit whole content. Is there something i'm missing?

**Comment by danylo-holovenko** [comment]
@Grsmto  Is there any solution to this issue?

**Comment by m3l1x** [comment]
it seems like the flex environment is broken again since 6.0.0
