### ISSUE TITLE
Change scrollbar color

### ISSUE THREAD

**Issue by Blackleones** [Grsmto/simplebar#431]
I notice sample's scrollbar has different color (like orange) compared to the default (dark grey). 
How can I change the default scrollbar color?

**Comment by jephtta** [comment]
Use simple css like this:
```
.simplebar-track.simplebar-vertical .simplebar-scrollbar:before {
    background-color: 'orange"
}
```
One of the samples uses a yellow/red gradient. You can achieve something similar like this:

```
.simplebar-track.simplebar-vertical .simplebar-scrollbar:before {
       background-image: linear-gradient( yellow , red);
}
```

**Comment by Grsmto** [comment]
I added a section in the README about styling.
Hope that gives hints on how to style the scrollbar.
https://github.com/Grsmto/simplebar/tree/master/packages/simplebar#styling

**Comment by TheMangoTrain** [comment]
> .simplebar-track.simplebar-vertical .simplebar-scrollbar:before {
>     background-color: 'orange"
> }

This did not work for me.

Based on Grsmto's guidance, this works:
```
.simplebar-track.simplebar-vertical {
    background-color: orange;
}
```
or
```
.simplebar-track{
    opacity: 0.3;
}
```

**Comment by beardfacefacebeard** [comment]
so implementing a color to the scrollbar was not difficult, i used the following with success:
`.simplebar-scrollbar::before {
  background-color: AliceBlue !important;
  opacity: 0.7;
}`

my question is how do i apply multiple styles if im using multiple simplebars?
ive tried adding
`.sbc-invis::before { background-color: Yellow !important; opacity: 1.0 !important; }`
and then my secondary simplebar is 
`<div data-simplebar class="simplebar-scrollbar sbc-invis">`
this does not work as hoped. any insight?
