### ISSUE TITLE
ScrollTo on load

### ISSUE THREAD

**Issue by mcgodan** [Grsmto/simplebar#435]
Using the react plugin i am using the ref to update the scrollTo position on my component mount, however, because the simblebar component hasn't yet mounted it fails, to overcome this i have added a setImmediate which works, but i think it would be cleaner to accept a starting position prop?

(using 2.0.7-corejs version)

**Comment by Grsmto** [comment]
Hi,
I tried to reproduce this problem but it works just fine when I do it. See Sandbox: https://codesandbox.io/s/nice-turing-8bmk9

Maybe you could provide an example using that.

**Comment by mcgodan** [comment]
I think it's because i have two components in my example, one which is mounting and calling a function to use the ref before the simplebar component has mounted from the render inside it...
