### ISSUE TITLE
"React does not recognize the `autoHide` prop on a DOM element."

### ISSUE THREAD

**Issue by GunslingerBara** [Grsmto/simplebar#436]
**Describe the bug**
On page load, I see a warning in Chrome's console with the following information:

`Warning: React does not recognize the `autoHide` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `autohide` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by SimpleBar)
    in SimpleBar (at App.js:141)
    in div
    in Layout (at App.js:140)
    in div
    in Fixed (at App.js:131)
    in SideBar (at App.js:341)
    in MediaQuery (at App.js:338)
    in div
    in Layout (at App.js:368)
    in App (created by ConnectFunction)
    in ConnectFunction (at src/index.js:24)
    in Provider (at src/index.js:23)`

**To Reproduce**
I don't think I'm doing anything special with SimpleBar? See below:

`<SimpleBar
          autoHide={false}
          style={{ overflow: "auto", height: "100%" }}
        >`

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 1.2.3
| Browser          | Chrome latest
| npm/Yarn         | yarn: 1.19.1
| Operating System | Windows 10

**Comment by Grsmto** [comment]
You are using an old version of `simplebar-react`. At that time, this way of passing options was not supported.
Either update to latest version or set the option this way: `data-simplebar="auto-hide"`

Thanks!

**Comment by blacksteed232** [comment]
@Grsmto I think we need to update the typescript definition, it seems to be out of date

**Comment by kaniseo** [comment]
I'm on the latest version of SimpleBar@2.1.0 and autoHide does not seem to be in the definition file.
[https://github.com/Grsmto/simplebar/blob/master/packages/simplebar-react/simplebar-react.d.ts](url)
