### ISSUE TITLE
What can cause both the simplebar and the native scrollbar to simultaneously show?

### ISSUE THREAD

**Issue by ajssd** [Grsmto/simplebar#438]
I've been trying to debug this without luck. What can cause the situation where both the simplebar and the native scrollbar both show?  The scrollable area is using css "flex: 1 1 auto" with overflow:auto.  The simplebar scrolling works fine, but there is the native scrollbar right next to it -- which kicks in after using simplebar to scroll all the way to the bottom.

In the debugger, if I apply overflow:hidden to the DIV with "data-simplebar" on it, then *both* scrollbars go away, and I can no longer scroll.  So they are definitely related to the same scrollable area.

![image](https://user-images.githubusercontent.com/10245941/73109345-b67ffd80-3eb7-11ea-9468-5b4cb260225f.png)

Using Safari 13.0.4 on macOS.

**Comment by Grsmto** [comment]
It's really hard to say, it can depend of a lot of stuff. Pretty impossible to tell you without trying and seeing code.
Maybe try to set `width: 100%; height: 100%` to your scrollable element.

**Comment by ajssd** [comment]
Got it ... and yes, I know it's nearly impossible to tell, but your suggestion was on the right track, it turns out.  It was solved by adding `height: 0px` (or any height other than `auto`) to the existing `flex: 1 1 auto`.
