### ISSUE TITLE
Scrollbar fixed height?

### ISSUE THREAD

**Issue by kimneu3001** [Grsmto/simplebar#44]
Do you have an idea how I could make the scrollbar fixed height? By default it's changing it's height according to viewport height, right? I'd like to disable that and write my custom height. But the scrollbar-track height should still adapt by viewport size. Using V1, can't get V2 beta to work..

**Comment by Grsmto** [comment]
Yes the plugin is intended to size the scrollbar just like it is usually on a normal scrollbar.
The only way I see you could give the scrollbar a fixed height is by defining its size in css followed by the `!important` suffix (to override the JS logic). But it will probably not work as you expect it.
I don't see any proper solution for that without altering the code of the plugin...
