### ISSUE TITLE
Can't change style (mac OS)

### ISSUE THREAD

**Issue by Altyn777** [Grsmto/simplebar#440]
I edited example and it works: https://codesandbox.io/s/inspiring-pond-oscn0
But in my project i can't set styles, it doesn't work:

```
import React from 'react';
import SimpleBar from 'simplebar-react';

import 'simplebar/dist/simplebar.min.css';
// import './styles.m.css'; don't work
import style from './styles.m.css'; // don't work

export function CustomScrollbars({
    children,
    autoHide = false,
    forceVisible = 'y',
    ...rest
}) {
    return (
        <SimpleBar
            style={{ maxHeight: 300 }} 
            autoHide={autoHide}      <--- this prop doesn't gives me same result as example above
            forceVisible={forceVisible}
            className={style}
            {...rest}
        >
            {children}
        </SimpleBar>
    );
}

```
prop autoHide here just make scroll visible firstly, but later it hide
I use mac OS (in my system settings scrollbar is always visible) and checked code at Chrome and Safari
Please, help me

**Comment by Grsmto** [comment]
Hi @Altyn777 apparently you have an issue with the import of CSS files in your project.
This is related to your project environment. You have to provide more information otherwise there is now ay I can help you.
What tool are you using to build your website? Is it Webpack, Create React App, Gatsby, Nextjs...?
What you are looking for is: "_How to import css files in [Webpack/CRA/Gatsby,Nextjs]?_"

**Comment by Altyn777** [comment]
Hi, @Neverbland, thanks a lot, you're right! I used Webpack and already fix this problem

But the property autoHide is still behaving strangely. 

And another question: I will import the style from this library in the file, but in the future my file will be in my library, and then the import will not work (import from one library to another, while the default style will need to be rewritten with my style). Is there any other way to use the style from your library so as not to lose support? Maybe some kind of style file is generated, or something like that.

**Comment by Grsmto** [comment]
>But the property autoHide is still behaving strangely.

Can't really help you on that without having an example of it "behaving strangely".

About your question regarding the styles, I'm not sure to understand exactly what you want to do. But again it depends of your bundler. I believe with Webpack you should be able to import simplebar.css from your own style.css file with an @import rule.
The user of your library can then do the same thing as you're doing with this one.

**Comment by Altyn777** [comment]
I think this is due to the wrong styles. When I set true/false to autoHide, nothing changes.
This scrollbar is always visible:
```
.simplebar-scrollbar {
    background-color: var(--rgbaColor2);
    ...
}

.simplebar-scrollbar:before {
    visibility: hidden;
}

.simplebar-scrollbar.simplebar-hover {
    background-color: var(--rgbaColor3);
    border: 2px solid var(--rgbaColor4);
}
```
and this is always hidden:
```
.simplebar-track.simplebar-vertical .simplebar-scrollbar:before {
    background-color: var(--rgbaColor2);
    ...
}

.simplebar-scrollbar.simplebar-hover {
    background-color: var(--rgbaColor3);
    border: 2px solid var(--rgbaColor4);
}
```
