### ISSUE TITLE
is it possible to resize the scrollbar?

### ISSUE THREAD

**Issue by jrse** [Grsmto/simplebar#444]
I would like to know, if it is possible to style the vertical scrollbar in a way, that it is for example attached to the bottom and has only the size of x instead of 100%.
This would be great.

**Comment by Grsmto** [comment]
Hi,

Maybe you can try [the min/max options](https://github.com/Grsmto/simplebar/tree/master/packages/simplebar#scrollbarminsize--scrollbarmaxsize) to do that.
