### ISSUE TITLE
Improve RTL Scroll Behavior Feature Detection

### ISSUE THREAD

**Issue by fred-wang** [Grsmto/simplebar#446]
As part of Chromium web interoperability effort, we are trying to switch to standard scroll coordinates for non-default writing modes ( see https://www.chromestatus.com/feature/5759578031521792 ). In particular, we are trying to check potential breakages by counting web pages setting scroll coordinate to positive values for scrollers that are supposed to use nonpositive values. `simplebar` is causing websites to trigger our use counters because of the operation scrollbarDummyEl.scrollLeft = 999.

@KingSora plans to change the feature detection of the OverlayScrollbars so that it only relies on setting nonpositive values and so won't trigger false positives ( see https://github.com/KingSora/OverlayScrollbars/issues/187#issuecomment-586876303 ). `simplebar` can probably follow the same approach.

**Comment by Grsmto** [comment]
Hi Fred,
Thanks for the report I will take a look as soon as possible.

**Comment by fred-wang** [comment]
Thanks @Grsmto !
