### ISSUE TITLE
The code needs to pass JSHint

### ISSUE THREAD

**Issue by stentas** [Grsmto/simplebar#448]
We want to try and use this nice scrollbar but our automatic testing (JSHint) finds too many errors.
If you paste the [compiled version](https://unpkg.com/simplebar@5.1.0/dist/simplebar.js) into this page: https://jshint.com/ you will see the errors.

Here are some of the errors:

`(global = global || self, global.SimpleBar = factory());`
Expected an assignment or function call and instead saw an expression.

`var global_1 =`
Identifier 'global_1' is not in camel case.

`Function('return this')();`
Missing 'new' prefix when invoking a constructor.

`return Object.defineProperty({}, 'a', { get: function () { return 7; } }).a != 7;`
Expected '!==' and instead saw '!='.

In multipl places you drop using {} on if statements. That also gives error.

and it keeps going. I hope the code can ble cleaned up to pass JSHint :)

**Comment by andersk** [comment]
Linters such as JSHint are not intended to be run on compiled code. And in general, you cannot expect all third-party packages to conform to the preferences dictated by your own linting setup, since preferences vary between developers. SimpleBar uses ESLint.
