### ISSUE TITLE
Flicker on initial display of simplebar

### ISSUE THREAD

**Issue by Pitros** [Grsmto/simplebar#449]
**Describe the bug**
When displaying conditionally simplebar in react, flickering is visible. Wrapper properties are set after browser paint.

To fix this issue, simplebar-react should rather use `useLayoutEffect` instead of `useEffect` hook to set properties before browser paint. https://github.com/Grsmto/simplebar/blob/master/packages/simplebar-react/index.js#L68

This issue did not occur in v1 of `simplebar-react`.

**To Reproduce**
Show simplebar conditionally.

**Expected behavior**
It should not flicker, height should be set before paint.

**Reproducible example**
https://codesandbox.io/s/cocky-darkness-2vq2k

Ckick on toggle button, numbers for a while appear outside red box, also scroll container is sometimes rendered with a delay.

**Comment by trronaldbasco** [comment]
Experiencing the same issue.

**Comment by danpalisoc** [comment]
This can be done as a workaround to resolve the flicker issue.

https://codesandbox.io/s/zen-euclid-2u2m4

**Comment by Grsmto** [comment]
Hi guys,
I'm not sure why you are using an old version but this bug was fixed a while ago and from my tests it works fine on your codepen with the latest version: https://codesandbox.io/s/romantic-varahamihira-kbmv8

I'm closing then! Thanks.

**Comment by ajitid** [comment]
I too faced a similar issue and switching to `useLayoutEffect` solved it. My requirement was to set scroll position before first paint. This is another case to prefer `useLayoutEffect` over `useEffect` in `simplebar-react` package.
