### ISSUE TITLE
Cannot click/scroll at all in Chrome/Windows

### ISSUE THREAD

**Issue by designumber18** [Grsmto/simplebar#45]
Simplebar seems to be working fairly well in most every browser, but I've found that it doesn't respond at all in Chrome on Windows 8 or 10. The  window I have simplebar used on does not scroll via mouse, nor will it allow me to click/drag on the sidebar to scroll that way.

I've tested on Mac using FF, Chrome, Safari, and on Windows using FF and IE... all function properly. Chrome on Windows is the only one that doesn't work. Any idea why this would be?

Thanks for any help!

**Comment by Grsmto** [comment]
Hey,
I just tested on Browserstack (I don't have a PC) on Windows 10, latest Chrome and it seems to be working fine for me. Do you have an existing environment where I could test it and see it not working?
Thanks

**Comment by designumber18** [comment]
Thanks for your reply! Yeah, got a little help from our Dev team here at work, and we determined that the issue is probably coming from people using older versions of browsers. We tried it on an older version of FF, it didn't work, then updated to the latest version, and the scrolling worked. So that may be the issue. If you don't have a PC, I'm not sure I can show it not working to you, because I can't even reproduce it myself unless I'm on a colleague's PC. 

Aside from that little hiccup, it's really cool stuff you've put together, thanks for sharing it! And thanks again for responding!

**Comment by Grsmto** [comment]
Thank you for the nice words :)
I'll take a look on older browsers versions then as I only tested on latest!

**Comment by designumber18** [comment]
No problem, I really do appreciate your work! I'm on a Mac too, and it's fantastic on all Mac browsers, just the older PC versions of FF and Chrome seem to not recognize the scrolling, not sure why. Thanks again!

**Comment by carasmo** [comment]
What versions of old browsers did this not work in?

**Comment by designumber18** [comment]
Chrome on Windows 8 and 10, and older (but fairly recent) versions of Firefox on PC only. Mac versions worked fine.

**Comment by Grsmto** [comment]
Hey,
So I just tested on Browserstack with Windows 8 on Firefox 50 (currently it's 57) and Chrome 56 (currently it's 63) and it worked as expected.
I'll close now, you can comment if you have more details about a precise browser version. It's probably a polyfill missing.
