### ISSUE TITLE
Scroll Wheel not working for some parts of scroll area in Firefox

### ISSUE THREAD

**Issue by weldonla** [Grsmto/simplebar#450]
## Current Behavior

Scroll Wheel not working for some parts of scroll area in Firefox. The scroll wheel will only work when the mouse is over certain elements in the scrollable section. Whereas in Chrome it works fine as long as the mouse is anywhere within the element with overflow.

## Additional context

I'm using aurelia if that's important. 

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.1.0        |
| Browser           | Firefox     |
| npm/Yarn        | npm         |
| OS                   | Win 10     |

**Comment by weldonla** [comment]
Update: for some reason, setting the z-index of the main scrollable content fixes the issue.

**Comment by Grsmto** [comment]
Closing as it's probably related to specific implementation.
