### ISSUE TITLE
Scrollbar style change in react is non trivial

### ISSUE THREAD

**Issue by anshumandce** [Grsmto/simplebar#453]
## 💬 Questions and Help
Hi I am working to integrate simplebar in a typescript based react project.
I am trying to change the color of the scrollbar, by editing the className in options. I was hoping that by having the same css class name, the css property would get overwritten. However I see no change here. Would appreciate any help. Here is a test code which I was using to validate if this works:
https://codesandbox.io/s/inspiring-nash-5b8qk

**Comment by Grsmto** [comment]
There is now an example on [the README](https://github.com/Grsmto/simplebar/tree/master/packages/simplebar#styling).
