### ISSUE TITLE
[simplebar-react] classNames conflict with storybook addons

### ISSUE THREAD

**Issue by ElForastero** [Grsmto/simplebar#454]
**Describe the bug**
classNames from 'simplebar-react' package conflict with other packages that use simplebar.

And since they can't be customized, this is very sad :(

I'm tried to fork the package and adjust all classNames with some prefix, but I have encountered an issue with data attributes. Since them can't be configured as well, SimpleBar is going to be initialized twice - first time by storybook.

**To Reproduce**
No need to reproduce. It's a fact.

**Expected behavior**
All classNames must be customizable via props, to avoid conflicts and wrong defaults taken from other packages.

**Reproducible example**
No.

**Additional context**
We need an ability to configure all classNames, if it's needed.

**Your environment**
simplebar-react: v2

**Comment by Grsmto** [comment]
Hi,
Could give more details on this issue? What is your setup and what are you trying to achieve?

I understand that you are using Storybook, so you have another SimpleBar component inside yout Storybook story? Is that it? 

Also I'm not sure to understand what classes have to do with this, they are used only for CSS styling. 
If SimpleBar is initialized twice it seems like another issue.

**Comment by ElForastero** [comment]
@Grsmto Hi,

Sorry about the missing details.

Yep, I forgot about the main problem - the data attribute `data-simplebar`.

When using `simplebar-react` in Storybook (basically in an environment with already installed simplebar), it will be initialized after seeing `data-simplebar` attribute. And `react-simpebar` itself initializes scroll again. So we have the situation when the scroll was initialized 2 times - we have 2 nested simplebars (wrappers, containers, etc...).

But styling is a problem too since classes are global. They just conflict with each other.

I'm not sure if there is a way to solve the `data-` attribute problem. Can we just remove it from React version? We initialize the scroll anyway.

**Comment by Grsmto** [comment]
This shouldn't happen anymore. Thanks.
