### ISSUE TITLE
[2.0.1] Native scrollbar is flashed when the view first starts overflowing

### ISSUE THREAD

**Issue by Tarpsvo** [Grsmto/simplebar#46]
Simplebar 2.0.1. Chrome 55. Windows 10.

When a view goes from not needing a scrollbar to needing a scrollbar, the native scrollbar will flash for a brief moment of time. Probably due to debouncing and/or initialization times.

I wonder if there are any ways to avoid the flashing?

**Comment by Grsmto** [comment]
Hi,
I can't reproduce this issue on my testing page. How can I reproduce?
The debounce shouldn't be the problem as we are using the `leading` option (so calculation got called immediately anyway, only subsequent calls are debounced).

**Comment by Tarpsvo** [comment]
Hey!

I tried to create a test to reproduce the issue, but failed to create a minimalistic example.

I think the scroll was flashing cause of the complexity of my view rendering - it added a lot of things to the browser main queue and by the time the queue got to the SimpleBar, the browser had already decided to render the default scrollbar.

I cannot give you a reproducible testcase right now, sorry. I'll look into it a bit more on my own for now, Currently it seems it's entirely my fault. 😐

Great library, thank you for your efforts!

**Comment by Grsmto** [comment]
Ok thanks for this. I hope it's not caused by the Mutation Observer, I didn't test it in situation with a big DOM and lot of manipulations.
If you come back with some performances issues I'll try to take a look at that as it may be concerning.

**Comment by Tarpsvo** [comment]
While trying to create a testcase to replicate the issue at hand, I ran across another issue: scrollbar slider position calculations. In scrollable areas with extremely long content, the scrollbar slider position seems to be calculated a bit wrong, causing the native scrollbar to appear as well.

See the fiddle below. Scroll to the bottom to see the issue. (Windows 10, Chrome 55, Simplebar 2.0.1).

https://gist.run/?id=1b4a0c88d0a5772ef26248ca22e87a2e

**Comment by Grsmto** [comment]
Oh that's a weird one!
Apparently it's happening no matter the number of item, when you reach the end of the list!

**Comment by Tarpsvo** [comment]
Hmm, true. Could be related to the fact that it is a fragment inside an iframe, not in an actual website.

**Comment by Grsmto** [comment]
Fixed in 45abdcbce7f2c6e6a9e7a7e8505b31a97349e1e7
