### ISSUE TITLE
Applying simplebar to DIV with visibility:hidden causes content to become visible

### ISSUE THREAD

**Issue by ajssd** [Grsmto/simplebar#464]
**Describe the bug**
Applying simplebar to DIV with visibility:hidden causes content to become visible

**To Reproduce**
1. Create a DIV with a CSS class that includes visibility:hidden.  Ours happens to look like this:

position: absolute;
top: 0;
bottom: 0;
left: 0;
right: 0;
visibility: hidden;

2. Add data-simplebar="init" to the DIV
3. Put some content inside the DIV

**Expected behavior**
The contents of the DIV should not be visible until another css class is applied that overrides the visibility property.

**Reproducible example**
https://jsfiddle.net/asefkow/3z1jf6rn/3/

**Additional context**

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 4.2.3
| Browser          | Safari 13.1
| npm/Yarn         | 10.x
| Operating System | macOS

**Comment by Grsmto** [comment]
Fixed in latest version.
