### ISSUE TITLE
how can i get position of scroll for ajax calls to load more data

### ISSUE THREAD

**Issue by shivamswims456** [Grsmto/simplebar#465]
## 💬 Questions and Help

Please before asking your question:

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

**Comment by DivyanshBatham** [comment]
I also have to implement infinite scroll, have been trying for hours now. I'm working in Vue with (simplebar-vue wrapper). I would really appreciate if anyone can guide me in the right direction.

**Comment by minzojian** [comment]
what i am doing is listener the scroll event by `getScrollElement()`
```
const simpleBar = new SimpleBar(document.getElementById("myElement"));
        simpleBar
            .getScrollElement()
            .addEventListener("scroll", function (event) {
                if (
                    event.target.scrollHeight - event.target.scrollTop <=
                    event.target.clientHeight
                ) {
                    ////bottom arrive... do something...
                }
            });
```
