### ISSUE TITLE
Styling the simplebar doesn't work with angular

### ISSUE THREAD

**Issue by Latifaa17** [Grsmto/simplebar#468]
I implemented the simplebar in angular using this code: 
```
<ngx-simplebar [options]="options" >
    <div *ngFor="let number of numbers">ngx-simplebar</div>
  </ngx-simplebar>
```
I tried to change the color following the documentation:
```
.simplebar-scrollbar::before {
    background-color: red !important; 
}
```
But it didn't work, is changing the color possible with angular ?

**Edit**
Moved the code to the global styles.css and it worked

**Comment by salmoro** [comment]
@Latifaa17 Angular components have style encapsulation turned on by default.

When you need to change styles of child components you'd either need to turn off view encapsulation on your component or use piercing in css via `::ng-deep`.
