### ISSUE TITLE
Destroy/umount

### ISSUE THREAD

**Issue by Yearhouse** [Grsmto/simplebar#47]
Hi 

How can I destroy or unmount SimpleBar??

**Comment by Grsmto** [comment]
Hey,
If you're using V2, it should unmount automatically when the element if removed from the DOM.
If you want to unmount for any other reason, you can call the `unMount` function. 
It will not revert the element to his original DOM structure still. If you want to do that you will have to do it manually (maybe by cloning the element in JS before SimpleBar is applied...).
