### ISSUE TITLE
How to add scroll event or set scroll position in ngx-simplebar in Angular app?

### ISSUE THREAD

**Issue by steosoft** [Grsmto/simplebar#471]
I'm developing Angular application and I'm using your awesome scrollbar. I really appreciate you work.

I wanted to add scroll event listener to simplebar to detect when user scrolls to bottom (and then fetch more data to show) but I have problem. Simple adding Angular (scroll) to <ngx-simplebar> element doesn't work. Also tried use strategy with calling getScrollElement() method but I don't really know how to do that - if I add ElementRef to ngx-simplebar element then I don't have such method.

Any help would be really appreciated.

**Comment by fpauser** [comment]
You can observe the current scroll position of `.simplebar-content-wrapper` and react accordingly.

**Comment by steosoft** [comment]
How to do that? I tried:
```
let wrapper = document.querySelector('#myScrollElement').querySelector('.simplebar-content-wrapper');
```
and then attach any of 3:
```
wrapper.onscroll = (event) => { };
wrapper.onScroll = (event) => { };
wrapper.scroll = (event) => { };
```
but neither worked.

**Comment by Grsmto** [comment]
Did you try attaching a ref to the component and then accessing the SimpleBar instance from it?

like:
```js
<ngx-simplebar #componentRef></ngx-simplebar>
```

and then
```js
import { SimplebarAngularComponent } from './simplebar-angular'

@ViewChild('componentRef', { read: SimplebarAngularComponent })
componentRef: SimplebarAngularComponent;

// now you can access the scroll element and attach event listener to it:
componentRef.SimpleBar.getScrollElement()
```

**Comment by steosoft** [comment]
@Grsmto ok but how to attach event listener to ScrollElement? I tried:
```
    this.componentRef.SimpleBar.getScrollElement().scroll = (event) => { console.log("scroll") };
    this.componentRef.SimpleBar.getScrollElement().onscroll = (event) => { console.log("onscroll") };
    this.componentRef.SimpleBar.getScrollElement().onScroll = (event) => { console.log("onScroll") };
```
but neither worked.

**Comment by markhus-aurelius** [comment]
> @Grsmto ok but how to attach event listener to ScrollElement? I tried:
> 
> ```
>     this.componentRef.SimpleBar.getScrollElement().scroll = (event) => { console.log("scroll") };
>     this.componentRef.SimpleBar.getScrollElement().onscroll = (event) => { console.log("onscroll") };
>     this.componentRef.SimpleBar.getScrollElement().onScroll = (event) => { console.log("onScroll") };
> ```
> 
> but neither worked.

for anyone else stumbling across this. It would be...

this.componentRef.SimpleBar.getScrollElement().addEventListener('scroll', function(...));
