### ISSUE TITLE
Apply Simplebar to <SELECT size="number">?

### ISSUE THREAD

**Issue by abolfazlshirazi** [Grsmto/simplebar#479]
Is it possible to apply simplebar to SELECT element with size more than 1? I tried the followings but it does not work:

```

<!DOCTYPE HTML>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <link rel="stylesheet"  type="text/css" href="css/simplebar.css">
  <script type="text/javascript" src="js/simplebar.min.js"></script>
</head>
<body>
<select size="5" id="mydiv" style="width:200px" data-simplebar>
  <option>Item 1</option>
  <option>Item 2</option>
  <option>Item 3</option>
  <option>Item 4</option>
  <option>Item 5</option>
  <option>Item 6</option>
  <option>Item 7</option>
</select>
</body>
</html>


```

Not only it does not work, but it also makes the options items disappear. 

![Untitled-1](https://user-images.githubusercontent.com/45438565/83363754-17ef3600-a39c-11ea-80cf-b445c2d35c39.jpg)

Any solutions?

**Comment by Grsmto** [comment]
No it's not, because SimpleBar changes the DOM structure so your `<select>` element would then be invalid!
I will add this to [the limitations](https://github.com/Grsmto/simplebar/tree/master/packages/simplebar#5-caveats) and add a link from the README cause this is important. Thanks.
