### ISSUE TITLE
apply scroll to body

### ISSUE THREAD

**Issue by sadashivm** [Grsmto/simplebar#48]
Hi,
this is awesome scrollbar and i want to know how to apply scrollbar to body tag

i included bellow files
```
<link rel="stylesheet" href="https://unpkg.com/simplebar@2.0.1/umd/simplebar.css" />
<script src="https://unpkg.com/simplebar@2.0.1/umd/simplebar.js"></script>
```
it is not working,  i written like
```
<!DOCTYPE html>
<html>
<head>
    <title>Scrollbar demo</title>
    <link rel="stylesheet" href="src/simplebar.css" />
    <noscript>
        <style>
            [data-simplebar] {
                overflow: auto;
            }
        </style>
    </noscript>
</head>


<body data-simplebar>

   

        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
        <p>Some content</p>
        <p>Some more content</p>
  

    <script src="src/simplebar.js"></script>
</body>
</html>

```

and also i want to apply scrollbar both body and inner div then what should i write
pls tell me

**Comment by Grsmto** [comment]
Hi,
Simplebar is not intended to work on the `body` element for now.
Try to embed your body content inside a div and apply Simplebar on that div.
Wrapping your web page inside a giant `overflow: auto` scroll is usually a bad practice as it's slower than the natural body scroll (I know Chrome and modern browsers did some improvements on that, but still).

**Comment by sadashivm** [comment]
Hi,
thanks for reply ok now i will not apply to body. and one more
how to get scrolled position in pixel because i want to show "Scroll to Top" button after some scrolling . and after clicking it should go to top. i need this code can u tell me how to slove this.

i tried bellow code but im getting error.

```
<div data-simplebar id="myEle" style="height:600px;width:600px">
----------------- dummy text   --------------
</div>

```
and in script as 
```
<script>
var elem = document.getElementById("myEle");
var scrollVal = el.SimpleBar.getScrollElement();
alert(scrollVal);
</script>
```

for reference i attached screen shot of scroll to top button

![back to top](https://cloud.githubusercontent.com/assets/10355473/21514001/31d24d28-cce5-11e6-9832-de0ac119db69.png)


pls send me code as early as possible i stucked in above issue

**Comment by lafasta** [comment]
we are in 2023 and it still does not work on the body, I also tried to wrap the contents in a div but that did not help. the problem occurs on chrome. but on firefox it works just fine ...
