### ISSUE TITLE
Issue with simplebar-react and ts: Type '{ children: Element; forceVisible: string; autoHide: boolean; }' is not assignable to type 'IntrinsicAttributes & RefAttributes<any>'.   Property 'children' does not exist on type 'IntrinsicAttributes & RefAttributes<any>'.

### ISSUE THREAD

**Issue by inthepanchine** [Grsmto/simplebar#483]
**Describe the bug**
When using the component in a react + ts project it give return: 
`ERROR in /Users/liamcaccetta/developer/project/src/components/Component/Component.tsx(107,6)
      TS2322: Type '{ children: Element; forceVisible: string; autoHide: boolean; }' is not assignable to type 'IntrinsicAttributes & RefAttributes<any>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & RefAttributes<any>'.`

**To Reproduce**
1. `npm install simplebar-react` 
2. Add component `SimpleBar` to your react + ts project
3. Add the props there are in the simplebar-react documentation (`forceVisible="y"` and `autoHide={false}`)
4. Compile with webpack

**Expected behavior**
I want it to compile without errors caused by simplebar-react component

**Reproducible example**
I don't really know how to do it

**Additional context**
Ask for it if you need

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 2.2.0
| Browser          | Firefox 77.0.1 (64 bit)
| npm/Yarn         | npm-6.14.5 yarn-1.22.4
| Operating System | MacOS Catalina 10.15.5

**Comment by Grsmto** [comment]
Wondering if this is fixed in latest `simplebar-react@3.0.0-beta.5`? If anyone passing here could try it. Thanks!

**Comment by Grsmto** [comment]
SimpleBar has been entirely rewritten in TS so this should be fixed.
