### ISSUE TITLE
Delay scrollbar displaying

### ISSUE THREAD

**Issue by Fomin2402** [Grsmto/simplebar#486]
I use simplebar with selector dropdown with animation.
So, when container with content is increasing from maxHeight: 0 to some value, simplebar execute recalculate function a lot of times and that's terrible.
Plus when increasing of height of container with list is started and it's on the middle of full height, the scrollbar is displayed.
Due to this I trying to find a way with delaying of scrollbar displaying/calculation

**Comment by Grsmto** [comment]
You could override the CSS because all the animations are done in CSS. Then when your animation is finished, remove that CSS again.
Hope this helps, thanks!
