### ISSUE TITLE
SimpleBar-React : Passable option to always show scrollbar

### ISSUE THREAD

**Issue by Accretence** [Grsmto/simplebar#489]
I'm working on a Web Application in which the body element is unscrollable, I have some content in a Bootstrap Card and I would like to leave a visual cue for the user to tell them this card is scrollable when they enter the page.

**Comment by Grsmto** [comment]
You can use `autoHide={false}` this is on the [documentation](https://github.com/Grsmto/simplebar/tree/master/packages/simplebar-react#passing-options).
Hope that helps!
