### ISSUE TITLE
When using conditional rendering in simplebar-vue's parent, the scrollbar freezes.

### ISSUE THREAD

**Issue by chepe263** [Grsmto/simplebar#494]
**Describe the bug**
I'm using `v-if` to render conditionally several sections of my website. Inside, there is one `<simplebar-vue />`. When changing the parent using the `v-if`, the simplebar vue component freezes the scrollbar and no longer scrolls.  The content still scrolls. 

**To Reproduce**
1. Make three divs using v-if
2. Inside place simplebar vue components
3. Change between the parents using v-if
4. See error, the scrollbar is frozen but the content still scrolls

**Expected behavior**
The content scrolls and the scrollbar reflects the current scroll position

**Reproducible example**
https://codesandbox.io/s/peaceful-lichterman-kyr0q

**Additional context**
Using v-show instead of v-if is a workaround. 

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| simplebar-vue|^1.5.1
| Browser          |Google Chrome	83.0.4103.116 (Official Build) (64-bit) (cohort: Stable)
| npm/Yarn         |6.14.5
| Operating System | Win10 2004

**Comment by Grsmto** [comment]
Should be fixed in `simplebar-vue@2.0.0-beta.3`.
