### ISSUE TITLE
SCRIPT438: Object doesn't support property or method 'scrollTo'

### ISSUE THREAD

**Issue by andrey-evstigneev** [Grsmto/simplebar#499]
**To Reproduce**
Click to track (not to handle)
It's reproduced on demo page too (https://grsmto.github.io/simplebar/examples/)

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.2.1
| Browser          | IE11

**Comment by Grsmto** [comment]
Thanks for your report.
Released a fix in `simplebar@6.0.0-beta.3`.

**Comment by selenajosephine** [comment]
I tried updating to simplebar@6.0.0-beta.3, and I still faced this issue. Please advise

**Comment by mKlus** [comment]
@Grsmto Any chance you could include fix for this in version 5 and release, please? :)
