### ISSUE TITLE
Determine how much page scrolled in pixel 

### ISSUE THREAD

**Issue by sadashivm** [Grsmto/simplebar#50]
Hi,
thanks for reply ok now i will not apply to body. and one more
how to get scrolled position in pixel because i want to show "Scroll to Top" button after some scrolling . and after clicking it should go to top. i need this code can u tell me how to slove this.

```

var offset = 300;
$(window).scroll(function () {
if($(this).scrollTop() > offset) {
$('#scrollTop').show();
}
else {
$('#scrollTop').hide();
}
            });
```

but problem is im not getting $(this).scrollTop() value.
if i use default browser then i will get value but i use this scrollbar then above code is not working.

i tried bellow code but im getting error.

```
<div data-simplebar id="myEle" style="height:600px;width:600px">
----------------- dummy text   --------------
</div>

```
and in script as 
```
<script>
var elem = document.getElementById("myEle");
var scrollVal = el.SimpleBar.getScrollElement();
alert(scrollVal);
</script>
```

for reference i attached screen shot of scroll to top button

![back to top](https://cloud.githubusercontent.com/assets/10355473/21514001/31d24d28-cce5-11e6-9832-de0ac119db69.png)

pls send me code as early as possible i stucked in above issue

**Comment by Grsmto** [comment]
This should work:

```
var elem = document.getElementById("myEle");
var scrollVal = $(elem.SimpleBar.getScrollElement()).scrollTop();
alert(scrollVal);
```
