### ISSUE TITLE
Is there a way to add the scrollbar globally without manually adding it to every project or html element ?

### ISSUE THREAD

**Issue by WalidKurchied** [Grsmto/simplebar#500]
Im working with micro-frontend applications and I came across simplebar and I implemented a working example in one of the Reactjs projects but the thing is Im not sure thats the best way to go forward because every application will need to have the same scrollbar and I'm afraid other developers would forget to include it in their project so I'm wondering if there is a way to have it globally added so that every project would have it. most of the projects are written in ReactJS and there might be some that will be written in other frameworks.

Thank you

**Comment by WalidKurchied** [comment]
Closing this as I got it done.

**Comment by kumikumi** [comment]
What is the solution?
