### ISSUE TITLE
simplebar-vue 2.0.0-beta.2 is broken

### ISSUE THREAD

**Issue by chepe263** [Grsmto/simplebar#504]
**Describe the bug**
Installing simplebar-vue in a fresh install of vue (with vue-cli) 

```
[Vue warn]: Error in mounted hook: "TypeError: (0 , SimpleBar.default).getOptions is not a function"


found in


---> <SimplebarVue>

       <App> at /src/App.vue

         <Root>
```

Also, the css `simplebar/dist/simplebar.min.css` is now located in `simplebar-core/dist/simplebar.min.css`

**To Reproduce**
1. `npm install simplebar-vue`
2. `import simplebar from 'simplebar-vue'; ` as stated in the README
3. run `npm run serve` for your project
4. Javascript console throws an error stated above

**Expected behavior**
Simplebar-vue renders without an issue

**Reproducible example**

https://codesandbox.io/s/naughty-star-9mup4

Also, run the example in this repository. You get the same results.

**Additional context**
If you make a few changes to the example [App.vue](https://github.com/Grsmto/simplebar/blob/master/examples/vue/src/App.vue) and install `simplebar` as a dependency for the example, simplebar-vue works as expected

```
import simplebar from '../../../packages/simplebar-vue/index';  //import simplebar from 'simplebar-vue';
import 'simplebar-core/dist/simplebar.min.css'; // import 'simplebar/dist/simplebar.min.css';
```
I wasn't able to recompile simplebar-vue but it looks like a simple recompilation could resolve the issue

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        |6.0.0-beta.2
| Browser          | Chrome 84
| npm/Yarn         | npm 6.14.4
| Operating System | Win 10

**Comment by Grsmto** [comment]
Released a fix in `simplebar-vue@2.0.0-beta.3`.
