### ISSUE TITLE
IE11 broken

### ISSUE THREAD

**Issue by eugenem** [Grsmto/simplebar#506]
Something seems to be broken recently (it was working a few days before).

At IE11 I get the following error:

simplebar.js (2076,41)

it's this line:
`window.addEventListener('resize', () => {`

**Comment by eugenem** [comment]
5.2.1 is working fine. So I've downgraded meanwhile.

**Comment by ElForastero** [comment]
`beta.7` (at least) is broken in IE11 due to using of arrow function inside addEventListeter.


![image](https://user-images.githubusercontent.com/5102818/95466215-28886c00-098d-11eb-985d-a51d12e512bc.png)

**Comment by Grsmto** [comment]
Latest version has been tested fine in IE11, so closing this! Thanks!
