### ISSUE TITLE
Initializing SimpleBar on a hidden element

### ISSUE THREAD

**Issue by ineentho** [Grsmto/simplebar#51]
If you initialize SimpleBar while the element is hidden, you have to manually call recalculate when the element is visible for the first time. In addition, if you want to use `autoHide: false`, you have to run flashScrollbars to show the scrollbar.

JSFiddle showing the problem: https://jsfiddle.net/5jjrm039/1/

As I wrote in #42, we run
```
if (simpleBar.el.style.overflow !== 'auto') {
  this.simpleBar.recalculate();
  this.simpleBar.flashScrollbar();
}
```
when we show an element that contains a SimpleBar element.

v2.0.1 improved the situation by providing `.enabled`, but is there any way to make this more convenient? I'd imagine it's a quite common inconvenience in many more app-y websites.

Is it possible to detect when the element turns visible with MutationObservers without adding listeners to all parent elements? Otherwise I would propose a `refresh` function that works something like this:
```
refresh () {
  if (!this.enabled) {
    return;
  }

  this.recalculate();

  if (!this.options.autoHide) {
    this.showScrollbar('x');
    this.showScrollbar('y');
  }
}
```

Any thoughts?

**Comment by Grsmto** [comment]
Yeah as you guessed the only way to detect if the element is visible I think is to observe every parent cause as soon as it's a parent that turns hidden/visible the SimpleBar element won't be notified I think...
Also I believe this bug probably happen only if the element is `display: none` and so the browser can't calculate the right values. Should work fine if you `visibility: hidden` instead right?

That's a recurrent issue with any library doing DOM manipulations I think...this has side effects and we can patch them but I feel like there's always gonna be scenarios where it breaks things.

I will dig it a bit and see how we could make this more convenient but your solution would work fine of course.

Thanks again for this :)

**Comment by armhov** [comment]
Hi, i'm using the latest version of simplebar  (//cdn.jsdelivr.net/npm/simplebar@latest/dist/simplebar.js') and as i can see, there is not flashscrollbar function, what i'm need to use instead of flashscrollbar function
( this.simpleBar.recalculate();
  this.simpleBar.flashScrollbar();
)

**Comment by Grsmto** [comment]
Just `recalculate();`. 
`flashScrollbar()` has been removed in the latest version.
