### ISSUE TITLE
css doesn't get bundled in gatsby build due to `sideEffects: false`

### ISSUE THREAD

**Issue by carljohnesan** [Grsmto/simplebar#511]
Title says it all, styles file doesn't get bundled in gatsby build because  of `sideEffects` set to `false` in package.json, solution is to set `sideEffects` to `["*.css"]`, or simply to `true`

**Comment by carljohnesan** [comment]
Why npm distribution of the library still has `sideEffects: false` ?

**Comment by Grsmto** [comment]
Should be fixed.
