### ISSUE TITLE
Simplebar bug with no changes online

### ISSUE THREAD

**Issue by nicleg** [Grsmto/simplebar#517]
**Describe the bug**
Few days ago my website was broken, while investigating I saw that simpeBar wasn't working.
My website wasn't touch since it was working great (I uploaded it 3 monthes ago).
I used this link to load SB : https://cdn.jsdelivr.net/npm/simplebar@latest/dist/simplebar.js
In the "same" time, simpleBar installed on a website I developping crash the same with the same link used.
Both are running with wordpress latest version, perhaps this could be a clue.

I've found just one codepen Simplebar example running and it uses : 
"https://cdn.jsdelivr.net/npm/simplebar@3.1.3/dist/simplebar.css"
and if you change by this (latest version) : 
https://cdn.jsdelivr.net/npm/simplebar@latest/dist/simplebar.js
its crashes

have fun, I hope it helps.

**Comment by eriqamiqo** [comment]
@nicleg 

same problem with my web apps. when i accessed the @latest version, it's using the 6.0.0-beta

i tried using the 5.2.* version and it's working again.

https://www.jsdelivr.com/package/npm/simplebar?version=5.2.0&path=dist

**Comment by nicleg** [comment]
@eriqamiqo,

THANK'S !

You save (the rest of) my day !
Using version 5.2 resolve my problem !

At least, you can check and discover my work :) https://nicolaslegall.fr
Nico.

**Comment by jordankeen** [comment]
@eriqamiqo Thanks for this, was wondering what happened to my beautiful scroll bars!

**Comment by Grsmto** [comment]
Sorry about this people, I unintendedly overrided the latest version with the beta version.
This should be fixed from on.

Thanks for the report!
