### ISSUE TITLE
"new SimpleBar()" class equivalent when using native javascript - if my title makes sense

### ISSUE THREAD

**Issue by patricksabado** [Grsmto/simplebar#519]
Hello,

I don't want to use any fancy loaders, what I did was include the source directly via the <script> tag. I want to dynamically initialize the scrollbar plugin once my modal opens up. I read your documentation and it says that I need to do

new SimpleBar(element)

however, this returns an "undefined" error. Is this not possible if you are not using fancy js stuff? I'm using v5.0.7. I know I'm just missing something and I don't what know could that be.

**Comment by Grsmto** [comment]
Hi,
This should work the way you describe. If you can provide the exact error you're getting, maybe we could help.

**Comment by patricksabado** [comment]
Hi,

so I need to initiate your plugin at a certain event lets say.

$(document).on('click', '#somebutton', function() {
new SimpleBar(<required_parameters>);
});

my problem is, I am getting the SimpleBar "undefined" error. When I check the javascript file for the simplebar plugin I couldn't find or I couldn't see any text occurrence of "SimpleBar" - or maybe since it is minified it could be replaced by a shorter variable.

But yeah the class is undefined for me.

**Comment by Grsmto** [comment]
Hey, this is very strange. What version are you using? 
Check this example that is doing pretty much what you said: [https://jsfiddle.net/Grsmto/gj0wLk2u/5/](https://jsfiddle.net/Grsmto/gj0wLk2u/5/)

**Comment by patricksabado** [comment]
all good, I removed the js bundling in our project and it reveals it is actually using require.js - means I have to do it in a fancy way. Thanks for all the help.
