### ISSUE TITLE
Update website with latest version demo

### ISSUE THREAD

**Issue by sanyashvets** [Grsmto/simplebar#52]
Always getting error with scrollbarwidth on init in 2nd version

**Comment by Grsmto** [comment]
Can you explain the issue? At least give the error message you are having?

**Comment by sanyashvets** [comment]
I`m sorry a lot. That was my bad. I have unusual plugin installation, but I solved this problem. Can I ask you to update plugin on your [demo ](http://grsmto.github.io/simplebar/demos/) site? That would be great for users and not so confusing for a first view)

**Comment by Grsmto** [comment]
Yes that's a good suggestion! I will do that. Thanks!

**Comment by sanyashvets** [comment]
Also I have some problems with width determination with flex model.
I have parent div with flex: 0 0 250px, but plugin makes width of child div = 260px (250 basis + 10px scrollbar) and scrollbar is visible. Of course, I can use width with flex-basis, but that isnt good in my opinion(
Is there other ways to support flex? As I see, a lot of plugins have no idea how to work with flex)

**Comment by Grsmto** [comment]
Hey, I used Simplebar with flexbox without problem. I think your issue may be too specific for me to understand where it comes from. Hope you found a solution!
