### ISSUE TITLE
Scrollbars not shown in version 5.x when scrollbar is dynamically added to the page

### ISSUE THREAD

**Issue by ajssd** [Grsmto/simplebar#522]
## Current Behavior

We are using the data-simplebar="init" syntax to apply a custom scrollbar to an absolutely-positioned DIV with fixed dimensions and some padding. Some of the content inside the div is rendered dynamically using Knockout.js.  In v5.0.3 the scrollbar renders correctly, but in v5.0.4, it does not -- at least initially.  I suspect the dynamic content is the issue because after the cache "warms up" then things are ok.  But on the initial render, when the UI takes longer to paint, the scrollbar never appears.

## Expected behavior

Scrollbar should appear when contents exceed the height of the allocated space.

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.0.4 and higher
| Browser          | Chrome (latest)
| npm/Yarn         |
| Operating System | macOS

**Comment by ajssd** [comment]
Interesting symptom: when this happens, on Chrome (macOS) I cannot scroll at all, with trackpad or mouse.  But the same UI on Safari, I can scroll fine -- but I don't see the scrollbar.  As before, if I leave the UI and come back, then the scrollbar appears in both browsers and everything is fine.  It's only the initial render.  With v5.0.3 there is no problem.  Only v5.0.4 and higher (including v5.2.1).

**Comment by ajssd** [comment]
Same thing is seen with v5.3.0.  Here is a little more info, feel free to reach out if you need more.

The `<div data-simplebar>` is being dynamically loaded into the DOM, using knockout.js.  I can see that the SimpleBar code is detecting it, because after the `<div>` is injected into the DOM, I can see all the `div`s that SimpleBar creates, e.g.:
```
> document.querySelector('[data-simplebar]')

<div class="oj-form scs-settingsPanel scs-panel-current" data-simplebar="init">
<div class="simplebar-wrapper" style="margin: 0px -10px;">…</div>
<div class="simplebar-track simplebar-horizontal" style="visibility: hidden;">…</div>
<div class="simplebar-track simplebar-vertical" style="visibility: hidden;">…</div>
</div>
```

But if I list the SimpleBar instances, it's not there (and the DIV cannot be scrolled)
```
> SimpleBar.instances.get(document.querySelector('[data-simplebar]'))

undefined
```

Next if I manually apply the SimpleBar like this
```
> new SimpleBar(document.querySelector('[data-simplebar]'))
```
then when I list the instances, I see it (and now the DIV *can* be scrolled)
```
> SimpleBar.instances.get(document.querySelector('[data-simplebar]'))

SimpleBar {onScroll: function, scrollX: function, scrollY: function, onMouseEnter: function, onMouseMove: function, …}
```

**Comment by Grsmto** [comment]
Do you think you could provide a reproductible example? For example using this one as a base: [https://jsfiddle.net/Grsmto/gj0wLk2u/](https://jsfiddle.net/Grsmto/gj0wLk2u/) that would help a lot to investigate the issue.
Thanks.

**Comment by ajssd** [comment]
Sure -- are you able to see this?
https://jsfiddle.net/asefkow/dn1k7maj/

**Comment by ajssd** [comment]
HI there -- I created a jsfiddle -- you can see how the scrollbar is missing.  
https://jsfiddle.net/asefkow/dn1k7maj/

I am using macOS Safari 14.0, FWIW.
-Andy

    On Friday, October 2, 2020, 05:18:10 PM PDT, Adrien Denat <notifications@github.com> wrote:  
 
 


Do you think you could provide a reproductible example? For example using this one as a base: https://jsfiddle.net/Grsmto/gj0wLk2u/ that would help a lot to investigate the issue.
Thanks.

**Comment by ajssd** [comment]
@Grsmto this still reproduces in the 5.3.4 that was released last week.  https://jsfiddle.net/asefkow/dn1k7maj demonstrates the problem.  When the green scrolling region is dynamically added to the page, the scrollbars are not seen.

**Comment by Grsmto** [comment]
I'll close this as I think something is going on with the framework you are using that doesn't deal well with the automatic instantiation of simplebar.
I would advice to use the manual instantiation with `new SimpleBar()` when the framework is ready instead!
