### ISSUE TITLE
How to change the opacity transition?

### ISSUE THREAD

**Issue by ArutanSipdrae** [Grsmto/simplebar#530]
In its current state when I add the autoHide props, the scrollbar disappears and reappears only when hovering/scrolling, which is what I want. But when reappearing, it doesn't reappear with an opacity of 1 and I don't know how to change this behaviour.

**Comment by tanzy242** [comment]
`.my-class.simplebar-scrollbar.simplebar-visible:before {
    opacity: 1;
  }`

I have added 'my-class' to increase the specificity to override the default style

**Comment by tanzy242** [comment]
> In its current state when I add the autoHide props, the scrollbar disappears and reappears only when hovering/scrolling, which is what I want. But when reappearing, it doesn't reappear with an opacity of 1 and I don't know how to change this behaviour.

`.my-class.simplebar-scrollbar.simplebar-visible:before {
    opacity: 1;
  }`

I have added 'my-class' to increase the specificity to override the default style
