### ISSUE TITLE
Built version numbers are one version behind

### ISSUE THREAD

**Issue by MikaelLambert** [Grsmto/simplebar#54]
Hi, I like your library so far it's very good, keep up the good work! 👍

The built version numbers appear to be 1 version behind. You can observe the issue by viewing the following files. They display version 2.0.2 but I've verified that it is indeed version 2.0.3 code.

https://unpkg.com/simplebar@2.0.3/umd/simplebar.css
https://unpkg.com/simplebar@2.0.3/umd/simplebar.js

NPM has the same issue if you open the files

 ~/node_modules/simplebar/umd/simplebar.css
 ~/node_modules/simplebar/umd/simplebar.js

**Comment by Grsmto** [comment]
Hey thank you Mikael! This is a mistake from me having troubles doing the NPM release properly :)
I will take care of doing that well for the next release :p
