### ISSUE TITLE
Scrollbar is (briefly) visible when attached to a hidden div

### ISSUE THREAD

**Issue by taras-slapdash** [Grsmto/simplebar#542]
**Describe the bug**
When the scroll bar is attached to a div which is hidden (`visibility: hidden`) the scroll bar's track is briefly visible on the page.

**To Reproduce**
1. Create a `div` with some content (make sure it's long enough) and set `visibility: hidden` and `height` to something that will trigger the scroll bar to appear.
2. Attach SimpleBar to this `div`.
3. Open the page in the browser (tested in Chrome/Safari on macOS) and notice that the scroll bar's track is visible for a few seconds (even though the content is hidden). 

**Expected behavior**
The scroll bar's track should not be visible when its content is hidden.

**Reproducible example**

Can provide if needed.

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | v2.3.0 |
| Browser          | Chrome 86 |
| Operating System | macOS, Big Sur|

**Comment by Grsmto** [comment]
We hide the native scrollbar entirely with CSS now so shouldn't happen anymore. Thanks!
