### ISSUE TITLE
Get scroll thumb drag events

### ISSUE THREAD

**Issue by sanbornhilland** [Grsmto/simplebar#545]
Is there an obvious way to hook into the drag events of the scroll thumb? One of the reasons that I am looking to a package that replaces native scrollbars is for the ability to handle the drag events directly. However the core package here blocks a bunch of event propagation so I'm having trouble finding a way to handle drag events. Thanks.

Edit: I should point out that I'm using the `React` version of this library which may complicate things a bit for cleanly getting drag events.

**Comment by sanbornhilland** [comment]
It took me a while but I finally realized that the class `simplebar-dragging` is applied to the outer container so that solves my problem. I can detect if that is set during a scroll event to determine if scrolling is triggered by dragging.

**Comment by side9527** [comment]
> It took me a while but I finally realized that the class `simplebar-dragging` is applied to the outer container so that solves my problem. I can detect if that is set during a scroll event to determine if scrolling is triggered by dragging.

but if there are two scrollbars on the page, you don't know which one is currently being dragged
