### ISSUE TITLE
Missing support for virtual lists

### ISSUE THREAD

**Issue by alekstar79** [Grsmto/simplebar#546]
There is not enough support for virtual lists. For some reason, you will not find any implementation of virtual lists with custom scrollbars on the Internet at all. Either custom scrollbars for regular lists, or a virtual list with a system scrollbar.

**Comment by Grsmto** [comment]
If you are using React, you can find an example using `react-window` [there](https://github.com/Grsmto/simplebar/blob/next/packages/examples/Demo.js#L280).

**Comment by alekstar79** [comment]
Unfortunately, I don't use React. I work with Nuxt (Vue).

**Comment by tlthiem** [comment]
@Grsmto This demo does not work for me.
Is there a live version of the example file?
Is this referening to an old version?
I checked `package.json` seems to be indicating that `"simplebar-react": "^3.0.0-beta.10"` is correct?.

**Comment by Grsmto** [comment]
@tlthiem I think it should work with both latest beta that you pointed out and also with `simplebar-react@2.4.2`.
You might find it buggy tho because I didn't have time to release simplebar-react v3 unfortunately...

**Comment by tlthiem** [comment]
@Grsmto Thanks fot the quick response.
 I created a minimal Sandbox. Does not seem to work sadly. 
Do you know of a different approach that may work? 

Sandbox: https://codesandbox.io/s/frosty-feistel-siwupy?file=/src/App.js

**Comment by gwendall** [comment]
I created a component for it, you can use it like a regular `FixedSizeList`. Don't forget to import the simplebar css.

https://gist.github.com/gwendall/7b04b571dcd8e19ec613b2f35d77a5bc
