### ISSUE TITLE
React to scrollbar overflow changes

### ISSUE THREAD

**Issue by Pipas** [Grsmto/simplebar#547]
I'm using simplebar in react and would like to style some of my content differently according to if a scrollbar is needed, this is if there is overflow on the component, or not.

I have tried reading the overflow from a reference to the scrollbar element but it only updates after all the components are already build so when the building is happening it has no overflow and if the next build the overflow is no longer necessary, it reads that it has overflow from the previous build.

What is the best way to go about solving this problem?

**Comment by Grsmto** [comment]
There are now new classes on the host element for that! Thanks!
