### ISSUE TITLE
Not recalculating with percentage widths/heights

### ISSUE THREAD

**Issue by onomori** [Grsmto/simplebar#55]
Is this expected behavior? Using absolute widths and changing it through inspect element does make it recalculate but when a div is set to, say, 50% and you resize the window, the `.simplebar-scroll-content`'s width stays the same as it was first calculated.

Made a fiddle to show it: https://jsfiddle.net/pctt4d6k/

Resizing the output window shows how the content isn't resizing width the main div because `.simplebar-scroll-content`'s width isn't changing. Another thing is when this happens, the horizontal scroll bar that appears doesn't work either. Am I getting something wrong or missing anything?

**Comment by Grsmto** [comment]
Thanks for this. You pointed a big issue, the MutationObserver doesn't catch css changes so the recalculate function doesn't get triggered.
The only solution I see right now would be using something like https://github.com/que-etc/resize-observer-polyfill

**Comment by IrvingArmenta** [comment]
Hello, I think my issue is related, here is a jsfiddle: https://jsfiddle.net/r1aqmop4/ 

Could you illustrate how to use the polyfill with the plugin? I'm not very avid with modern js.

Thanks
