### ISSUE TITLE
Nesting bars in latest version wrecks inner ones

### ISSUE THREAD

**Issue by CaptinJackSparow** [Grsmto/simplebar#552]
**Describe the bug**
Whenever initializing simplebar inside a simplebar, the inside one breaks and either the scroll bar doesn't show if it is set to autohide or it is frozen in place if it is forced to visible. 

**To Reproduce**

1. Create the following with JS
2. Create a div with set height and assign simplebar or activate simplebar with any method.
2. Create a div inside this div with a set height that is smaller than the outer div 
and assign or create simplebar with any method
3. Try scrolling in the inner div, it doesn't show the simplebar

**Expected behavior**
Simplebar should be showing in nested divs

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | Latest - link in HTML
| Browser          | Chrome
| Operating System | Windows 10

Since I have found if I do a get request and add the inner simplebar divs with that much time difference and the scrolling works for all items... however, to create a layout where it has an outer simplebar and inner simplebar at once and the inner ones break.
Having it take some time to build the inner ones afterward allows it to work.

**Comment by norin89** [comment]
I'm experiencing the same issue in my app. Latest working version for me is `5.0.3`. I tried to reproduce on JSFiddle but everything seems to work well there. I'll make attempt 2 of reproduction soon.

**Comment by mordatiy** [comment]
@CaptinJackSparow thanks!
timeout for inner (nested) SimpleBar really decides problem

**Comment by andersk** [comment]
I found a reproduction recipe for this issue: https://jsfiddle.net/anderskaseorg/Ltp1wjz7/1/

The problem is that
1. the outer SimpleBar constructor rearranges the DOM, triggering mutation events;
2. the inner SimpleBar constructor runs;
3. the mutation observer sees the events from step 1, incorrectly concludes that the inner SimpleBar has been removed, and so destroys it.

**Comment by Grsmto** [comment]
Thanks! Released in latest version.
