### ISSUE TITLE
RTL direction - on click and move, the scrollbar will not follow the mouse right away

### ISSUE THREAD

**Issue by ion-ciubaciuc** [Grsmto/simplebar#554]
**Describe the bug**
RTL direction - click and drag the scrollbar is not working properly.

**To Reproduce**

1. Go to https://codepen.io/ion-ciubaciuc/pen/ExNRWKj
2. If you drag the scrollbar in LTR, you'll see that everything works as expected (scrollbar follows the mouse).
3. Click the scrollbar in RTL and drag it to the left.
4. Notice that the scrollbar will start moving when the mouse arrow is not above the scrollbar anymore  

**Expected behavior**
When you click on scrollbar in RTL mode, it should follow the mouse right away.

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.3.0
| Browser          | Safari 14, Chrome 88, Firefox 86
| Operating System | MacOS 11

**Comment by melodyfang** [comment]
+1

**Comment by TBschen** [comment]
Also happens on the official example page. It is less noticable because of the size, though I wonder how long the issue went unnoticed.

**Comment by yunusga** [comment]
Still same error. v6.2.0
