### ISSUE TITLE
Should support react 17

### ISSUE THREAD

**Issue by linonetwo** [Grsmto/simplebar#558]
https://github.com/Grsmto/simplebar/blob/a0611f7bc31a45970f2f3f645c5f6eee47812f77/packages/simplebar-react/package.json#L39

ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tiddly-git@0.3.6
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   dev react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.3.0 || ^16.0.0-rc || ^16.0" from simplebar-react@3.0.0-beta.10
npm ERR! node_modules/simplebar-react
npm ERR!   dev simplebar-react@"3.0.0-beta.10" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by sanbornhilland** [comment]
Supporting React 17 might be more than just a peer dependency update. React 17 seems to introduce a small breaking change with the `onScroll` handler.

React 16 allows `onScroll` being attached to `SimpleBar` directly like:

```jsx
<SimpleBar onScroll={...}></SimpleBar>
```

This breaks in React 17 for a reason that is not clear to me. In React 17 you need to use this form of the `onScroll` handler:

```jsx
<SimpleBar scrollableNodeProps={{
  onScroll() {...}
}}></SimpleBar>
```

There is a reproducer here: https://codesandbox.io/s/trusting-flower-butid?file=/src/App.js. If you use React 16.x you can see that both forms work. In React 17.x the top version stops firing.

**Comment by skiminock** [comment]
@Grsmto do you have any plans for update *simplebar* for react 17.x in near future?

**Comment by manishoctal** [comment]
The CoreUI team is using React 17, Someone needs to work on support on this.

**Comment by alixsep** [comment]
I really want to see an update for this please make it happen 🙏

**Comment by rismantrdr** [comment]
i also had this problem. I hope it can happen in the future

**Comment by mogzol** [comment]
The reason for the issue @sanbornhilland mentioned is that [the `onScroll` event in React v17 no longer bubbles](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#aligning-with-browsers). I would argue that this isn't even an issue with simplebar-react, it's just how React 17 works.

Other than that, I haven't run into any issues using simplebar on React 17, I think that it would be safe to update the package.json for simplebar-react to allow react and react-dom v17 without making any other changes.
