### ISSUE TITLE
Error: Property 'placeholder' of type 'string | undefined' is not assignable to string index type 'string'.  24         [className: string]: string;

### ISSUE THREAD

**Issue by evgeniykorablev** [Grsmto/simplebar#564]
**Describe the bug**
Error: node_modules/simplebar/dist/simplebar.d.ts:24:9 - error TS2411: Property 'placeholder' of type 'string | undefined' is not assignable to string index type 'string'.
[className: string]: string;

**To Reproduce**
Angular build in strict mode.

ng build, ng serve.

**Expected behavior**
Should not be error.

**Reproducible example**

**Additional context**

**Your environment**

"@angular/animations": "^11.2.7",
    "@angular/cdk": "^11.2.6",
    "@angular/common": "^11.2.7",
    "@angular/compiler": "^11.2.7",
    "@angular/core": "^11.2.7"
    "simplebar": "^5.3.0",

**Comment by Grsmto** [comment]
Closing this since codebase has changed a lot since then. Re-open a new issue if needed.
