### ISSUE TITLE
Double scrollbar on iOS and iPadOS

### ISSUE THREAD

**Issue by thisisrandy** [Grsmto/simplebar#568]
**Describe the bug**
On iOS and iPadOS (iPad 6 & 7, iPhone 6, Safari & Chrome tested), both the native scrollbar and simple bar are visible. The result is as below using your react demo:

![simplebar-react-double-scrollbar](https://user-images.githubusercontent.com/22106562/120087437-c788e200-c09c-11eb-9f55-8081f2dc6151.jpg)

I am aware that this is a duplicate of #445, but as that issue is old and seems to provide a (ultimately unhelpful) "solution" at the bottom of the thread, it seems cleaner to start a new issue with better evidence of the problem. Apologies if you feel this pollutes your issues store. Please direct me to add to #445 and close this if you feel that is best.

**To Reproduce**

1. Go to any of the simplebar demo pages on a device running iOS or iPadOS (see above for tested devices and browsers).
2. Scroll, observing that simplebar and the native scrollbar overlap.

**Expected behavior**

Only simplebar should be visible regardless of the device used.

**Reproducible example**

https://grsmto.github.io/simplebar/examples/
https://codesandbox.io/s/simplebar-react-gwgyw
(etc.)

**Additional context**
Occasionally, and by that I mean apparently nondeterministically, the native scrollbar will *not* be present. This can change literally between reloads of the exact same content. Using your examples page, here is a screencap of no native scrollbars:

![examples without](https://user-images.githubusercontent.com/22106562/120087761-8b0ab580-c09f-11eb-96bc-5a5f606a52ed.jpg)

Followed by moments later after a reload, this:

![examples with](https://user-images.githubusercontent.com/22106562/120087769-9958d180-c09f-11eb-8a73-cfb55e39dc97.png)

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.3.3
| Browser          | Safari/Chrome
| Operating System | iOS/iPadOS

**Comment by alexbchr** [comment]
I think the issue is caused by iOS 14 no longer supporting custom CSS for scrollbars. See this [link](https://developer.apple.com/forums/thread/670065) for reference.

We have the same issue with Simplebar as well on iOS 14 devices.

I can't see any way to fix this except setting `overflow: hidden` on the container, but simplebar will probably break then...

**Comment by thisisrandy** [comment]
@alexbchr, that's an interesting find, but please bear in mind that I am reporting this issue on older devices. iPhone 6, for example, is running iOS 12.5.4 as of this writing. OP on that thread claims that their custom scrollbar worked just fine on iOS 12. There's also some ambiguity there about whether the issue was confined to Safari. I observed this issue on both Safari and Chrome on the devices mentioned above.

That said, I am curious which devices/browsers/OS versions you have ready access to that display this same behavior. Could you provide some details, please?

**Comment by alexbchr** [comment]
@thisisrandy We are using an iPhone 11 Pro on iOS 14.6.

> iPhone 6, for example, is running iOS 12.5.4 as of this writing.

Then maybe our issue for iOS 14 is different 🤔 However, we tried multiple CSS fixes for this issue without success. Also, our issue is not intermittent but always present. The second scrollbar (native one), appears as soon as we scroll.

**Comment by thisisrandy** [comment]
@alexbchr, the intermittent portion of the bug is definitely strange. While I don't have any strong evidence one way or the other, I'm actually inclined to believe that might be a separate issue not having to do with simplebar at all. I see some "iOS scrollbar intermittently invisible" hits in a [cusory search](https://discussions.apple.com/thread/8447471). Maybe best to focus on why simplebar isn't successfully hiding the native scrollbar at all times.

As to whether the issue's cause is different on iOS 14, it's hard to say. The forum post you linked, while purportedly from an Apple employee, was terse and failed to link any sort of official release notes or the like, so I'm hesitant to treat it as authoritative. Maybe it's true and was also backported to a maintenance release for older devices, in which case this isn't a fixable issue on any version of iOS, but we're getting into some pretty speculative territory here. Hopefully someone can chime in with something more concrete.

Also, re:

>I can't see any way to fix this except setting overflow: hidden on the container, but simplebar will probably break then...

Correct, doing so disables scrolling altogether.

**Comment by romancfischer** [comment]
+1
