### ISSUE TITLE
Horizontal Scrolling with Mouse Wheel

### ISSUE THREAD

**Issue by JoshClose** [Grsmto/simplebar#57]
How would you recommend changing the scroll wheel to scroll horizontally on an area that only scrolls horizontally?

**Comment by Grsmto** [comment]
You can use the `wheel` event as described here: https://developer.mozilla.org/en-US/docs/Web/Events/wheel#Listening_to_this_event_across_browser

Listen to this event on the SimpleBar element and then trigger scroll with something like this:
```
el.SimpleBar.getScrollElement().scrollTo(deltaY, 0)
```

**Comment by JoshClose** [comment]
There doesn't seem to be a `scrollTo` method. 

This did work though.

```javascript
e.currentTarget.SimpleBar.getScrollElement().scrollLeft += e.deltaY;
```

Anything wrong with that?

**Comment by Grsmto** [comment]
Hmm you're right, `scrollTo` is only on the window element! My bad :)
Nothing wrong with what you did I think.

**Comment by strarsis** [comment]
@Grsmto: Is this feature available in latest version?
If not, could horizontal scrolling by mouse-wheel be added as a feature?
Or are there libraries that can be used that add this the right way?

**Comment by ch3rn1k** [comment]
Well, I'm using this solution:

``` js
let horizontalElements = document.querySelectorAll('[data-simplebar]');
for (let element of horizontalElements)
element.onwheel = (event) => {
  event.preventDefault();
  let elementToScroll = element.querySelector('.simplebar-content-wrapper');

  clearTimeout(elementToScroll.timer);
  elementToScroll.timer = setTimeout(() => {
    elementToScroll.scrollTo({ left: event.deltaY > 0 ? elementToScroll.scrollLeft + 250 : elementToScroll.scrollLeft - 250, behavior: 'smooth' });
  }, 20);
};
```

But anyway I haven't found a solution for firefox glitchy bug on scroll. Works fine in chrome.

**Comment by strarsis** [comment]
@ch3rn1k: Thanks for the example code. It would be great if such a functionality is implemented in this library and take all the browsers into account.

**Comment by Al-Sharif** [comment]
> Well, I'm using this solution:
> 
> ```js
> let horizontalElements = document.querySelectorAll('[data-simplebar]');
> for (let element of horizontalElements)
> element.onwheel = (event) => {
>   event.preventDefault();
>   let elementToScroll = element.querySelector('.simplebar-content-wrapper');
> 
>   clearTimeout(elementToScroll.timer);
>   elementToScroll.timer = setTimeout(() => {
>     elementToScroll.scrollTo({ left: event.deltaY > 0 ? elementToScroll.scrollLeft + 250 : elementToScroll.scrollLeft - 250, behavior: 'smooth' });
>   }, 20);
> };
> ```
> 
> But anyway I haven't found a solution for firefox glitchy bug on scroll. Works fine in chrome.

Thank you ch3rn1k, worked for me.

**Comment by Al-Sharif** [comment]
Thank you @ch3rn1k  , worked for me.

**Comment by bacvietswiss** [comment]
Thank you @ch3rn1k , it works nicely for me
