### ISSUE TITLE
Simplebar-Angular - onDestroy issue

### ISSUE THREAD

**Issue by ThePatzen** [Grsmto/simplebar#572]
**Describe the bug**
When SimplebarComponent gets destroyed it throws an exception.

**To Reproduce**
Hard to say.

**Expected behavior**
I think you should check in SimplebarAngularComponent if simplebar is not undefined before unmounting it!

**Additional context**
```
Error: Uncaught (in promise): TypeError: Cannot read property 'unMount' of undefined
TypeError: Cannot read property 'unMount' of undefined
    at SimplebarAngularComponent.ngOnDestroy (simplebar-angular.js:33)
**Your environment**

```
| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 3.0.0-beta.10

**Comment by nizamial09** [comment]
any idea why this happens? For me its started happening on the unit tests once the angular is updated to angular 13 and the jest is updated to 28, but surprisingly not in the browser.

**Comment by nizamial09** [comment]
I was on version `2.4.1` and now I reduced it to `2.2.1` and there I am facing no issues.
