### ISSUE TITLE
Upgrade to Angular 12

### ISSUE THREAD

**Issue by woteska** [Grsmto/simplebar#577]
## Current Behavior

Get warnings when installing via simplebar-angular package.
```
npm WARN simplebar-angular@2.3.4 requires a peer of @angular/common@^8.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN simplebar-angular@2.3.4 requires a peer of @angular/core@^8.1.3 but none is installed. You must install peer dependencies yourself.
```

## Expected behavior

No warnings. 

## Suggested solution(s)

Upgrade to latest Angular.

**Comment by ihor-bobyr** [comment]
same issue

**Comment by rekomat** [comment]
@ihor-bobyr Probably the option `--legacy-peer-deps` would have the same effect as downgrading npm.

**Comment by Grsmto** [comment]
This should be done in latest version.
