### ISSUE TITLE
Show scroll bar on container hover before scroll starts

### ISSUE THREAD

**Issue by Bilal-io** [Grsmto/simplebar#58]
Hello,

Is there anyway to make the scrollbar appear on hover instead of waiting until I start scrolling?
I've seen this on Facebook Messenger www.messenger.com and it seems like a better UX.

Thank you

**Comment by Grsmto** [comment]
Hi Bilal,
It is supposed to work this way already. If it doesn't there is probably a
issue!

**Comment by Bilal-io** [comment]
Hi @Grsmto,
That's really weird, I am on Mac 10.12.3, tested your own demo on Chrome, Firefox and Safari latest versions and the scrollbar doesn't appear automatically, only when I start scrolling.

I also had a friend try it on their Windows 8 machine, used Chrome. They reported the same issue. 
I hope you can look into that. 
Thank you.

**Comment by Grsmto** [comment]
Hey Bilal, I tested and actually the native mac osx implementation (that will be triggered if you're on a mac with no mouse plugged) doesn't display the scrollbar on hover. The messenger.com implementation is custom.
Then I double checked SimpleBar and it seems like when it's the custom scrollbar triggered, it does have the behaviour you described (on Mac try to activate it in System Preferences > General > Show scroll bars: always) and visit the SimpleBar demo again and let me know

**Comment by Bilal-io** [comment]
I did that, activate 'Always' under Show Scroll Bars, and that fixed it on SimpleBar demo, but it messed things up on my demo. 
One container was still scrollable without showing the scroll bar at all, and a second was't event scrollable, the overflow:hidden wasn't added to it, but the html was changed (3 divs with classes " simplebar-track vertical" "simplebar-track horizontal" "simplebar-scroll-content") I noticed that I noticed when the Show Scroll Bars is "Automatically based on mouse or trackpad" the html isn't generated.

**Comment by Grsmto** [comment]
It's not very clear but read this part of the readme: https://github.com/Grsmto/simplebar#mobile-support
SimpleBar activates only when the device doesn't use "floating scrollbars".
However if you want to have SimpleBar always on, you can use the option `forceEnabled`.
