### ISSUE TITLE
data-simplebar-auto-hide not working in Nuxt.js

### ISSUE THREAD

**Issue by nevadavid** [Grsmto/simplebar#585]
`data-simplebar-auto-hide` attrs (or props) not working in Nuxt.js.

I created this "wrapper" component  for simplebar:

```javascript
import simplebar from 'simplebar-vue';
import 'simplebar/dist/simplebar.min.css';

export default {

	name: 'c-simplebar',

	render(h) {
		return h(
			'client-only',
			[
				h(
					simplebar,
					{
						attrs: { // or props
							'data-simplebar-auto-hide': false,
						},
					},
					this.$slots.default,
				),
			],
		);
	},

};
```

| Software         | Version(s) |
| ---------------- | ---------- |
| simplebar-vue        | 1.6.7 |
| nuxt | 2.15.7 |
| Browser          | Chrome 92 |
| Operating System | Ubuntu |

**Comment by phikko** [comment]
I am probably late for the party but for someone who has this problem:
Since `data-simplebar-auto-hide` isn't a prop but an attribute it needs to be passed as a string.
```js
'data-simplebar-auto-hide': false
// change it to:
'data-simplebar-auto-hide': 'false',
```
Now it should work as intended

**Comment by nevadavid** [comment]
> I am probably late for the party but for someone who has this problem:
> Since `data-simplebar-auto-hide` isn't a prop but an attribute it needs to be passed as a string.
> 
> ```js
> 'data-simplebar-auto-hide': false
> // change it to:
> 'data-simplebar-auto-hide': 'false',
> ```
> 
> Now it should work as intended
> 
> Explanation why it won't work with boolean value:
> In Vue when boolean value is passed to attribute it corresponds whether attribute is present or not
> 
> ```
> <button :disabled="true">Button</button>
> // becomes
> <button disabled>Button</button>
> 
> <button :disabled="false">Button</button>
> // becomes
> <button>Button</button>
> ```
> 
> Attribute is not present on rendered DOM element thats why it won't work as you thought it would.
> String value behaves as you thought because it renders the attribute regardless of the value

Thank you, it works!
