### ISSUE TITLE
Vue Options | Recalculate

### ISSUE THREAD

**Issue by ricnunes** [Grsmto/simplebar#588]
## Current Behavior

vue.esm.js?65d7:1693 TypeError: Cannot read property 'recalculate' of undefined

## Expected behavior

Recalculate to run

## Reproducible example

`watch: {
      '$parent.isOpen' (newVal, oldVal) {
        if (newVal) {
          this.simplebar.recalculate()
        }
      }
    }`

## Additional context

There's no documentation for the options on the different frameworks, so I'm just guessing. What should be the correct option for this?

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        |  1.6.7
| Browser          | 92.0
| Operating System | MacOs

**Comment by Grsmto** [comment]
Solved in [simplebar-vue@1.7.0](https://github.com/Grsmto/simplebar/releases/tag/simplebar-vue%401.7.0).
