### ISSUE TITLE
Classes on a HTML SELECT are removed

### ISSUE THREAD

**Issue by nicolomonili** [Grsmto/simplebar#589]
**Describe the bug**
The classes are removed from the HTML select on the popup.

**To Reproduce**
- run the jsfiddle
- the classes of the select on the popup (sweetalert library) are removed

**Expected behavior**
The select on the popup should have the class MYCUSTOMCLASS

**Reproducible example**
[https://jsfiddle.net/k0x169oe/](https://jsfiddle.net/k0x169oe/)

**Additional context**
I noticed that deleting the simplebar library solves the problem (try on the jsfiddle). More specifically, i noticed that by removing **HTMLSelectElement** from the **domIterables** variable, the problem no longer occurs.

```
// iterable DOM collections
// flag - `iterable` interface - 'entries', 'keys', 'values', 'forEach' methods
 domIterables = {
	  CSSRuleList: 0,
	  CSSStyleDeclaration: 0,
	  CSSValueList: 0,
	  ClientRectList: 0,
	  DOMRectList: 0,
	  DOMStringList: 0,
	  DOMTokenList: 1,
	  DataTransferItemList: 0,
	  FileList: 0,
	  HTMLAllCollection: 0,
	  HTMLCollection: 0,
	  HTMLFormElement: 0,
	  ---> HTMLSelectElement: 0,
	  ....
};
```

**Comment by Grsmto** [comment]
I think you posted this on the wrong repository!
