### ISSUE TITLE
Add TypeScript Definition for Vue

### ISSUE THREAD

**Issue by alexmccabe** [Grsmto/simplebar#600]
SimpleBar's mission statement is to keep things simple and stick to the native scroll behaviour as much as possible. However if you have a suggestion that falls within this approach that hasn't already been proposed, we'd love to hear it!

**Is your feature request related to a problem? Please describe.**
I see that the React version has TS definitions, but the Vue version does not. Is there scope to add them? I've created my own definition file, but it's a little lacking comparatively to the React version

**Describe the solution you'd like**
A TS definition for the Vue library

**Describe alternatives you've considered**
I've created my own TS definition, which works well enough, but I think it would be useful for everyone if there were a definition included in the lib.

**Additional context**

This is my implementation for anyone that ends up here

```ts
declare module 'simplebar-vue' {
    import Vue from 'vue';
    import SimpleBar from 'simplebar';

    export class SimpleBarComponent extends Vue {
        SimpleBar: SimpleBar;
        contentElement: HTMLDivElement;
        scrollElement: HTMLDivElement;
    }

    export default SimpleBarComponent;
}
```

**Comment by Grsmto** [comment]
Released in [simplebar-vue@1.7.0](https://github.com/Grsmto/simplebar/releases/tag/simplebar-vue%401.7.0).
