### ISSUE TITLE
Type error: 'SimpleBar' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by tcetin** [Grsmto/simplebar#604]
I am getting an error during the NextJS build process like in below:

`Type error: 'SimpleBar' cannot be used as a JSX component.`

I am using ^2.3.6 as simplebar-react version.

How can I fix this?

**Comment by TeckTn** [comment]
I have the same issue any workaround ?

**Comment by markingman** [comment]
As a hack fix I renamed the .ts file (node_modules/simplebar-react/dist/simplebar-react.d.ts) to .tsx.

I've added this to our build as an intrim fix:
[ -f "node_modules/simplebar-react/dist/simplebar-react.d.ts" ] && mv "node_modules/simplebar-react/dist/simplebar-react.d.ts" "node_modules/simplebar-react/dist/simplebar-react.d.tsx"

For me it was compiling locally with yarn but not npm (which is what our Dockerfile was using).

I guess ideally there's a way to specify the .ts file to be assumed to be JSX somehow?

**Comment by Grsmto** [comment]
I don't understand this issue. This used to work just fine AFAIK and we didn't change anything. I saw some people complaining about something like this with the latest version of `@types/react` could it be related?

**Comment by markingman** [comment]
Yes we didn’t change anything at our end either… I suspect it was a point release change in (about a caret ^ version number in package.json) but haven’t had chance to look further.

**Comment by rustedwolf** [comment]
I have the same issue, full error text (maybe it will help):

> TS2786: 'SimpleBar' cannot be used as a JSX component.
  Its instance type 'SimpleBar' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("./node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
          Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, props

**Comment by OchreFox** [comment]
**Here's a workaround for people looking for a solution:**
I installed react-beautiful-dnd and also got the same error:
```
'SimpleBar' cannot be used as a JSX component.
  Its instance type 'SimpleBar' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("./node_modules/@types/react-beautiful-dnd/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
```

I managed to track the error and this dependency introduced types for react in v18. For context, I'm using Typescript with React 17 since I have some dependencies that are not fully compatible with v18. This is the command output:
```
npm ls @types/react
ROOT-PROJECT@1.0.0 <PROJECT_PATH>
├─┬ @types/react-beautiful-dnd@13.1.2
│ └── @types/react@18.0.15
├─┬ @types/react-dom@17.0.17 extraneous
│ └── @types/react@17.0.45 extraneous
├─┬ @types/react-window@1.8.5
```
The same package I installed also installed the types for React 18, so the only thing to be done is to override this dependency when installing. In npm is done by forcing the dependency version in the `overrides` section in the package.json file. I'm using yarn v1 so the directive is called `resolutions`.

After modifying the package.json file, I restarted VS Code and the error is now gone.

**Comment by GitHub-Cool** [comment]
> **Here's a workaround for people looking for a solution:** I installed react-beautiful-dnd and also got the same error:
> 
> ```
> 'SimpleBar' cannot be used as a JSX component.
>   Its instance type 'SimpleBar' is not a valid JSX element.
>     The types returned by 'render()' are incompatible between these types.
>       Type 'React.ReactNode' is not assignable to type 'import("./node_modules/@types/react-beautiful-dnd/node_modules/@types/react/index").ReactNode'.
>         Type '{}' is not assignable to type 'ReactNode'.
> ```
> 
> I managed to track the error and this dependency introduced types for react in v18. For context, I'm using Typescript with React 17 since I have some dependencies that are not fully compatible with v18. This is the command output:
> 
> ```
> npm ls @types/react
> ROOT-PROJECT@1.0.0 <PROJECT_PATH>
> ├─┬ @types/react-beautiful-dnd@13.1.2
> │ └── @types/react@18.0.15
> ├─┬ @types/react-dom@17.0.17 extraneous
> │ └── @types/react@17.0.45 extraneous
> ├─┬ @types/react-window@1.8.5
> ```
> 
> Now the only thing to be done is to override this dependency when installing. In npm is done by forcing the dependency version in the `overrides` section in the package.json file. I'm using yarn v1 so the directive is called `resolutions`:
> 
> ```json
>  "resolutions": {
>     "@types/react": "17.0.39"
>   },
> ```
> 
> After modifying the package.json file and running `yarn install`, I restarted VS Code and the error is now gone.

It worked

**Comment by rolanday** [comment]
Ran into similar issue here. Since simplebar-react is just a small (single file) wrapper around simple bar-core, I added the [code](https://github.com/Grsmto/simplebar/blob/master/packages/simplebar-react/index.tsx) directly to my project, removed simplebar-react dep (and added simplebar-core), and works well.
