### ISSUE TITLE
Auto-attach with `data-simplebar` does not work in Chrome, IE11, Edge on Windows

### ISSUE THREAD

**Issue by lsorber** [Grsmto/simplebar#61]
Appending `data-simplebar` to the element is not enough to attach the scrollbar to Chrome, IE11 and Edge on Windows, while it does work for Firefox. I need to add `new SimpleBar(el)` to get it to attach in those browsers.

**Comment by Grsmto** [comment]
I can't reproduce this issue (I'm testing using Browserstack). Could you tell me what exact version of Chrome for ex this is happening? Or maybe a jsfiddle where I can experience this issue?

Thanks!

**Comment by lsorber** [comment]
Upon further inspection, the problem is slightly more complex than I thought. The issue is that I load simplebar with the `async` attribute. Apparently, Firefox handles `async` scripts differently from Chrome, IE11 and Edge.

More specifically, the issue appears to be that the `DOMContentLoaded` event has already fired before simplebar has the chance to register the event listener.

jQuery and other libraries deal with this problem like by querying the `document.readyState` [1].

[1] http://stackoverflow.com/questions/9237044/async-loaded-scripts-with-domcontentloaded-or-load-event-handlers-not-being-call

**Comment by Grsmto** [comment]
Okay that makes sense, should be fairly easy to fix.
Thanks for this!

**Comment by lsorber** [comment]
You're welcome, happy to help improve an already awesome 🥇 library!
