### ISSUE TITLE
Element with no fixed height (or fixed parent height) grows indefinitely

### ISSUE THREAD

**Issue by lsorber** [Grsmto/simplebar#62]
If you attach the scrollbar to an element without a fixed height (or attach it to an element whose parent does not have a fixed height), simplebar will keep increasing the element's height indefinitely. Probably has something to do with the mutationobserver.

The workaround I have now is basically to fix the scrollable element's height:
```
var menu = document.getElementById('menu');
menu.style.height = menu.clientHeight + 'px';
new SimpleBar(menu); // Need to manually attach, cf. issue #61.
```
but this is less than ideal because the scrollable element may need to change height (e.g., when the user rotates his/her device's screen).

**Comment by Grsmto** [comment]
Hi Isorber,
Sorry I don't seem to understand the issue, how can it have a scrollbar if the element or his parent don't have a fixed height?
The scrollbar by definition is triggered because the children content has bigger height than the parent height. But if parent doesn't have a height...Or maybe you mean with a height as percentage?

Maybe you could provide a jsfiddle? (taking this one as an example https://jsfiddle.net/pctt4d6k/)
Thanks!

**Comment by lsorber** [comment]
In my use case I only require a horizontal scrollbar, which I achieve by setting `white-space: nowrap`. Here's a minimal example that reproduces the issue: https://jsfiddle.net/lsorber/a1bw7k8k/1/

If you don't set the `max-height` property of the `.wrap` element, simplebar will continue to grow the height of the element indefinitely. Because of `max-height`, it finishes after a few iterations.

Let me know if you need any further help identifying the issue.

**Comment by Grsmto** [comment]
Ah okay makes more sense now! it was an horizontal overflow 😅
Thanks for this I'll take a look!

**Comment by Grsmto** [comment]
Hey,
I released a version that should hopefully fix it, if you can test and let me now it would be awesome! :)

**Comment by lsorber** [comment]
Hi @Grsmto, I just tested everything in Chrome, Firefox, IE11 and Edge on Windows, and everything is working smoothly out of the box! Both the `async` and growing container bugs have been resolved. Thanks a lot.
