### ISSUE TITLE
No support for `RefCallback`

### ISSUE THREAD

**Issue by Vovan-VE** [Grsmto/simplebar#622]
https://github.com/Grsmto/simplebar/blob/160dc756fad6340b667d283b48d3683486392703/packages/simplebar-react/index.js#L86-L89

`ForwardedRef<T>` can also be a callback `(instance: T | null) => void`. However it is not supported now.

```js
if (typeof ref === 'function') {
  ref(instance);
  // and also `ref(null);` somewhere else
} else if (ref) {
  ref.current = instance;
}
```

**Comment by Grsmto** [comment]
Sounds good. Just not sure what you mean by your comment. `ref(null);` wouldn't pass the `if (ref)` condition anyway no?

**Comment by Vovan-VE** [comment]
I mean, when `ref` is a callback, it should be called with `T` on mount and with `null` on unmount.
Now you have no assignment `ref.current = null` on unmount phase. In some specific case (mostly with `RefCallback`) it may be an issue.
