### ISSUE TITLE
how to customize simplebar like twitch.tv

### ISSUE THREAD

**Issue by muflih1** [Grsmto/simplebar#624]
how i can customize this simplebar library like twitch.tv

**Comment by tlthiem** [comment]
are you serious? what kind of issue is this?

**Comment by Grsmto** [comment]
You can do it with CSS. Best is to inspect the scrollbar directly on twitch.tv with the browser developer tools and copy the CSS from there.
I will close this because I think it should be easy enough to find how to do this on your own! Good luck.
