### ISSUE TITLE
Performance Problems on simplebar-angular

### ISSUE THREAD

**Issue by SebastianPost1996** [Grsmto/simplebar#626]
**Describe the bug**
Moving the mouse inside content wrapped in the simplebar component causes a lot of unnecessary template updates.

**To Reproduce**

1. Open a page with content wrapped inside the simplebar component.
2. Open Angular development tools -> profiler -> start recording.
3. Move the mouse inside the wrapped content.
4. The profiler records an unnecessarily large amount of template updates.

**Proposed solution**
Angular forces a template update when a DOM Event is handled, so this component likely has an event handler on the mousemove event. There should either be an alternative handler or it could be debounced (with RxJs debounceTime operator) to force less template updates.

**Comment by SebastianPost1996** [comment]
Fix proposal here: https://github.com/Grsmto/simplebar/pull/631

**Comment by Grsmto** [comment]
Published as `simplebar-angular@2.5.0`.
