### ISSUE TITLE
Allow CSS-based fallback

### ISSUE THREAD

**Issue by lsorber** [Grsmto/simplebar#63]
In case the user does not have JavaScript enabled, it would be good to be able to set a CSS-based fallback like:
```css
overflow-x: scroll; /* or overflow-y */
-webkit-overflow-scrolling: touch;
```

However, simplebar currently does not disable the container's overflow property when it attaches itself, resulting in both a native and simplebar scrollbar.

**Comment by Grsmto** [comment]
I'm not sure to get it, it should work just fine with JS disabled as the css (`overflow: hidden`) is added in JS. Seems to work fine for me when I try on http://grsmto.github.io/simplebar/

**Comment by lsorber** [comment]
Here's a minimal working example of the issue (with v2.3.2): https://jsfiddle.net/lsorber/a1bw7k8k/

In the CSS, I set `overflow-x: scroll` so that if JavaScript is disabled or SimpleBar is otherwise not available, the browser's native scrollbar takes over. However, SimpleBar does not remove this `overflow: scroll` fallback when it attaches itself, resulting in both the native and SimpleBar scrollbars rendering simultaneously.

---

There is a second issue that appears in the above demo (let me know if you want me to create a separate GH issue for it): if I scroll the content with my mouse, I see both the horizontal and vertical SimpleBar scrollbars. If I scroll by swiping my finger (I have a touchscreen computer), I only see the horizontal SimpleBar scrollbar. The vertical scrollbar show not be appearing at all since there is nothing that overflows vertically.

**Comment by Grsmto** [comment]
Hey, it seems to be working fine to me when I remove your `overflow` property.
I update to the latest SimpleBar version as well: https://jsfiddle.net/a1bw7k8k/5/

**Comment by lsorber** [comment]
I agree SimpleBar works when you remove the `overflow-x: scroll` property on the wrapper element. However, the actual issue here is that SimpleBar should also work _with_ `overflow-x: scroll` set on the wrapper element. The motivation for this is that if JavaScript is disabled or SimpleBar is blocked from loading for some reason, then at least the native scrollbar (due to `overflow-x: scroll`) will be there for the user as a fallback.

**Comment by Grsmto** [comment]
Okay I understand now! this should be covered in this section of the doc (and with the latest version) https://github.com/Grsmto/simplebar#non-js-fallback

Hope it helps!

**Comment by lsorber** [comment]
Yes, that should do the trick.
