### ISSUE TITLE
[simplebar-react] Cannot read properties of null (reading 'setAttribute')

### ISSUE THREAD

**Issue by catamphetamine** [Grsmto/simplebar#635]
Passing a function as a child doesn't work:

```js
<SimpleBar>
  {({ scrollableNodeRef, contentNodeRef }) => {
    // Now you have access to scrollable and content nodes
    return <div></div>;
  }}
</SimpleBar>
```

Errors at line:

```js
function setAccessibilityAttributes() {
  var ariaLabel = this.options.ariaLabel || 'scrollable content';
  this.contentWrapperEl.setAttribute('tabindex', '0'); // <----------
```

**Comment by catamphetamine** [comment]
Looking at the source code, it's not clear how it's even supposed to work:

```js
            <div className="simplebar-offset">
              {typeof children === 'function' ? (
                children({ scrollableNodeRef, contentNodeRef })
              ) : (
                <div
                  {...scrollableNodeProps}
                  className={`simplebar-content-wrapper${
                    scrollableNodeProps.className
                      ? ` ${scrollableNodeProps.className}`
                      : ''
                  }`}
                >
                  <div className="simplebar-content">{children}</div>
                </div>
              )}
            </div>
```

The code snippet above suggests that a developer has to supply the whole structure of `<div/>`s, with the exact class names and the exact properties which aren't passed to the `children` function by the way so it's unclear how is it supposed to get those.

**Comment by catamphetamine** [comment]
An alternative solution would be passing `ref` to `<SimpleBar/>` but that wouldn't always work in cases when that `ref` is expected to be present in `useEffect()` or `useLayoutEffect()` in some child element because children's effects run before the parent's effects, and `<SimpleBar/>` creates a `ref` in a `useEffect()`.

**Comment by catamphetamine** [comment]
@Grsmto 

> You are right you still have to pass the right className to the element that get the `scrollableNodeRef`. I think we could prob improve that in the next version by passing down the right class as a prop as well.

If what you're saying is accurate then that means that the example provided in the README is wrong:

```js
<SimpleBar>
  {({ scrollableNodeRef, contentNodeRef }) => {
    // Now you have access to scrollable and content nodes
    return <div></div>;
  }}
</SimpleBar>
```

The code snippet above states that one is not required to pass any specific structure as `children` when using this approach, so the example should be fixed to a minimal one that you're positive is gonna work. Or that code snippet should be removed from the README entirely so that not to confuse the people trying it out.

**Comment by catamphetamine** [comment]
@Grsmto 

> if you look [there](https://github.com/Grsmto/simplebar/blob/master/packages/simplebar/demo/Demo.js#L282) or [here](https://github.com/Grsmto/simplebar/blob/master/packages/simplebar/demo/Demo.js#L282) you can see how this is supposed to work

```js
          <SimpleBarReact
            className="demo1"
            autoHide={false}
            data-simplebar-force-visible="x"
            // scrollableNodeProps={{ ref: scrollableElRef }}
          >
            {({ scrollableNodeRef, contentNodeRef }) => (
              <List
                height={300}
                itemCount={1000}
                itemSize={35}
                outerRef={scrollableNodeRef}
                innerRef={contentNodeRef}
                className="simplebar-content-wrapper"
              >
                {({ index, style }) => <div style={style}>Row {index}</div>}
              </List>
            )}
          </SimpleBarReact>
```

I dunno.
Does it expect a child to be a `<div/>` with a class name of `simplebar-content-wrapper`?
Or does it expect any other DOM structure?
What are those two `ref`s for? Are they just for reading the elements' refs? Or should they be used to set the `ref`s? Most likely the latter, but again, unclear.

```js
<div ref={scrollableNodeRef} className="simplebar-content-wrapper">
  <div ref={contentNodeRef}/>
</div>
```

What should `scrollableNodeRef` be attached to? Should it be the outermost div?
What should `contentNodeRef` be attached to? Should it be the div inside the outermost div?

**Comment by catamphetamine** [comment]
@Grsmto So will something like this work then?

```js
<div ref={scrollableNodeRef} className="simplebar-content-wrapper">
  <div ref={contentNodeRef}>
    Content
  </div>
</div>
```

**Comment by Grsmto** [comment]
@catamphetamine yes.
Sorry my 2nd link was wrong: https://github.com/Grsmto/simplebar/blob/master/packages/simplebar/demo/Demo.js#L339

> What are those two refs for? Are they just for reading the elements' refs? Or should they be used to set the refs? Most likely the latter, but again, unclear.

You would sometimes need to use the refs if you want to use SimpleBar with another plugin like infinite scroll plugin. In those cases the plugin would create its own scrolling DOM nodes so SimpleBar needs a way to know what those are. So you use the refs for that.

**Comment by catamphetamine** [comment]
@Grsmto 

> You would sometimes need to use the refs if you want to use SimpleBar with another plugin like infinite scroll plugin. In those cases the plugin would create its own scrolling DOM nodes so SimpleBar needs a way to know what those are. So you use the refs for that.

I see, so those refs are both for writing and reading.

> my 2nd link was wrong

I see, that one's better, but it's still not fully correct.
Something like this would be:

```js
<SimpleBar>
  {({ scrollableNodeRef, contentNodeRef }) => (
    <div ref={scrollableNodeRef} className="simplebar-content-wrapper">
      <div ref={contentNodeRef} className="simplebar-content">
        ...
      </div>
    </div>
  )}
</SimpleBar>
```

The example above seems to be working. Thanks.
Would you update the React component readme to fix the example at the end?
https://github.com/Grsmto/simplebar/tree/master/packages/simplebar-react#accessing-refs
