### ISSUE TITLE
Module not found: Can't resolve 'simplebar/dist/simplebar.min.css'

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [Grsmto/simplebar#636]
I have installed this package in my next js app and following the [react documentation](https://github.com/Grsmto/simplebar/tree/master/packages/simplebar-react). But when I am importing the `simplebar.min.css` as follows:

```
import 'simplebar/dist/simplebar.min.css'
```

I am getting the following error

```
error - ./App/Screens/Shared/Components/ScrollContainer/ScrollContainer.js:3:0
Module not found: Can't resolve 'simplebar/dist/simplebar.min.css'
  1 | 
  2 | import SimpleBarReact from "simplebar-react";
> 3 | import 'simplebar/dist/simplebar.min.css'
  4 | 
  5 | function ScrollContainer({
  6 |     children,
```

I also checked the [sandbox](https://codesandbox.io/s/youthful-framework-i85etf?file=/src/index.js:116-125) and [GitHub](https://github.com/Grsmto/simplebar/blob/master/examples/react/src/App.js) example but can't figure out how you are importing `simplebar.min.css`. Please let me know if i am doing something wrong or there is a bug while using with next js,

Versions:

`"simplebar-react": "^3.0.0",`
`"next": "12.2.5",`

**Comment by ZeeshanAhmadKhalil** [comment]
let me clone the GitHub example and check from where we're getting CSS file

**Comment by ZeeshanAhmadKhalil** [comment]
Copying css from https://cdnjs.cloudflare.com/ajax/libs/simplebar/6.0.0/simplebar.min.js and pasting in a local `.css`  and importing this file in `_app.js` as follows resolves the issue:

```
import '../styles/ScrollContainer.css';
```

**Comment by Grsmto** [comment]
It should be `import 'simplebar-react/dist/simplebar.min.css'` not `import 'simplebar/dist/simplebar.min.css'`.

**Comment by tbl0605** [comment]
Same problem with the [vue documentation](https://github.com/Grsmto/simplebar/tree/master/packages/simplebar-vue), it should be `import 'simplebar-vue/dist/simplebar.min.css';` not `import 'simplebar/dist/simplebar.min.css';`
