### ISSUE TITLE
new css path

### ISSUE THREAD

**Issue by barbalex** [Grsmto/simplebar#638]
We used to import the css like this:
```
import 'simplebar/dist/simplebar.min.css'
```
With simplebar-react v3.1.0 (updated from 2.4.3) it now seems to be:
```
import 'simplebar-core/dist/simplebar.css'
```

Would be nice if that were declared in the release (https://github.com/Grsmto/simplebar/releases/tag/simplebar%406.0.0).

Thanks for this great project.

**Comment by Grsmto** [comment]
Hi @barbalex ,
That's right, I think there was a mistake in the documentation before and it was meant to be `import 'simplebar-react/dist/simplebar.min.css'`. I will add that to the release to make it clear because that's a deal breaker! Thanks for pointing this out.
