### ISSUE TITLE
TypeError when creating SimpleBar with wrapContent set to false

### ISSUE THREAD

**Issue by GREsau** [Grsmto/simplebar#64]
In v2.2.1, creating a SimpleBar with the wrapContent option set to false fails with this error:

> TypeError: this.contentEl is undefined

As far as I can tell, this was introduced in 7df84101d0c7306383f0109b6c4aff6db859dc96, as this.contentEl is now only assigned to when wrapContent is true

**Comment by Grsmto** [comment]
Thanks for this.
This project needs tests asap! :o

**Comment by wasd171** [comment]
I experience the same issue with 2.2.2. It is fixed in the source code, but packaged version still does not assert correct values to `this.contentEl` and `this.scrollContentEl`

**Comment by Grsmto** [comment]
Hi, I just release a new version 2.3.0 that should solve this issue. Let me know, thanks!
https://github.com/Grsmto/simplebar/releases/tag/v2.3.0

**Comment by wasd171** [comment]
@Grsmto thanks! works fine for me. Is it on npm already too?

**Comment by Grsmto** [comment]
@wasd171 yes it is!
