### ISSUE TITLE
Add typings field in package.json

### ISSUE THREAD

**Issue by Daniel-Knights** [Grsmto/simplebar#641]
**Describe the bug**
TS is complaining that it can't find a declaration file for this package.

**To Reproduce**
Import the package in a TS project.

**Comment by AndreyChechel** [comment]
While there is no `typings` field, it seems possible to get the issue round by adjusting the path:

```ts
import SimpleBar from "simplebar/dist";
```

**Comment by upikoth** [comment]
Closed: https://github.com/Grsmto/simplebar/pull/661

simplebar@6.2.3
