### ISSUE TITLE
Can't import SimplebarAngularModule on newly created Angular 15 project

### ISSUE THREAD

**Issue by schlonzovg** [Grsmto/simplebar#642]
**Describe the bug**
As soon as I add 

import { SimplebarAngularModule } from 'simplebar-angular';

to my newly created Angular app the part 'simplebar-angular' is being red-underlined by Visual Studio Code complaining "Cannot find module 'simplebar-angular' or its corresponding type declarations.". My package.json looks like this:

"name": "example-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^15.1.0",
    "@angular/common": "^15.1.0",
    "@angular/compiler": "^15.1.0",
    "@angular/core": "^15.1.0",
    "@angular/forms": "^15.1.0",
    "@angular/platform-browser": "^15.1.0",
    "@angular/platform-browser-dynamic": "^15.1.0",
    "@angular/router": "^15.1.0",
    "rxjs": "~7.8.0",
    "simplebar-angular": "^3.2.0",
    "tslib": "^2.5.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.1.3",
    "@angular/cli": "~15.1.3",
    "@angular/compiler-cli": "^15.1.0",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.9.4"
  }
}

**To Reproduce**
1. Open Visual Studio Code with installed @angular/cli
2. Create new project with "ng new example-app"
3. Open newly created project
4. Install simplebar-angular by using "npm install simplebar-angular --save"
5. Add import to app.module.ts as described in the simplebar-angular documentation ( import { SimplebarAngularModule } from 'simplebar-angular'; )

**Expected behavior**
I can import the SimplebarAngularModule and use it in my Angular app

**Additional context**
I am on a Windows 10 machine with the latest updates and I am using Visual Studio Code for development

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| simplebar-angular | 3.2.0
| npm                       | 8.19.3
| Operating System | Windows 10

**Comment by Grsmto** [comment]
I just released a new version that should fix it.

**Comment by schlonzovg** [comment]
Great! It seems to work! Thanks for the quick fix!
