### ISSUE TITLE
[Feature] Delay before scrollbar hide

### ISSUE THREAD

**Issue by daniil-kh** [Grsmto/simplebar#645]
I'd really like to see ability to set timeout before scrollbar hides as it was in previous version (via `timeout` arg)

**Possible solution**

I think it will be possible to implement it as in previous version (with help of `debounce` from `lodash`). So it will be something like this
```ts
this.hideScrollbar = debounce(this.hideScrollbar.bind(this), this.options.timeout)
```

**Comment by Grsmto** [comment]
Hey,
You can do it by overriding the CSS like this:

```
.simplebar-scrollbar:before {
   transition-delay: XXX;
}
```

Hope this helps. I'll add it to the doc.

**Comment by daniil-kh** [comment]
Thanks, that work flawless)

Have this in docs will very nice
