### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by arobert93** [Grsmto/simplebar#655]
**Describe the bug**

Installing `simplebar-react` requires `lodash` to be installed.

```bash
Error: Cannot find module 'lodash'
Require stack:
- /node_modules/simplebar-core/dist/index.cjs
- /node_modules/simplebar-react/dist/index.cjs
- /.next/server/pages/_app.js
```

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 3.2.1
| Browser          | Chrome
| npm/Yarn         | 8.19.2
| Operating System | MacOS 13.0.1

**Comment by ahmadertarizqi** [comment]
I have the same issue about this when using nextjs project

**Comment by exilvm** [comment]
Can confirm the issue.

**Comment by ericaig** [comment]
I'm having the same problem as well
```
"next": "^13.2.4",
"react": "^18.2.0",
"simplebar": "^6.2.1",
"simplebar-react": "^3.2.1",
```

**Comment by Grsmto** [comment]
Fixed in latest version! thanks.
