### ISSUE TITLE
lodash reference not found in Angular 15

### ISSUE THREAD

**Issue by axmad22** [Grsmto/simplebar#663]
**Describe the bug**
Building Angular 15 with simplebar fails, with error :

_error TS2688: Cannot find type definition file for 'lodash'._
**reference types="lodash"**

_error TS7016: Could not find a declaration file for module 'lodash-es'._
**import type { DebouncedFunc } from 'lodash-es';**

angular/common: 15.2.0,
simplebar-angular: "3.2.2",
OS: Linux 

I cleared  removed node_modules, package-lock.json, then npm cache clear --force and npm install again, and still nothing same error.

**Comment by Grsmto** [comment]
Thanks for the report. Fixes at `simplebar-angular@3.2.3`.
