### ISSUE TITLE
forceEnabled not working

### ISSUE THREAD

**Issue by MentalGear** [Grsmto/simplebar#67]
First of, let me say this is a great plugin.

However, using it on MacOS ( 12 ), I found that the setting "forceEnabled" won't initialize a custom scrollbar. No elements are added to the DOM.

The same also happens on the demo page for this plugin (btw: the demo page uses only v.1 ).

**Comment by MentalGear** [comment]
I tried to enable it using:

        var SimpleBar_Controller = new SimpleBar( $(".example")[0], {
            forceEnabled: true,
            autoHide: false
        })

However, the only thing that happens, is that on the example container, "overflow: auto" is set.

**Comment by Grsmto** [comment]
Hi,
I know where it comes from, I'll be able to fix this tonight!

**Comment by MentalGear** [comment]
Let me know, if I can help you ? :)

**Comment by Grsmto** [comment]
Hey, actually it's not as simple as what I thought. There is a regression on the latest version that breaks `forceEnabled`, I'll need more time to fix it. Try using an older version maybe.
Sorry about that :/

**Comment by MentalGear** [comment]
Oh, okay. :-/
Do you know by chance what by version it was still working?
I used 2.1. previously, where it also seemed to have been broken already.

**Comment by Grsmto** [comment]
Yes, that's when the bug has been introduced, try v2.0.3.

**Comment by MentalGear** [comment]
Thanks for the reactivity!
Make sure to let me know if you need help or additional testing with the forceEnabled issue!

**Comment by Grsmto** [comment]
Hey,
I actually did some progress yesterday solving this, I'll try to push something tonight. If I can't deploy a fix by that, I'll simply merge the PR of Webxl.
Thanks for your patience :)

**Comment by Grsmto** [comment]
I published the fix from @webxl .
