### ISSUE TITLE
removeObserver() not working

### ISSUE THREAD

**Issue by webxl** [Grsmto/simplebar#69]
I was trying to disable the global mutation observer, but it's not working. globalObserver is never assigned to the static observer property:
```javascript
static initHtmlApi() {
    // MutationObserver is IE11+
    if (typeof MutationObserver !== 'undefined') {
      // Mutation observer to observe dynamically added elements
      const globalObserver = new MutationObserver(mutations => {

...

static removeObserver() {
    this.observer && this.observer.disconnect();
  }
```

Also, there should be a way to have opt-in global observers in addition to opt-out. I know there's the convenience factor, but for pages with a lot of DOM manipulation, this feature is very costly. so that would require manual instantiation. Perhaps there could be an alternate module, and you would import it with something like ``import NotSoSimpleBar from 'simplebar/manual';`` and they could share  the bulk of code in some other module.

**Comment by Grsmto** [comment]
Good point. I thought about that but as a first version I didn't implement it until I actually figure out some cases we have performances issues with it.
Did you encounter a case where it actually impacts on performances?
As the observer is naturally debounced it shouldn't have a huge impact even if the page has lot of DOM manipulations but I didn't have such a scenario yet.

**Comment by webxl** [comment]
Yes, I have a table built with marionette.js and it has infinite scroll to show additional search results. So anywhere from 100 to a couple thousand mutations on a single query. Every time the user modifies the query, the current results get removed and another 100 get added. Within the table rows, there are a bunch of elements, too. So the events start to pile up.

**Comment by Grsmto** [comment]
Hi, I just release a new version 2.3.0 that should solve this issue. 
I leave this issue open as I still want to work on performances and to have a separate module without the mutationObservers.

**Comment by webxl** [comment]
Thanks. I spent some time on splitting the declarative (watching for the data-simplebar attribute) feature out last week: https://github.com/webxl/simplebar/tree/split-out-declarative. Not sure if you want to do it that way, but it might give you some ideas.  I also worked on adding mocha tests, but I'm having trouble testing the mutation observer: https://github.com/webxl/simplebar/tree/unit-tests. I like testing things in node.js if possible, but for this, I might need to switch to karma-webpack so that we get the full browser API.

**Comment by Grsmto** [comment]
Very interesting stuff. I liked the approach you proposed in your first comment with a "sub-module" `simplebar/manual`. This should be doable without having to duplicate some code I guess.
About the tests that's awesome! For the mutation observer I guess that's really tricky to test as you would have to mock it or something...

**Comment by webxl** [comment]
Yeah, the naming is a bit odd. I wanted to keep it backward compatible. It's still loaded via a submodule though: https://github.com/webxl/simplebar/blob/unit-tests/test/imperative.js#L2
