### ISSUE TITLE
Compatibility with react-virtuoso

### ISSUE THREAD

**Issue by tlthiem** [Grsmto/simplebar#692]
Looks like quite a few people, me included, are [struggling](https://github.com/petyosi/react-virtuoso/issues/253) to get simplebar to work with [`react-virtuoso`](https://github.com/petyosi/react-virtuoso) virtualization library

@Grsmto would you mind taking a look?

The library is providing access to its scroll element via a `Scroller` [components prop](https://virtuoso.dev/custom-scroll-container/#list-with-custom-scroller)

People got it [working](https://codesandbox.io/p/sandbox/billowing-night-65cmq9?file=%2Fsrc%2Findex.js%3A20%2C37) with "rc-scrollbars" lib.

Given that react-virtuoso is becoming a defacto standard virtualization lib it would be nice to have a reference implementation, if possible.

**Comment by Grsmto** [comment]
Hi @tlthiem ,

I did an example on Codesandbox, let me know if that works: https://codesandbox.io/p/sandbox/lucid-morning-dkhpgx

important part is that I had to override some CSS from react-virtuoso wrapper like this:
```
.simplebar-content > * {
  position: static !important;
}
```

idk if there is a cleaner way to do that, but seems to work. Hope that helps.

**Comment by Grsmto** [comment]
Hi @tlthiem ,

I tried a few things but couldn't find a good way of doing it. It will require Simplebar to mount before react-virtuoso can mount. So there will be a re-render, like in the example provided in the issue you referenced: https://codesandbox.io/p/sandbox/lucid-morning-dkhpgx

**Comment by tlthiem** [comment]
Alright, thanks for clarifying that there is no better way. Appreciate it!
