### ISSUE TITLE
Can't import SimplebarAngularModule  in Angular 17

### ISSUE THREAD

**Issue by bishal-saha** [Grsmto/simplebar#693]
**Describe the bug**
When import {SimplebarAngularModule} from "simplebar-angular"; in stabnd alone componeht

**To Reproduce**
1.Install simplebar-angular by using "npm install simplebar-angular --save"
2. Add import to app.module.ts as described in the simplebar-angular documentation ( import { SimplebarAngularModule } from 'simplebar-angular'
4. See error in cli: [ERROR] TS2307: Cannot find module 'simplebar-angular' or its corresponding type declarations. [plugin angular-compiler]

**Expected behavior**
I can import the SimplebarAngularModule and use it in my Angular app

**Reproducible example**

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        |  3.2.5
| Browser          | Chrom
| npm         | 10.2.4
| Operating System | Ubuntu

**Comment by andreoromera** [comment]
Same here

**Comment by IvanUmanets** [comment]
version 3.2.5 doesn`t have 1 file  ( simplebar-angular.d.ts ) 
use 3.2.4 as stable version

**Comment by Grsmto** [comment]
fixed in 3.2.6. Sorry about that!
