### ISSUE TITLE
If I want to use that component in vue 2.6, how can I implement it?

### ISSUE THREAD

**Issue by qingyun1029** [Grsmto/simplebar#694]
## 💬 Questions and Help

Please before asking your question:

If I want to use that component in vue 2.6, how can I implement it? 
Thanks!

**Comment by Grsmto** [comment]
Unfortunately I think we only support vue 2.7 minimum.
Maybe try to upgrade to 2.7?
Otherwise there are a lot of alternative libraries!

Thanks
