### ISSUE TITLE
How to get compiled file fore jQuery website?

### ISSUE THREAD

**Issue by jeevasusej** [Grsmto/simplebar#706]
I need the compiled files to be used in the jQuery website. I came across an example where the compiled file was referenced in the "dist" folder. However, when I checked the release folder, I couldn't find a "dist" folder.

**Comment by Grsmto** [comment]
Are you looking for this?

https://unpkg.com/simplebar@latest/dist/simplebar.min.js
https://unpkg.com/simplebar@latest/dist/simplebar.css

It's documented [here](https://github.com/Grsmto/simplebar/tree/master/packages/simplebar#installation)
