### ISSUE TITLE
Custom cursor when hovering scrollbar, without breaking mouse wheel

### ISSUE THREAD

**Issue by kalnode** [Grsmto/simplebar#707]
I'm trying to have a custom cursor when hovering the scrollbar.

Ideally, there would be a CSS-only solution. Here is a snippet from another [thread](https://github.com/Grsmto/simplebar/issues/490):
```
.simplebar-track {
    cursor: default;
    pointer-events: auto !important;
}
```

**Problem:**

The cursor does change with this, but because pointer-events is no longer `none`, the scrollbar area now captures the pointer event and mouse wheel scrolling no longer works (because it doesn't pass to the parent container).

**Current work around:**

On simplebar initialization, in JS I'm creating a listener to manually change the mouse cursor when hovering the scrollbar. Everything seems to work fine with this.

```
  function isEventInElement(event: MouseEvent, element: Element) {
      var rect = element.getBoundingClientRect()
      var x = event.clientX
      if (x < rect.left || x >= rect.right) return false
      var y = event.clientY
      if (y < rect.top || y >= rect.bottom) return false
      return true
  }

const scrollbar = mySimpleBarInstance.querySelector('.simplebar-track.simplebar-vertical') as HTMLElement

mySimpleBarInstance.addEventListener('mousemove', (evt) => {
    if (scrollbar) {
        if (isEventInElement(evt, scrollbar)) {
            document.documentElement.style.cursor = 'pointer'
        } else {
            document.documentElement.style.cursor = 'none'
        }
    }
})
```

**QUESTION:** Is there truly no CSS-only way to do this? I've been wrestling with CSS for hours.

**Comment by Grsmto** [comment]
No I don't think there is a solution for this with Simplebar :(

We would have to not rely on `pointer-events: none` and trigger the mousewheel event in JS...
If you want more customisation than Simplebar propose you should check https://kingsora.github.io/OverlayScrollbars/
