### ISSUE TITLE
Custom scrollbar not working when initiated as new Simplebar()

### ISSUE THREAD

**Issue by rajasri215** [Grsmto/simplebar#72]
Please find below the code snippet.
https://www.w3schools.com/code/tryit.asp?filename=FEHSNK518SGL

Custom scrollbar works fine when used as `<div data-simplebar></div>` but not when used as `new SimpleBar($('#myElement')[0])`

Also, trying to add scrollbar using `new SimpleBar(document.getElementById('#myElement'), { wrapContent: false });` shows javascript error in the console.

Tested in Chrome Version 57.0.2987.133 (64-bit) and IE 11

**Comment by wasd171** [comment]
Might be a dublicate of https://github.com/Grsmto/simplebar/issues/64

**Comment by Grsmto** [comment]
Hi, I just release a new version 2.3.0 that should solve this issue. Let me know, thanks!
https://github.com/Grsmto/simplebar/releases/tag/v2.3.0
