### ISSUE TITLE
Content smaller that container

### ISSUE THREAD

**Issue by wasd171** [Grsmto/simplebar#75]
Hello!

Imagine the following structure:
```
<Container>
    <div className='simplebar-scroll-content'>
        <div className='simplebar-content'>
            <Content/>
        </div>
    </div>
</Container>
```

If `Content`'s height is smaller than `Container`'s, native x-axis scrollbar shows.

**Comment by artaommahe** [comment]
looks related

![image](https://cloud.githubusercontent.com/assets/1944061/25098619/eea4fafe-23b1-11e7-97da-7da27cd0098b.png)

```html
<div class="aep-settings">
    ...
    <div class="simplebar-scroll-content">
        ...
    </div>
</div>
```

`div.aep-settings` has `padding: 24px;`. Without padding looks well

**Comment by Grsmto** [comment]
This should be solved in the latest npm version.

**Comment by artaommahe** [comment]
@GregOnNet `2.3.2` nothing changes for my case with padding on container

**Comment by Grsmto** [comment]
@artaommahe this is normal, you shouldn't apply padding on the container as that's how the native scrollbar gets hidden. Unfortunately I don't think we can do anything about that.
if you want padding you should better use another wrapper as a parent of the element that has SimpleBar on it.

**Comment by artaommahe** [comment]
@Grsmto what about getting container padding and add it to simplebar nodes?

**Comment by artaommahe** [comment]
@GregOnNet also i cannot add inner container to skip padding issue, cause scrollbar on this container will have wrong position - it should be at right edge at element with padding
here it is with additional element with applied simplebar
![image](https://cloud.githubusercontent.com/assets/1944061/25103843/97e93814-23c6-11e7-9840-3b54a4640664.png)
```
- div with padding
  - div with simplebar
    - simple bar nodes and items list
```
