### ISSUE TITLE
Working with flexbox

### ISSUE THREAD

**Issue by artaommahe** [Grsmto/simplebar#77]
Is there any way to make simplebar work with flexbox lists?
This should be horizontal list with X scrolling
http://codepen.io/anon/pen/zwvOWZ?editors=1010
remove `data-simplebar` and it will work as expected.

Maybe we can somehow get rid of additional DOM elements like `.simplebar-scroll-content` and `.simplebar-content` and have list items directly in initial container?

**Comment by Grsmto** [comment]
I had no problem using SimpleBar with flexbox. You may have to apply some specific CSS to the SimpleBar divs to make it work with your layout.
Sadly SimpleBar can't do anything about it as it changes the DOM and you will have to make it fit yourself to your layout.
