### ISSUE TITLE
Scrollbar blinking on list items update

### ISSUE THREAD

**Issue by artaommahe** [Grsmto/simplebar#78]
I have a chat with simplebar on it. On each new messages hidden by default vertical scrollbar appears that leads to scrollbar blinking on messages flow.
Any way to disable scrollbar visibility on updates? Imho it should be visible only on container hover.

**Comment by Grsmto** [comment]
Hey, sorry for the late answer, I believe this has been fixed because I can't reproduce this at the moment. If you remember what method you were using to update your chat let me know. I tested calling `recalculate` and appending elements in the DOM and none are making the scrollbar appear.
