### ISSUE TITLE
Simplebar not working in any browsers

### ISSUE THREAD

**Issue by cbaxter713** [Grsmto/simplebar#79]
I have been using simplebar in development of a new web tool, and it has been working great, but seems to have just stopped working today.  

I'm pulling the js in properly, but no elements with [data-scrollbar] on them are being inited properly.

**Comment by Grsmto** [comment]
This doesn't help much to figure out where the issue comes from. Could you set up a jsfiddle to reproduce your issue? http://jsfiddle.net
Thanks!
