### ISSUE TITLE
Browser specifications missing in the docs, hide scrollbar completely

### ISSUE THREAD

**Issue by rrphotosoft** [Grsmto/simplebar#8]
Hi,
Firstly, let me congratulate you for developing this plugin, this is a very common problem and your plugin will go a long way

I have two issues:
1.How do I hide the scrollbar completely, i.e I do not want to the user to see the scrollbar even while scrolling.
My use case is a situation where there is a div with a fixed-height and a small amount of content initially. At that point, there is no scrollbar. When the user clicks a 'show more' button , more content appears at the bottom, but the div height remains the same, basically overflow-y is switched to scroll.
However I do not want a scrollbar to appear at all, and I don't just want to set visibility to 'hidden' since that will change the width of the rest of the div, and cause elements to jump slightly to the left.
2.How well does your plugin work out in different browsers eg: ie8, ie9 ?

Regards,
RR.

**Comment by Grsmto** [comment]
Hi!

Thanks for the request of browser support. I will think about adding this. However this plugin should work pretty much everywhere (from IE6).
To hide the scrollbar entirely, the simplest way is to apply a css rule like this:
`.simplebar-scrollbar { display: none; }`
It shouldn't shift the content from what I know (but either `visibility: hidden`) so I don't know if it resolves your problem!

**Comment by stepladder** [comment]
I noticed in IE8 and 9 the browser scrollbar appears with the styled scrollbar overlaying it.

![scrollbar](https://cloud.githubusercontent.com/assets/5172399/9788842/391594a6-57c4-11e5-9e02-5bc7174b974d.jpg)

I'm able to hide the styled scrollbar, but would prefer to keep the styled one and hide the browser one.

Is there a way to do this?

Thanks

**Comment by Grsmto** [comment]
@stepladder I am unable to replicate this issue on IE8/9. Could you provide an example? Or are you having the same issue with one of the demo?
Thanks!

**Comment by stepladder** [comment]
That's weird on your demo it works ok, but when I download the demo files and upload to my own server it's broken again;

http://dev.stepladderuk.com/simplebar/demo/

**Comment by Grsmto** [comment]
This issue should be fixed in the latest release. Thanks guys!
