### ISSUE TITLE
A way to detect if content needs scrollbar?

### ISSUE THREAD

**Issue by Aedaeum** [Grsmto/simplebar#80]
Depending on the size of the window, the content may be longer than the display port. Is there a way to detect when a scrollbar is needed? Obviously the native scrollbars only show up if the content is too long. It would be nice if this plugin had that same effect.

**Comment by Grsmto** [comment]
Hey, sorry it's actually already the case but there is a bug in the latest version. It's included in the next version to be released. You can try it by doing `npm install simplebar@next`.

**Comment by Aedaeum** [comment]
I installed using `simplebar@next`. I should note that the comment within the file still says version `v2.3.2`. I checked the `package.json` which says `v2.4.0`.

That being said, I still have the same issue. Even though the native scrollbar has no **bar** (because the content does not overflow), the SimpleBar scrollbar is visible and renders the full length of the track.
![ss 2017-04-19 at 04 53 36](https://cloud.githubusercontent.com/assets/2054218/25207051/c3f362f8-2520-11e7-833b-62417c524fdc.png)

As you can see from the above screen shot, the native scrollbar arrow is greyed out and if I posted the full size image, you would see that there is no "bar" on the track.

**Comment by Grsmto** [comment]
Sorry can you try to `npm install simplebar@next` again, I messed up on the release :(

**Comment by Grsmto** [comment]
No it's not intended but I guess that's the way the browser works and depending on how complex is your layout the resize event of the browser can be really slow. I don't think SimpleBar can do anything about this (for example I don't have the issue on the demo page as laptop is powerful and page is simple I guess).

**Comment by Aedaeum** [comment]
As you close this, I should mention that it only fails when the page is resized so that the scrollbar is no longer needed. The scrollbar stays there.

**Comment by Grsmto** [comment]
Is it constant? Once you resized the window the scrollbar stays constantly? I don't seem to be able to reproduce this issue

**Comment by Aedaeum** [comment]
Yes, it is constant. I can reproduce it every time.
