### ISSUE TITLE
Bug when hitting back button

### ISSUE THREAD

**Issue by jfyzhao** [Grsmto/simplebar#85]
![simplebar](https://cloud.githubusercontent.com/assets/7339981/26466469/b30bfa4c-4143-11e7-9240-465fec13140d.gif)

In the middle of this gif, I hit a link to go to another page, and quickly hit the back button. When i am returned to the original page, the Simplebar scroll becomes buggy where the vertical scroll doesn't work anymore and the container (which doesn't have any x-overflow) suddenly has horizontal scroll.

Using simplebar in a pretty straightforward way - initializing it in my JS as so new SimpleBar($('.left-nav-brand-list')[0], {autoHide: false});

I also tried removing the jquery and just initializing it with data-simplebar and am seeing the same error.

**Comment by jfyzhao** [comment]
Suspicion is that this is related to the fact that when hitting the back button, the simplebar DOM markup is still there causing incorrect height/width calculations. For example, if I go through the same flow, and instead of hitting the back button, I navigate to the previous page via the URL bar, this problem doesnt occur. Is there a workaround for this?

**Comment by Grsmto** [comment]
That's pretty hard to say without knowing your environment. This can come from multiple things.
I guess that you're working in a single page application environment? When you go to the previous page via the URL bar, it forces a page reload, so the plugin is initialised properly.
But when you hit back button, if no page reload occurs, you need to make sure the plugin is initialised properly based on what's in the DOM. You can't init Simplebar on an element that has already been initiated before. You'll have to refresh your element to it's original DOM shape.

**Comment by jfyzhao** [comment]
Yeah turns out its a rails + turbolinks related issue with hitting the back button pulling up a cached version of the DOM, and the JS reinitializing simplebar even though it already exists in the cached version.

Is there a way to destroy the DOM for simplebar? Don't see anything in the documentation but wanted to check.

Thanks @Grsmto !

**Comment by Grsmto** [comment]
There is no way currently to "clean" the DOM from the Simplebar elements. That's something I thought about but didn't implement it until I actual have a good reason to do so.
That may probably be a good idea to add such a function to Simplebar. In the meanwhile you can probably woraround that by cleaning the DOM manually, or maybe keep a copy of the element before Simplebar is added to it and re-apply it when page is left. So when the cached version of the DOM kicks in, it's still the original DOM. It's quite a pain to do to be honest but that's the only solution I see...
Or Simplebar should be able to re-attach itself. Maybe try the `{ wrapContent: false }` option!
It's a pretty weird behaviour to cache the DOM this way tho!

**Comment by jfyzhao** [comment]
Got it, using the wrapContent option combined with removing the vertical and horizontal tracks before reinitializing Simplebar seems to allow it to reattach itself successfully. Kind of a hacky solution but a bit better than cleaning the DOM manually.

Thanks!
