### ISSUE TITLE
Demos are broken

### ISSUE THREAD

**Issue by GregOnNet** [Grsmto/simplebar#86]
Hey @Grsmto,

it seems that the demo page is broken.
Both `js` and `css` sources of simplebar cannot be found (see:. http://grsmto.github.io/simplebar/demos/).

![image](https://cloud.githubusercontent.com/assets/444278/26569390/b796c8a6-450a-11e7-8518-a09a6b14b115.png)

Hope this helps.

Kind Regards
Gregor

**Comment by Aedaeum** [comment]
I can confirm this.
