### ISSUE TITLE
Simplebar not working with web components

### ISSUE THREAD

**Issue by iexplore** [Grsmto/simplebar#87]
This is a great simple piece of software that does exactly what it needs to do but....
I am writing an application in Polymer 2. Polymer 2 is using the new standard [web components](https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom) with shadowdom, etc. Browser without the capability are polyfilled.

Currently simplebar does not work when I activate it on or within a web component.
I assume Simplebar is not working with this new dom feature because there are some changes to find and work with elements, You have to work from shadowRoot from the element like:<element>.shadowRoot.getElementById("toc"). See [here](https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#findall)  for complete example.

**Comment by adrian-moisa** [comment]
I've been using simplebar with web components (no polymer). Seems that it is working quite ok.

**Comment by iexplore** [comment]
You probably didn't use it within in element itself. If you only use webcomponents you don't have to deal with shadow dom. 
I am now using a web component [custom-scrollbar](https://github.com/DoubleTrade/custom-scrollbar) which works quite well.
