### ISSUE TITLE
I can't even make it work...

### ISSUE THREAD

**Issue by kurkweb** [Grsmto/simplebar#92]
I am going to assume it is because I am not doing it through npm like suggested.  I just downloaded the repo and copy/pasted the css & js files into a new folder.  Here are some screen shots of the code and the output. 

Thanks in advance, I'm probably just too n00b.

![2017-06-28_12-48-53](https://user-images.githubusercontent.com/17031549/27649707-8e5d6b40-5c00-11e7-8ae3-e8136d1f05b8.png)

![2017-06-28_12-49-18](https://user-images.githubusercontent.com/17031549/27649712-90b43c34-5c00-11e7-870b-258ec5c2fb6f.png)

**Comment by kurkweb** [comment]
side note, the bar shows up. It just doesn't scroll.

**Comment by Grsmto** [comment]
You should remove any css that you applied on `.simplebar-content` this is an internal div of Simplebar so you shouldn't have to add any css to it. Let me know if it fixes it.

**Comment by kurkweb** [comment]
![2017-06-28_16-38-47](https://user-images.githubusercontent.com/17031549/27659104-4c19d582-5c20-11e7-8540-41020930612a.png)


This is the result of me removing .simplebar-content CSS :/ soo close

**Comment by Grsmto** [comment]
I don't understand, in the screenshot, in your html file, you're showing some code that seems like the output html of Simplebar.
It's pretty confusing.
If I'm right, I think you're doing something wrong. Make sure to read the doc again. To apply Simplebar you *only* need to add `data-simplebar` to an element, like so: `<div data-simplebar></div>` and nothing else.

**Comment by kurkweb** [comment]
Yea I am confused myself... I've read through the ReadMe.  And I realize I am suppose to attach the css and the js files that you created.  And I have, I also tried data-simplebar in the div, but when I constrain the div to a particular height it just locks.

![2017-06-28_18-00-14](https://user-images.githubusercontent.com/17031549/27662472-e4fca31e-5c2b-11e7-9b6a-e734b704f95c.png)
![2017-06-28_18-00-19](https://user-images.githubusercontent.com/17031549/27662473-e90e47be-5c2b-11e7-8f42-7557321a4662.png)

**Comment by kurkweb** [comment]
Would having the jQ library affect anything if I downloaded bootstrap wrong or if I connected it wrong?  You didn't mention anything about npm earlier so I am guessing just downloading the repository is a viable option and then copying and pasting the files into a new folder is fine?  Puzzled...

**Comment by Grsmto** [comment]
Ok your setup seems fine now!
I did an example for you to check with the same setup as you. Just downloading the repository is completely fine. Make sure to use the files from the /dist folder.

There is the example: https://embed.plnkr.co/eBQsQPbbkJNiVtAtdzez/

**Comment by kurkweb** [comment]
Ok, thank you Grsmto... I feel like I am on a much better track.  Now I gotta figure out why it only work with normalize and demo.
