### ISSUE TITLE
Text blurs out for a millisecond when you hover over scroll area

### ISSUE THREAD

**Issue by Spazer9** [Grsmto/simplebar#93]
This is a small issue and more of a cosmetic one.

When you hover over the scroll area, the text kind of blurs out a little (as if you applied some 3d transform to it) but only for like 500ms.

This happens on windows 10 at least. not sure how to fix it since I looked at the css and there's no weird transforms being applied.

Video of the issue: https://s3.amazonaws.com/snaps-bucket/2017/07/54JMtLh/2017-07-03_00-02-05.webm

The effect is more prevalent on darker backgrounds

**Comment by LastReaction** [comment]
I've done more research on this and the issue seems to stop when you disable the CSS transition on `.simplebar-scrollbar:before`. This problem also only happens on Google Chrome. Firefox and Edge do not have this problem.

**Comment by udyux** [comment]
@Spazer9 this looks like antialiasing loss during a transform transition (probably by the `.simplebar-track`).

Try adding `backface-visibility: hidden;` to `.simplebar-content` or to the individual list items. You could also try the same property on the `.simplebar-track` if the above doesn't work.
