### ISSUE TITLE
duplicated scrollbar on firefox

### ISSUE THREAD

**Issue by alexey-sh** [Grsmto/simplebar#94]
Hi, thanks for the library.

I noticed duplicated scrollbar 
<img width="64" alt="2017-07-06 4 50 07" src="https://user-images.githubusercontent.com/1584156/27888222-bdb64f0e-6206-11e7-8c8a-e5afc0b5d1ca.png">
when I tried to set `overflow-y: hidden` it just doesn't scoll anymore
<img width="338" alt="2017-07-06 4 51 33" src="https://user-images.githubusercontent.com/1584156/27888247-de275d46-6206-11e7-83a9-10a33a079c84.png">
How can I fix it?

**Comment by Grsmto** [comment]
It seems like you use an old version of Simplebar. Can you try the latest version and see if it fixes it?

**Comment by CLINT0N** [comment]
Hi, This still seems to be an issue.

I've just installed the latest simplebar from npm, version 2.4.4 and I am seeing duplicate sidebars, not just in Firefox but other browsers too. The native sidebar is not getting hidden.

I tried using the solution in [#73](https://github.com/Grsmto/simplebar/issues/73) but this did not make any difference, and it looks like it is in the css anyway upon inspection.

Are you working on a fix for this?

**Comment by Grsmto** [comment]
Hi @CLINT0N can you try this jsfiddle and see if it's happening  there? https://jsfiddle.net/Grsmto/pctt4d6k/3/
Thanks.

**Comment by CLINT0N** [comment]
Hi @Grsmto 

Thanks for that, it has fixed the issue.

Duplicate sidebars becomes a problem when the overflow css properties are used, the example you sent to me above and also when inspecting the code of your demo you use max-width/max-height instead.

It might be good if this could be added in the documentation somewhere, as I imagine it will catch more people out

Thanks for the great package

**Comment by Grsmto** [comment]
Hey, thanks for the advice. I added a mention in the README about it as suggested! (probably can be improved).

**Comment by SagaraZD** [comment]
Hi,
Same issue here. what was the fix? i think demo jsfiddle  expired.

**Comment by Grsmto** [comment]
@SagaraZD there is no fix actually. This was due to some css styles clashing with SimpleBar ones. Are you on the latest version (2.6.0) and still having this issue?
Make sure you don't have any css interfering with the plugin.

**Comment by SagaraZD** [comment]
Yes, i'm think i'm using latest one.

![untitled](https://user-images.githubusercontent.com/25058474/37825935-91e89a98-2eb7-11e8-8e32-5700508a7876.png)

**Comment by Grsmto** [comment]
What is applying this width and height on .simplebar-scroll-content ? This is definitely what is breaking the plugin, there shouldn't be any width/height on this div.
Also the `box-sizing: content-box` on simplebar-content where is that comes from? This is not from SimpleBar.

**Comment by SagaraZD** [comment]
Hi,
Sorry about the height and width. it's  think it's coming from my Angular script. 
But after i remove it issue still the same. scroll on the native scroll.

![dsfs](https://user-images.githubusercontent.com/25058474/37827177-6d09e6dc-2ebc-11e8-95e0-390ada809fa1.png)

**Comment by Grsmto** [comment]
Ok so it's coming from your Angular script. Here you just removed it manually from the dev tools but your script is removing some styles applied by SimpleBar which are critical and the plugin can't work without them.
I don't  know why your script is doing that but it shouldn't apply breaking styles to that div, especially as this is an internal div created by SimpleBar I don't see a reason for doing so.
