### ISSUE TITLE
Scrollbar showing all the time?

### ISSUE THREAD

**Issue by engineers-nemanjag** [Grsmto/simplebar#95]
I implemented scrollbar, set up the data-simplebar on elements I want, max-heights... But simplebar is always there, even when there is no need for scrolling the page? Anyone has the same issue?

**Comment by solarbeetle** [comment]
Hi - I have the same problem in Chrome and Firefox, but it works in IE Edge....
Did you find a solution to this?

Thanks

Paul

**Comment by solarbeetle** [comment]
Ah, I solved it. I was using a slightly older version of the js file. Using v2.4.3 works for me in all browsers.
