### ISSUE TITLE
Position bug if have radio button inside

### ISSUE THREAD

**Issue by mdss-single** [Grsmto/simplebar#97]
Example with bug
https://codepen.io/mdss/pen/rzNQxG

I have custom styled radio button and label.
When I click latest radio button .simplebar-scroll-content have strange position. What I'm doing wrong?

**Comment by Grsmto** [comment]
I can't seem to reproduce the issue on Chrome mac. What browser/platform are you seeing this issue?

**Comment by mdss-single** [comment]
Mozilla Firefox 54.0.1 (latest version) win7.
Google chrome work perfect (tho webkit too).
I think this is because different behavior of flex model.
I'm try to not use flex, but then plugin doesnt't work.

Two screenshots before checking and after.

![screenshot_3](https://user-images.githubusercontent.com/11454517/28558892-adba904a-711c-11e7-8d96-e4b372245946.png)
![screenshot_4](https://user-images.githubusercontent.com/11454517/28558893-adbcfba0-711c-11e7-9cf4-3dafdf204026.png)

**Comment by mdss-single** [comment]
Fix for me (I use only vertical bar):
1) Set this styles for container .simplebar-scroll-content (adding position)
```
.simplebar-scroll-content {
	box-sizing:content-box;
	position:relative;
	top:0; bottom:0; right:0; left:0;
	overflow-x:hidden;
	overflow-y:scroll;
	min-width:100%;
}
```
2. remove marginBottom from scrollContentEl (because I need only vertical)
3. remove paddingBottom from contentEl (because I need only vertical)

Now it's work perfectly. Thanks for plugin!

**Comment by Fisher5991** [comment]
I have the same problem
