### ISSUE TITLE
IE 11 "Object doesn't support property or method 'find'". FF Only works if I open the Dev Tools.

### ISSUE THREAD

**Issue by danielg42** [Grsmto/simplebar#98]
Hi, 

You can check it here: http://projects.gizel.la/asdf/

This works in Chrome perfectly. In Firefox it only works, if I open the Dev Tools and refresh the site, but at least it adds the necessary elements to the DOM. In IE 11, nothing gets added to the DOM, and there is an error:  "Object doesn't support property or method 'find'".

Win7, latest Chrome and Firefox. jQuery 3.2.1 (I tried it with 1.12, but it made no difference.)

**Comment by Grsmto** [comment]
Hi,
It seems like IE11 doesn't support the `find()` function. You should probably use a polyfill in the meanwhile (like polyfill.io or Babel http://babeljs.io/docs/usage/polyfill/).
For Firefox it's really weird as the browser supports this so it's probably unrelated.

**Comment by brentrug** [comment]
i have the same issue... weird that its writte it supports IE11. but on my IE11 i get

`TypeError: Das Objekt unterstützt die Eigenschaft oder Methode "find" nicht`

**Comment by wintercounter** [comment]
Off: I can't believe MS invested time into translating run-time error messages -.-

**Comment by jovpet** [comment]
I don't know does it help, but I had a similar issue due to usage of Array.prototype.find() in my ES6 syntax. Once I changed .find to .filter()[0] it passed in ie11. (I used babel to translate it to es2015 standard)

**Comment by Grsmto** [comment]
This should be fixed with the latest version.
Thanks and sorry for the delay!
